### ISSUE TITLE
Study download is not stopped when using $dicom:close -a

### ISSUE THREAD

**Issue by marcopin** [nroduit/Weasis#103]
I was testing with studies with a big quantity of images. While downloading one study I send command to open another study using $dicom:close -a to close current downloading work. The new study starts downloading but the old study remains.

**To Reproduce**
Open big study using $dicom:get -w url... and, while downloading, open a new study using $dicom:close -a $dicom:get -w url.

**Expected behavior**
It must close all download working, close all studies and begin to download new study.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Weasis Version 3.5.4RC

![image](https://user-images.githubusercontent.com/3383909/67059521-70cccf80-f127-11e9-8cb0-062862b20db4.png)

**Comment by nroduit** [comment]
The download manager works at series level. Calling dicom:close -a will stop downloading if a series has started to be downloaded (see https://github.com/nroduit/Weasis/blob/master/weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/DicomModel.java#L437). So the close action will remove all the existing series and those that are being downloaded.

**Comment by nroduit** [comment]
As the download manager works at the series level, it cannot be considered as an issue. Reopen the issue if you do not believe the issue to be resolved.
