### ISSUE TITLE
4K monitor

### ISSUE THREAD

**Issue by luizinho44** [nroduit/Weasis#109]
Is It possible to configure a resolution greater than 2560x1440? I use 4K monitor (3840 x 2160)

**Comment by nroduit** [comment]
There is no restriction. [HiDPI](https://github.com/nroduit/Weasis/issues/64) is supported since the version 3.5.3

**Comment by luizinho44** [comment]
Ok thank you, where do I reset the monitor configuration in windows 10, I try to reinstall weasis, but it keeps in 2560x1440. I had another full HD monitor on my first installation, maybe this is the cause.

**Comment by nroduit** [comment]
Please start by explaining what the problem is (what do you mean by keeping in 2560x1440) and what is the expected behavior.

There are monitor preferences (calibration and initial screen). From the main menu, open File > Preferences (Alt + P) > Monitors. You should see the resolution at the end of the screen name.
The values are stored in ${user}/.weasis/data/weasis-core-ui/persitence.properties.

**Comment by luizinho44** [comment]
I use this resolution on my microsoft windows:
![1](https://user-images.githubusercontent.com/58574331/70464204-320b2400-1a9d-11ea-8833-4b7bc7e7045e.jpg)

In preferences (Alt+P) or in "${user}/.weasis/data/weasis-core-ui/persitence.properties" I can't change it from 2560x1440 to 3840 x 2160, and because of it I see a lot of pixels on the xrays.

![2](https://user-images.githubusercontent.com/58574331/70464380-8d3d1680-1a9d-11ea-80d6-6f1563a1cbd2.jpg)
![3](https://user-images.githubusercontent.com/58574331/70464389-8f9f7080-1a9d-11ea-9258-e1a8ffb3838e.jpg)

**Comment by nroduit** [comment]
The resolution value in weasis is coming from the system. So you can't change the resolution in Weasis.

Is 3840 x 2160 the native resolution of the monitor?

Try to update the graphic card driver (already seen this kind of bug).

Changing the text size to 100% should also change the text size in Weasis.

**Comment by luizinho44** [comment]
> The resolution value in weasis is coming from the system. So you can't change the resolution in Weasis.
> Ok.
> Is 3840 x 2160 the native resolution of the monitor?
> Yes.
> Try to update the graphic card driver (already seen this kind of bug).
> ...
> Changing the text size to 100% should also change the text size in Weasis.
Just doing this now it works, thank you.

![1](https://user-images.githubusercontent.com/58574331/70472224-861e0480-1aad-11ea-969c-039a2d7ea522.jpg)
