### ISSUE TITLE
Weasis 3.5.4 does not display images stored with JLSL compression in DCM4CHEE

### ISSUE THREAD

**Issue by amroweb** [nroduit/Weasis#111]
Weasis 3.5.4 does not display images stored with JLSL compression in DCM4CHEE.
But works fine with J2KR
Also works fine when changing wado service in dcm4chee UseTransferSyntaxOfFileAsDefault = false .As in this case transmission of images occurs in explicit VR little endian

We've used weasis 1.2.9 works fine with both compressions.JLSL , and J2KR .

We use it in front of a servlet that makes wado calls as in the text file below.

[call.txt](https://github.com/nroduit/Weasis/files/4067119/call.txt)

etc.......

we also found the same issue. with little endian syntax...not sure why...same thing old version works fine.

ِHere is some log entries that may help..
]
    at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at org.weasis.core.api.media.data.ImageElement.startImageLoading(ImageElement.java)
15.01.2020 14:15:18.818 *ERROR* [Thumbnail Loader-pool-6-thread-1] org.weasis.core.api.media.data.ImageElement: Cannot read pixel data!: 1.2.840.113543.6.6.4.0.63732468873147561473412839321391962035478 java.util.concurrent.ExecutionException: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.1) C:\jenkins\workspace\opencv\modules\core\src\lut.cpp:368: error: (-215:Assertion failed) (lutcn == cn || lutcn == 1) && _lut.total() == 256 && _lut.isContinuous() && (depth == CV_8U || depth == CV_8S) in function 'cv::LUT'
]
    at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at org.weasis.core.api.media.data.ImageElement.startImageLoading(ImageElement.java)
15.01.2020 14:15:36.369 *ERROR* [AWT-EventQueue-0] org.weasis.core.api.media.data.ImageElement: Cannot read pixel data!: 1.2.840.113543.6.6.4.0.61736696755371148555412829143773397355656 java.util.concurrent.ExecutionException: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.1) C:\jenkins\workspace\opencv\modules\core\src\lut.cpp:368: error: (-215:Assertion failed) (lutcn == cn || lutcn == 1) && _lut.total() == 256 && _lut.isContinuous() && (depth == CV_8U || depth == CV_8S) in function 'cv::LUT'
]
    at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
    at org.weasis.core.api.media.data.ImageElement.startImageLoading(ImageElement.java)
![ERROR](https://user-images.githubusercontent.com/59934935/72464457-4b417780-37a3-11ea-8c6e-709465208f53.jpg)
![error2](https://user-images.githubusercontent.com/59934935/72464458-4bda0e00-37a3-11ea-8200-bcf7e4bf95f6.png)

**Comment by nroduit** [comment]
Could you share or send me an image sample?

**Comment by amroweb** [comment]
Yes, I can send them to you. But can't share them publicly because of patient privacy issues. patient name on in the images, can't anonymize that .Please let me know what email to send them to. 
mine is amroweb@yahoo.com

Regards -Amro 

    On Wednesday, January 15, 2020, 3:00:28 PM EST, Nicolas Roduit <notifications@github.com> wrote:  
 
 
Could you share or send me an image sample?

**Comment by nroduit** [comment]
The logs above are not related to the jpeg-ls issue.

CharLS cannot read the compressed data because those images are images corrupted by the JAI jpeg-ls encoder (see https://dcm4che.atlassian.net/browse/DCMEE-1144).

These corrupted images need to be patched (in [dcm4chee](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/imageWriter.html) by using  the value JAI2ISO)

=> improve Weasis to trace the error: 
[ERROR:0] global opencv/modules/imgcodecs/src/grfmt_dcm_jpegls.cpp (90) readData Read JPEG_LS data error: Invalid JPEG-LS stream, the encoded bit stream contains a general structural problem

**Comment by nroduit** [comment]
It also possible to decompress these corrupted files with the dcm4che3 toolkit by overriding the reader properties (see this [post](https://groups.google.com/d/msg/dcm4che/vUdlnnzeObg/1OFmEUKeBgAJ))
```
1.2.840.10008.1.2.4.80:jpeg-ls-cv:org.dcm4che3.opencv.NativeImageReader:JAI2ISO:
1.2.840.10008.1.2.4.81:jpeg-ls-cv:org.dcm4che3.opencv.NativeImageReader:JAI2ISO:
```

**Comment by amroweb** [comment]
Thank you very much. That solves the first, but the second one Philips ultra sound, attached, I think had no compression, little endian. Same solutions ?

Regards -Amro 

    On Friday, January 17, 2020, 3:54:37 PM GMT+1, Nicolas Roduit <notifications@github.com> wrote:  
 
 
It also possible to decompress these corrupted files with the dcm4che3 toolkit by overriding the reader properties (see this post)
1.2.840.10008.1.2.4.80:jpeg-ls-cv:org.dcm4che3.opencv.NativeImageReader:JAI2ISO:
1.2.840.10008.1.2.4.81:jpeg-ls-cv:org.dcm4che3.opencv.NativeImageReader:JAI2ISO:

**Comment by nroduit** [comment]
It is another issue, see my [comment](https://groups.google.com/d/msg/dcm4che/_Q5Dcv4nKr8/QE77Rl0OEQAJ).
