### ISSUE TITLE
QR doesn't work: invalid argument exception (Weasis 3.6.0)

### ISSUE THREAD

**Issue by ppazos** [nroduit/Weasis#122]
**Describe the bug**
The QR is done correctly, then on "import" I get "invalid argument exception". This was working OK on a previous version I have on another machine.

```
04.05.2020 22:38:46.191 *INFO* [pool-7-thread-1] org.dcm4che3.net.Connection: Stop TCP Listener on localhost/127.0.0.1:11113
04.05.2020 22:38:46.191 *ERROR* [Dicom Q/R task-pool-6-thread-1] org.weasis.dicom.qr.RetrieveTask: Dicom retrieve error: Invalid argument (connect failed)
04.05.2020 22:38:46.384 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.LoadLocalDicom: End of loading DICOM locally
04.05.2020 22:39:09.023 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Connection: Initiate connection from 0.0.0.0/0.0.0.0:0 to 192.168.1.105:11112
04.05.2020 22:39:09.023 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Connection: Established connection Socket[addr=/192.168.1.105,port=11112,localport=46315]
04.05.2020 22:39:09.024 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) << A-ASSOCIATE-RQ
04.05.2020 22:39:09.037 *INFO* [pool-11-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) >> A-ASSOCIATE-AC
04.05.2020 22:39:09.038 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 1:C-FIND-RQ[pcid=1, prior=0
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
04.05.2020 22:39:09.063 *INFO* [pool-11-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 1:C-FIND-RSP[pcid=1, status=ff01H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
04.05.2020 22:39:09.066 *INFO* [pool-11-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 1:C-FIND-RSP[pcid=1, status=0H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
04.05.2020 22:39:09.066 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) << A-RELEASE-RQ
04.05.2020 22:39:09.073 *INFO* [pool-11-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) >> A-RELEASE-RP
04.05.2020 22:39:09.073 *INFO* [pool-11-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2): close Socket[addr=/192.168.1.105,port=11112,localport=46315]
04.05.2020 22:39:13.912 *INFO* [pool-14-thread-1] org.dcm4che3.net.Connection: Start TCP Listener on localhost/127.0.0.1:11113
04.05.2020 22:39:13.912 *INFO* [Dicom Q/R task-pool-13-thread-1] org.dcm4che3.net.Connection: Initiate connection from localhost/127.0.0.1:0 to 192.168.1.105:11112
04.05.2020 22:39:13.913 *ERROR* [Dicom Q/R task-pool-13-thread-1] org.weasis.dicom.op.CMove: movescu java.net.ConnectException: Invalid argument (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
04.05.2020 22:39:13.913 *ERROR* [Dicom Q/R task-pool-13-thread-1] org.weasis.dicom.qr.RetrieveTask: Dicom retrieve error: Invalid argument (connect failed)
04.05.2020 22:39:13.913 *INFO* [pool-14-thread-1] org.dcm4che3.net.Connection: Stop TCP Listener on localhost/127.0.0.1:11113
04.05.2020 22:39:14.033 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.LoadLocalDicom: End of loading DICOM locally
```

**To Reproduce**
1. Create a DICOM node (this is my DCM4CHEE PACS)
2. File > Import > DICOM
3. DICOM Query/Retrieve
4. Select the node created on 1. as the Archive, note "calling node" has the Default one
5. Click Search, I can see results from my PACS, only one study there (this is for testing)
6. Click "import and close"
7. Throws exception

**Expected behavior**
1. The study images should be available in WEASIS without throwing any exceptions

**Desktop (please complete the following information):**
 - OS: Linux Mint 18
 - Java Rutime: openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
 - Weasis Version 3.6.0

**Additional context**
My PACS is running on a VM that has a network interface available in my LAN, that is why the QR without the import works.

**Traces**
See above.

**Comment by ppazos** [comment]
I see something strange in the connection initiated from WEASIS: ** localhost/127.0.0.1:0** port = 0?

> 04.05.2020 23:08:49.551 *INFO* [Dicom Q/R task-pool-17-thread-1] org.dcm4che3.net.Connection: **Initiate connection from localhost/127.0.0.1:0** to 192.168.1.105:11112

**Comment by nroduit** [comment]
DICOM C-MOVE requires more configuration:
https://groups.google.com/d/msg/dcm4che/U77zWpiRXnk/tS5ez_ICAgAJ
https://groups.google.com/d/msg/dcm4che/hgJvEov3EE0/P1IEV6cuBgAJ

**Comment by ppazos** [comment]
Thanks, I'll try.

On another machine I have v3.0.3 and works OK with similar configuration:

> 05.05.2020 08:09:05.819 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Connection: Initiate connection from 0.0.0.0/0.0.0.0:0 to 192.168.1.105:11112
> 05.05.2020 08:09:05.827 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Connection: Established connection Socket[addr=/192.168.1.105,port=11112,localport=46917]
> 05.05.2020 08:09:05.854 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(1) << A-ASSOCIATE-RQ
> 05.05.2020 08:09:05.903 *INFO* [pool-6-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(1) >> A-ASSOCIATE-AC
> 05.05.2020 08:09:05.928 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(1) << 1:C-FIND-RQ[pcid=1, prior=0
>   cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:06.108 *INFO* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(1) >> 1:C-FIND-RSP[pcid=1, status=ff01H
>   cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:06.134 *INFO* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(1) >> 1:C-FIND-RSP[pcid=1, status=0H
>   cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:06.135 *INFO* [AWT-EventQueue-0] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(1) << A-RELEASE-RQ
> 05.05.2020 08:09:06.144 *INFO* [pool-6-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(1) >> A-RELEASE-RP
> 05.05.2020 08:09:06.144 *INFO* [pool-6-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(1): close Socket[addr=/192.168.1.105,port=11112,localport=46917]
> 05.05.2020 08:09:09.344 *INFO* [Dicom Q/R task-pool-8-thread-1] org.dcm4che3.net.Connection: Initiate connection from 0.0.0.0/0.0.0.0:0 to 192.168.1.105:11112
> 05.05.2020 08:09:09.347 *INFO* [Dicom Q/R task-pool-8-thread-1] org.dcm4che3.net.Connection: Established connection Socket[addr=/192.168.1.105,port=11112,localport=58362]
> 05.05.2020 08:09:09.348 *INFO* [Dicom Q/R task-pool-8-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) << A-ASSOCIATE-RQ
> 05.05.2020 08:09:09.453 *INFO* [pool-9-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) >> A-ASSOCIATE-AC
> 05.05.2020 08:09:09.455 *INFO* [Dicom Q/R task-pool-8-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 1:C-GET-RQ[pcid=1, prior=0
>   cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.537 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 2:C-STORE-RQ[pcid=33, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.2 - CT Image Storage
>   iuid=1.2.840.113619.2.30.1.1762295590.1623.978668950.109 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.631 *INFO* [pool-9-thread-1] org.dcm4che3.tool.getscu.GetSCU: WEASIS_QR->DCM4CHEE(2): M-RENAME /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/tmp/1.2.840.113619.2.30.1.1762295590.1623.978668950.109 to /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/1.2.840.113619.2.30.1.1762295590.1623.978668950.109
> 05.05.2020 08:09:09.633 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 2:C-STORE-RSP[pcid=33, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.2 - CT Image Storage
>   iuid=1.2.840.113619.2.30.1.1762295590.1623.978668950.109 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.643 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 3:C-STORE-RQ[pcid=33, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.2 - CT Image Storage
>   iuid=1.2.840.113619.2.30.1.1762295590.1623.978668949.889 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.689 *INFO* [pool-9-thread-1] org.dcm4che3.tool.getscu.GetSCU: WEASIS_QR->DCM4CHEE(2): M-RENAME /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/tmp/1.2.840.113619.2.30.1.1762295590.1623.978668949.889 to /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/1.2.840.113619.2.30.1.1762295590.1623.978668949.889
> 05.05.2020 08:09:09.690 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 3:C-STORE-RSP[pcid=33, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.2 - CT Image Storage
>   iuid=1.2.840.113619.2.30.1.1762295590.1623.978668949.889 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.706 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 4:C-STORE-RQ[pcid=33, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.2 - CT Image Storage
>   iuid=1.2.840.113619.2.30.1.1762295590.1623.978668949.888 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.737 *INFO* [pool-9-thread-1] org.dcm4che3.tool.getscu.GetSCU: WEASIS_QR->DCM4CHEE(2): M-RENAME /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/tmp/1.2.840.113619.2.30.1.1762295590.1623.978668949.888 to /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/1.2.840.113619.2.30.1.1762295590.1623.978668949.888
> 05.05.2020 08:09:09.737 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 4:C-STORE-RSP[pcid=33, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.2 - CT Image Storage
>   iuid=1.2.840.113619.2.30.1.1762295590.1623.978668949.888 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.744 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 5:C-STORE-RQ[pcid=147, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.423267 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.749 *INFO* [pool-9-thread-1] org.dcm4che3.tool.getscu.GetSCU: WEASIS_QR->DCM4CHEE(2): M-RENAME /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/tmp/1.3.51.0.7.11111.22222.33333.423267 to /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/1.3.51.0.7.11111.22222.33333.423267
> 05.05.2020 08:09:09.750 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 5:C-STORE-RSP[pcid=147, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.423267 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.771 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 6:C-STORE-RQ[pcid=147, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.996782 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.788 *INFO* [pool-9-thread-1] org.dcm4che3.tool.getscu.GetSCU: WEASIS_QR->DCM4CHEE(2): M-RENAME /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/tmp/1.3.51.0.7.11111.22222.33333.996782 to /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/1.3.51.0.7.11111.22222.33333.996782
> 05.05.2020 08:09:09.788 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 6:C-STORE-RSP[pcid=147, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.996782 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.890 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 7:C-STORE-RQ[pcid=147, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.297788 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.894 *INFO* [pool-9-thread-1] org.dcm4che3.tool.getscu.GetSCU: WEASIS_QR->DCM4CHEE(2): M-RENAME /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/tmp/1.3.51.0.7.11111.22222.33333.297788 to /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/1.3.51.0.7.11111.22222.33333.297788
> 05.05.2020 08:09:09.895 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 7:C-STORE-RSP[pcid=147, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.297788 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.899 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 8:C-STORE-RQ[pcid=147, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.418402 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.905 *INFO* [pool-9-thread-1] org.dcm4che3.tool.getscu.GetSCU: WEASIS_QR->DCM4CHEE(2): M-RENAME /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/tmp/1.3.51.0.7.11111.22222.33333.418402 to /tmp/weasis-pablo.2B70055B/tmp/qr/15886768938910/1.3.51.0.7.11111.22222.33333.418402
> 05.05.2020 08:09:09.905 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) << 8:C-STORE-RSP[pcid=147, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.88.11 - Basic Text SR Storage
>   iuid=1.3.51.0.7.11111.22222.33333.418402 - ?
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.998 *INFO* [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 1:C-GET-RSP[pcid=1, completed=7, failed=0, warning=0, status=0H
>   cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 05.05.2020 08:09:09.999 *INFO* [Dicom Q/R task-pool-8-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) << A-RELEASE-RQ
> 05.05.2020 08:09:10.000 *INFO* [pool-9-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2) >> A-RELEASE-RP
> 05.05.2020 08:09:10.001 *INFO* [pool-9-thread-1] org.dcm4che3.net.Association: WEASIS_QR->DCM4CHEE(2): close Socket[addr=/192.168.1.105,port=11112,localport=58362]
> 05.05.2020 08:09:10.130 *INFO* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.LoadLocalDicom: Adding patient: MISTER, CT
> 05.05.2020 08:09:10.177 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: HELICAL CHEST
> 05.05.2020 08:09:10.954 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: 
> 05.05.2020 08:09:11.073 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: 
> 05.05.2020 08:09:11.096 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: SCOUT
> 05.05.2020 08:09:11.113 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: 
> 05.05.2020 08:09:11.118 *INFO* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.DicomModel: Series splitting: SCOUT
> 05.05.2020 08:09:11.118 *INFO* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.DicomModel: Series splitting: SCOUT
> 05.05.2020 08:09:11.160 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: 
> 05.05.2020 08:09:11.187 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.LoadLocalDicom: End of loading DICOM locally
>

**Comment by ppazos** [comment]
@nroduit from the conversations it is not clear which extra configuration is needed.

Shouldn't the "Default" calling node work for C-MOVE?

**Comment by nroduit** [comment]
No, it is not the same configuration (C-GET vs C-MOVE):

05.05.2020 08:09:09.998 INFO [pool-9-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(2) >> 1:C-GET-RSP[pcid=1, completed=7, failed=0, warning=0, status=0H
cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET

and

04.05.2020 22:39:13.913 *ERROR* [Dicom Q/R task-pool-13-thread-1] org.weasis.dicom.op.CMove: movescu java.net.ConnectException: Invalid argument (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)


With C-MOVE, you need the same configuration on server and client side.
