### ISSUE TITLE
3D reconstruction & MPR 

### ISSUE THREAD

**Issue by xiaorui531** [nroduit/Weasis#124]
**Describe the bug**
After reconstruction, there are different pixel spacing value between original images and new images.
 The postcontrast sagittal T1-weighted images were loaded (176 slices,1mm thickness, 0.5*1 pixel spacing). After clicking MPR, the new axial T1-weighted images were generated (512 slices, 0.47 mm thickness, 0.5 * 1 pixel spacing).

**To Reproduce**
1. Go to 'MPR'
2. Click on 'DICOM information'
3. Scroll down to 'Image Plane'

**Expected behavior**
Reconstruction does not change the pixel spacing and thickness of the images.

**Desktop (please complete the following information):**
 - OS:   Windows 10
 - Java Rutime: -x86-64
 - Weasis Version  3.6.0 

 

![image](https://user-images.githubusercontent.com/38315211/81583833-80be4080-93e4-11ea-8e6f-eeef283d78ad.png)
![image](https://user-images.githubusercontent.com/38315211/81583869-8d429900-93e4-11ea-8d70-e1aeb91abda3.png)

**Comment by nroduit** [comment]
I don't see a problem with your description. The height and width of a pixel is generally equivalent but not with the distance between 2 slices.
The orthogonal MPR reconstructs images for each plane without interpolation/extrapolation.

**Comment by xiaorui531** [comment]
> I don't see a problem with your description. The height and width of a pixel is generally equivalent but not with the distance between 2 slices.
> The orthogonal MPR reconstructs images for each plane without interpolation/extrapolation.

Thank you for the reply.
