### ISSUE TITLE
Opening files with Polish diacritic signs doesn't work on Windows

### ISSUE THREAD

**Issue by marmistrz** [nroduit/Weasis#126]
**Describe the bug**

**To Reproduce**
The following is done on a Windows 7 machine.
1. Take a `.dcm` file containing a Polish diacritic sign, for instance `Rafał.dcm`
2. Double click the `.dcm` file in Windows explorer to open it in Weasis.

**Expected behavior**
The image loads (this is actually the behavior on Linux)

**Actual behavior**
No image loads. The same happens if I run Weasis through cmd as `Weasis.exe Rafał.dcm`. If the file is renamed not to contain the `ł` letter, the image loads as expected. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Java Rutime: 1.8.0_131
 - Weasis Version: 3.6.0

**Additional context**
If the image is manually imported through the "import" menu, the image is successfully loaded.

**Traces**
I don't know how to get logs on Windows. There are no logs printed when the app is run from cmd :confused:

**Comment by nroduit** [comment]
I managed to reproduce the issue. This happens when the path in go through the binary (built by jpackage).

I've submit a bug report in the openjdk project, the reference is not yet visible.

**Comment by marmistrz** [comment]
JRE 8 is pretty old, maybe using a newer version would do the trick? (I don't have access to the machine ATM so I can't test it right now)

**Comment by nroduit** [comment]
No Weasis native embeds the modular JDK 14 (the latest release).

**Comment by nroduit** [comment]
Fix in [JDK 15](https://bugs.openjdk.java.net/browse/JDK-8246042)
