### ISSUE TITLE
Can we draw the Graph manually when we are loading the image in viewer with x,y coordinates 

### ISSUE THREAD

**Issue by laxmiprasannaBorigi** [nroduit/Weasis#129]
I have a feature where we need to load the json which has the coordinates and using this coordinates i need to draw the graph on top of Image. Will it be possible here using weasis.

**Comment by nroduit** [comment]
Today, apart from the DICOM Presentation State (which is the only standard way with DICOM SR that can also contain graphics), it is possible [to export and import data in an XML file](https://github.com/nroduit/Weasis/blob/master/weasis-core/weasis-core-ui/src/main/java/org/weasis/core/ui/serialize/XmlSerializer.java) (proprietary).

Ideally, the standard method should be preferred.

**Comment by laxmiprasannaBorigi** [comment]
@nroduit : Is thers i any other instead of  XML file, like import the graph boundaries in JSON and using that JSON to place the same graphic in DICOM Image

**Comment by nroduit** [comment]
No, we are not going to integrate non-standard formats when there is a standard one.

All DICOM objects can be converted to xml or json and vice versa. So, it would be possible to read or write a DICOM Presetation State in JSON. 

It should be possible to modify Weasis for supporting JSON Presentation State.
