### ISSUE TITLE
Drawing Tool with Name Or Annotation Or Title 

### ISSUE THREAD

**Issue by kamlesh0606** [nroduit/Weasis#137]
Drawing Tool with input Title textbox for Name Or Mark Or Annotation. And need details Textarea for notes. Ref. photo given 

![image](https://user-images.githubusercontent.com/3240948/86405436-fc46ba80-bcce-11ea-97b5-559a9db9d0aa.png)

Use case , Dr put name And details save in dicom server. patient will come next time that time read previous note also compare it.

**Comment by nroduit** [comment]
I'm not sure I understand the request but to comment on something it is possible to use the annotation tool which allows to put text on several lines.

![image](https://user-images.githubusercontent.com/993975/86438180-5747d400-bd06-11ea-8c98-899513322fe7.png)

**Comment by kamlesh0606** [comment]
But When Save this data in dicom server at that time , make two object for it Like 1 for polygon and 2nd for text Box. So that time  text message is not clear to display Dr team in other place like Reporting tool , other place .. 

This type option given This [tool](https://viewer.ohif.org/viewer/1.3.51.0.7.633918642.633920010109.6339100821)  but this is very basic think like not good for dr .

Ref, Photo.
![image](https://user-images.githubusercontent.com/3240948/86440985-17461880-bd29-11ea-98f4-7ccae1c3dc6b.png)

**Comment by nroduit** [comment]
Weasis annotations and measurements can be saved as DICOM Presentation state. [Graphic Object](https://dicom.innolitics.com/ciods/grayscale-softcopy-presentation-state/graphic-annotation/00700001/00700009) and Text Object are two different elements.

Currently, OHIF viewer has its own implementation of graphics. So those graphics cannot be share with other viewers.
