### ISSUE TITLE
DICOM Query/Retrieve - search Patient Name in cyrillic not work as expected.

### ISSUE THREAD

**Issue by dvrass** [nroduit/Weasis#149]
Search for Patient which name is written on PACS server in russian does not work as expected.

Go to Import DICOM
Click on DICOM Query/Retrieve
Type in Search PatientName russian patient name and nothing found. If use a star symbol with russian character - result is like you inter only star symbol.
With English patient name it's work correctly.

 - OS: Linux
 - Java Rutime: OpenJDK Runtime Environment 16-ea+12-477
 - Weasis Version 3.6.2
![Screenshot_20200914_132459](https://user-images.githubusercontent.com/71260594/93075021-defa7900-f68d-11ea-9fd4-4895ab9879b3.png)
![Screenshot_20200914_131943](https://user-images.githubusercontent.com/71260594/93074755-7d3a0f00-f68d-11ea-8230-ee8c67a5fa99.png)
![Screenshot_20200914_132016](https://user-images.githubusercontent.com/71260594/93074771-81662c80-f68d-11ea-8c03-f1260fe567b9.png)
![Screenshot_20200914_132152](https://user-images.githubusercontent.com/71260594/93074777-84611d00-f68d-11ea-8daf-14c33c6c36e8.png)

**Comment by nroduit** [comment]
The interpretation of wildcards is done at the server side. Is it working with other Q/R tools? 
The one used in weasis is https://github.com/dcm4che/dcm4che/tree/master/dcm4che-tool/dcm4che-tool-findscu

**Comment by dvrass** [comment]
> The interpretation of wildcards is done at the server side. Is it working with other Q/R tools?
> The one used in weasis is https://github.com/dcm4che/dcm4che/tree/master/dcm4che-tool/dcm4che-tool-findscu
We can try dcmqr from dcm4che-2.x:

`./dcmqr -L drass_109@wst109.linux.rniito.ru:2001 pacs1@pacs.rniito.ru:11112 -cget -qStudyDate=20200914 -qPatientName='аникина*'  
Start Server listening on port 2001
10:22:42,199 INFO   - Start listening on wst109.linux.rniito.ru/127.0.1.1:2001
10:22:42,219 INFO   - Association(1) initiated Socket[addr=pacs.rniito.ru/10.101.100.21,port=11112,localport=56441]
10:22:42,219 INFO   - pacs1(1): A-ASSOCIATE-RQ pacs1 << drass_109
10:22:42,227 INFO   - pacs1(1): A-ASSOCIATE-AC drass_109 >> pacs1
10:22:42,231 INFO   - Connected to pacs1@pacs.rniito.ru:11112 in 0.031 s
10:22:42,266 INFO   - Send Query Request using 1.2.840.10008.5.1.4.1.2.2.1/Study Root Query/Retrieve Information Model - FIND:
(0008,0020) DA #8 [20200914] Study Date
(0008,0030) TM #0 [] Study Time
(0008,0050) SH #0 [] Accession Number
(0008,0052) CS #6 [STUDY] Query/Retrieve Level
(0010,0010) PN #16 [аникина*] Patient’s Name
(0020,000D) UI #0 [] Study Instance UID
(0020,0010) SH #0 [] Study ID
(0020,1206) IS #0 [] Number of Study Related Series
(0020,1208) IS #0 [] Number of Study Related Instances

10:22:42,271 INFO   - pacs1(1) << 1:C-FIND-RQ[pcid=1, prior=0
        cuid=1.2.840.10008.5.1.4.1.2.2.1/Study Root Query/Retrieve Information Model - FIND
        ts=1.2.840.10008.1.2/Implicit VR Little Endian]
10:22:42,284 INFO   - pacs1(1) >> 1:C-FIND-RSP[pcid=1, status=ff00H
        cuid=1.2.840.10008.5.1.4.1.2.2.1/Study Root Query/Retrieve Information Model - FIND
        ts=1.2.840.10008.1.2/Implicit VR Little Endian]
10:22:42,286 INFO   - pacs1(1) >> 1:C-FIND-RSP[pcid=1, status=0H
        cuid=1.2.840.10008.5.1.4.1.2.2.1/Study Root Query/Retrieve Information Model - FIND]
10:22:42,286 INFO   - Query Response #1:
(0008,0005) CS #10 [ISO_IR 192] Specific Character Set
(0008,0020) DA #8 [20200914] Study Date
(0008,0030) TM #6 [090014] Study Time
(0008,0050) SH #0 [] Accession Number
(0008,0052) CS #6 [STUDY] Query/Retrieve Level
(0008,0054) AE #6 [pacs1] Retrieve AE Title
(0008,0056) CS #6 [ONLINE] Instance Availability
(0010,0010) PN #58 [АНИКИНА О.В.53Г. 17 ОТД^^№9911-13,10030-31] Patient’s Name
(0020,000D) UI #58 [1.3.51.0.7.13289553294.1444.22081.48629.36017.10340.41140] Study Instance UID
(0020,0010) SH #16 [2009140858247970] Study ID
(0020,1206) IS #2 [2] Number of Study Related Series
(0020,1208) IS #2 [2] Number of Study Related Instances
(0088,0130) SH #0 [] Storage Media File-set ID
(0088,0140) UI #0 [] Storage Media File-set UID

10:22:42,286 INFO   - Received 1 matching entries in 0.059 s
10:22:42,288 INFO   - Send Retrieve Request using 1.2.840.10008.5.1.4.1.2.2.3/Study Root Query/Retrieve Information Model - GET:
(0008,0052) CS #6 [STUDY] Query/Retrieve Level
(0020,000D) UI #58 [1.3.51.0.7.13289553294.1444.22081.48629.36017.10340.41140] Study Instance UID

10:22:42,288 INFO   - pacs1(1) << 2:C-GET-RQ[pcid=7, prior=0
        cuid=1.2.840.10008.5.1.4.1.2.2.3/Study Root Query/Retrieve Information Model - GET
        ts=1.2.840.10008.1.2/Implicit VR Little Endian]
10:22:42,405 INFO   - pacs1(1) >> 2:C-GET-RSP[pcid=7, remaining=null, completed=0, failed=2, warning=0, status=a702H
        cuid=1.2.840.10008.5.1.4.1.2.2.3/Study Root Query/Retrieve Information Model - GET
        ts=1.2.840.10008.1.2/Implicit VR Little Endian]
10:22:42,406 INFO   - Retrieved 0 objects (warning: 0, failed: 2) in 0.119s
10:22:42,406 INFO   - pacs1(1) << A-RELEASE-RQ
10:22:42,406 INFO   - pacs1(1) >> A-RELEASE-RP
10:22:42,407 INFO   - Released connection to pacs1@pacs.rniito.ru:11112
10:22:42,407 INFO   - pacs1(1): close Socket[addr=pacs.rniito.ru/10.101.100.21,port=11112,localport=56441]
10:22:42,407 INFO   - Stop listening on wst109.linux.rniito.ru/127.0.1.1:2001`

It's work fine.

**Comment by nroduit** [comment]
It should be similar in Weasis. Could you [activate the logger](https://nroduit.github.io/en/faq/#how-to-enable-weasis-logging-) and post the C-FIND request to compare.

**Comment by dvrass** [comment]
Weasis debug log in attachment
[default.log](https://github.com/nroduit/Weasis/files/5223705/default.log)

**Comment by nroduit** [comment]
I tried to do a similar test and with dcm4che 2.0.26 I get no result and with dcm4che 5.22.5 I get the same result as with Weasis.

Could you try with dcm4che 5.22.5

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.

**Comment by Aztks** [comment]
Hi, similarly I get name "UNKNOWN" in search from the PACS server (Orthanc) whenever the name is in Cyrillic.
(The Cyrillic name is displayed correctly in Orthanc explorer.)
Could this be fixed somehow?

![image](https://github.com/nroduit/Weasis/assets/45974840/3d1c89ed-bd10-435b-a1c4-bbd06117e88c)
