### ISSUE TITLE
Exception while retrieving Ultrasound Image Storage Instance with C-GET - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Pela2silveira** [nroduit/Weasis#150]
**Describe the bug**
With store-tcs.properties enabled, it fails to retrieve some instances ([1.2.840.113845.11.1000000002090985487.20200909104432.1322235.zip](https://github.com/nroduit/Weasis/files/5232703/1.2.840.113845.11.1000000002090985487.20200909104432.1322235.zip)). If not enabled, images are retrieved using  JPEG Baseline Lossy JPEG 8-bit Image Compression. Particularly in this example, they aren´t properly rendered. Retrieving in JPEG I think is a default behavior.

Tested with weasis portable 3.0.3 (32bit) it retrieves ultra sound images, but no a secondary capture instance. It throw another exception: 16.09.2020 10:14:54.396 ERROR [Dicom Q/R task-pool-6-thread-1] org.weasis.dicom.op.CGet: Read sop classes java.lang.IllegalArgumentException: GrayscaleSoftcopyPresentationStateStorageSOPClass

**To Reproduce**
**Added** 0 .Rename C:\Program Files\Weasis\app\resources\store-tcs.properties.example to .."store-tcs.properties" 
1. Upload Study to a PACS 
2. Configure weasis to c-get to PACS
3. c-find and c-get
4. Only one image retrieved. Check for logs. 

**Expected behavior**
All Ultrasound Image Storage be retrieved.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Java Rutime: --
 - Weasis Version 3.6.2 msi 64
 - Dcm4chee-arc-light Version 5.22.4,330ef7b,2020-08-20

**Additional context**
Tested use other dicom clients (DCMTK) without problem.

**Screenshots**
Not relevant

**Traces**
WEASIS LOG
15.09.2020 14:32:39.978 *ERROR* [Dicom Q/R task-pool-5-thread-1] org.weasis.dicom.op.CGet: Read sop classes java.lang.IllegalArgumentException: PseudoColorSoftcopyPresentationStateStorageSOPClass
    at org.dcm4che3.data.UID.forName(UID.java:65)
    at org.dcm4che3.tool.common.CLIUtils.toUID(CLIUtils.java:164)
    at org.weasis.dicom.op.CGet.configureStorageSOPClass(CGet.java:179)

DCM4CHEE LOG:

org.dcm4che3.net.NoPresentationContextException: No Presentation Context for Abstract Syntax: 1.2.840.10008.5.1.4.1.1.6.1 - Ultrasound Image Storage negotiated

**Comment by nroduit** [comment]
I followed your procedure to reproduce:
- Upload the images on dcm4chee-arc-light 5.22.4
- Q/R with C-GET with Weasis 3.6.2

All the 20 images are retrieved and displayed correctly. So I cannot reproduce the issue.

**Comment by Pela2silveira** [comment]
Sorry I by pass a step:
To Reproduce
Steps to reproduce the behavior:
    rename C:\Program Files\Weasis\app\resources\store-tcs.properties.example to .."store-tcs.properties"
    Upload Study to a PACS
    Configure weasis to c-get to PACS
    c-find and c-get
    Only one image retrieved. Check for logs.

**Comment by nroduit** [comment]
The sample is not up to date, use the [latest one](https://github.com/nroduit/weasis-dicom-tools/blob/master/src/main/resources/org/dcm4che3/tool/getscu/store-tcs.properties) as base.

**Comment by Pela2silveira** [comment]
Solved
