### ISSUE TITLE
Studies opened when loading an XML manifest

### ISSUE THREAD

**Issue by jerry-cbn** [nroduit/Weasis#151]
Hello,

Perhaps it's normal .. But when I load an XML manifest containing several studies of a same patient, Weasis display series of all these studies.

The button used to select studies (on the left panel) is not set to the last study but on "All studies", so all series of all studies are displayed.

Perhaps I could use an XML tag in the manifest to inform Weasis that a particular study must be displayed ?

Sincerely,

Jeremy.

**Comment by nroduit** [comment]
As there are several concurrent process levels and the display of a series can change from one time to another (it is the first one downloaded). A change in the manifest model is required to control strictly the loading of series in a layout. 

See also this [post](https://groups.google.com/g/dcm4che/c/ZCx-cop4mcY/m/_5XQeIuoAQAJ).

**Comment by jerry-cbn** [comment]
Hello Nicolas.

Thanks for your answer. I saw the post you mentioned.
Not the same thing. I was talking about the study selection button (on the left panel).
For example, if I load a manifest containing 5 studies of a same patient, Weasis will load these 5 studies (because study selection button is set to "All studies"). Is there a way to inform Weasis that the first study only must be loaded (and more if user select another study or all study with the button) ?

Sincerely,

Jeremy.

**Comment by nroduit** [comment]
The selection of a specific exam in the combobox just filters the thumbnail view, it has no impact on image loading. The image loading process is something asynchronous and parallelized at several levels.

See the documentation of [DICOM Explorer](https://nroduit.github.io/en/tutorials/dicom-explorer/)

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
