### ISSUE TITLE
Add graphic object opacity of DICOM Presentation State

### ISSUE THREAD

**Issue by VitMosin** [nroduit/Weasis#153]
**Is your feature request related to a problem? Please describe.**
I have "SQ graphic object sequence (0070, 0009)" with items. Items are closed polylines
Tag "CS graphic object (0070, 0024)" with value "Y" works properly as expected. Polyline is filled.
But there is sequence "SQ fill style sequence (0070, 0233)" too.
And if I add single item with tag to this sequence, f.ex. Patter On Opacity (https://dicom.innolitics.com/ciods/grayscale-softcopy-presentation-state/graphic-annotation/00700001/00700009/00700233/00700284), there are no changes in weasis.

**Describe the solution you'd like**
I'd like to see closed graphic objects filled with opacity (transparency).

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/8428137/96714116-5bc5f480-13aa-11eb-8233-b3376528780e.png)
![image](https://user-images.githubusercontent.com/8428137/96714264-8e6fed00-13aa-11eb-9b08-83432e7f690c.png)

**Comment by nroduit** [comment]
It should be possible to add transparency without changing the graphic model.

**Comment by VitMosin** [comment]
> It should be possible to add transparency without changing the graphic model.

You mean this feature is already accessible?

**Comment by nroduit** [comment]
There are a few small changes to be made so that it is also possible to create graphics with a certain transparency by adding the alpha channel in the color of each graphic. 
color = new Color((fillOpacity << 24) | (color.getRGB() & 0x00ffffff), true);

And for DICOM PR by converting the alpha part into the appropriated tag.

**Comment by nroduit** [comment]
Handle PatternOnOpacity for line and fill style but as opacity of line and fill cannot display separately the fill style override the line style.
