### ISSUE TITLE
cine speed based on screen/image size

### ISSUE THREAD

**Issue by rxk145** [nroduit/Weasis#155]
When I try to increase the FPS (cine speed), the ultrasound clips run slower than the desired cine speed, and this depends on the image size (for example, if I decrease the zoom and make the images small, it gets faster (closer to desire speed). 

**Desktop (please complete the following information):**
 - OS: MAC OS 10.12. The 6
 - Java Rutime: [e.g. JRE-8_191-x86-64] ? 
 - Weasis Version 3.62

**Comment by nroduit** [comment]
It is related to your machine capabilities and the graphic card. Try to set the [zoom](https://nroduit.github.io/en/tutorials/zoom/) at actual pixel size (100%) for best result.
If you have installed the native version it should use jdk-15.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
