### ISSUE TITLE
3D DICOM viewer with adjustable angles

### ISSUE THREAD

**Issue by Sogolumbo** [nroduit/Weasis#156]
The views of the orthogonal MPR depend on the angle that the data was collected. That makes it hard to compare two data sets (e.g. from before and after a surgery) that are taken with different angles.

Add an option to change the angle of the crosshair.
I think it could be very resource intensive to do this in real time. If possible I think there should be a 3D view which allows realtime navigation (but also keep the 2D view for users with less powerful computers).
If it's not possible there should be the option to select an angle and then let the computer calculate new 2D foto stacks.

The proprietary software of my doctor has this feature and it's a game changer.

**Comment by nroduit** [comment]
The development of an oblique MPR has been started but unfortunately at the moment I have not time to finalize this feature.

**Comment by nroduit** [comment]
See https://github.com/nroduit/Weasis/issues/390
