### ISSUE TITLE
Server response: java.net.SocketException: Address Family not supported by protocol family: connect

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#157]
Hi, I'm running Weasis in a network with more than 10 client PCs, it runs ok on 9 of them, but on this machine I'm getting this error:

![image](https://user-images.githubusercontent.com/1405017/100619793-64d8a880-32fc-11eb-86b5-bf90adfd5a22.png)

On the server side, no error is logged, it looks like the client not even attempt to connect.

So far I tried disabiling the Firewall and the antivirus, also adding this to c:\program files\weasis\runtime\conf\net.properties:

```
java.net.preferIPv4Stack=true
java.net.preferIPv6Addresses=false
```

But the error persists. Can you help me with this?.

**Comment by nroduit** [comment]
Please provide contextual information: system, version, weasis version...

Try to add a new java-options in /app/Weasis.cfg:
java-options=-Djava.net.preferIPv4Stack=true

But this IPv4 issue seems to be only related to old Java 6 and 7.

**Comment by leonardorame** [comment]
Hi Nicolas, here's the context:

O.S. Windows 10 Pro 64bit
Weasis 3.6.2 64bit
Java (uninstalled from the PC, Weasis uses the bundled one).

**Comment by leonardorame** [comment]
Well, the issue was fixed by adding `java-options=-Djava.net.preferIPv4Stack=true` to `/app/Weasis.cfg`.

**Comment by nroduit** [comment]
Ok, so you should have a different network configuration on this PC.

**Comment by leonardorame** [comment]
For the record,this happened again on a brand new Windows 11 Home PC

**Comment by nroduit** [comment]
I have never heard of this error elsewhere. In principle, there is no reason to restrict to IPv4. The problem may be related to a DNS or Proxy server or to a particular network configuration.
