### ISSUE TITLE
Read ISO File directly.

### ISSUE THREAD

**Issue by lamyergeier** [nroduit/Weasis#160]
**Is your feature request related to a problem? Please describe.**
I create ISO backup of CD and DVD that contains DICOM data from my doctor. It will be useful if we could directly read from ISO file. 

**Describe the solution you'd like**
Currently, the ISO file can't be read directly. It will be nice if it supports this.

**Describe alternatives you've considered**
I mount the file first and then it works fine.

**Comment by nroduit** [comment]
I won't provide such a feature because it is possible to mount a drive from an iso image with different software or in command line. The Weasis can read directly the drive from the CD button.

**Comment by nroduit** [comment]
Handling ISO image is not the role of a DICOM viewer

**Comment by m3thm4th** [comment]
@nroduit I beg you to reconsider this.
- Many minimal Linux distros don't have GUI mounting options and it's a pain to mount with CLI, especially since sudo is needed and thus a password.
- The majority of desktops and laptops today have no optical drive, as it's not a widespread medium anymore

if Weasis could handle ISOs directly it would be a huge convenience improvement

**Comment by nroduit** [comment]
I tested this on Windows 10/11, macOS and several Ubuntu versions: double‑clicking an .iso mounts the image on all of those systems and Weasis can then read the mounted filesystem. If a particular OS doesn’t auto‑mount the ISO, Weasis can’t substitute for the OS — the image needs to be mounted or the files extracted first.

Alternative that works directly with Weasis: export the DICOM files into a DICOM ZIP (many PACS/viewers support exporting a ZIP of the study). Weasis can open DICOM ZIP archives directly (including password‑protected ZIPs) via [DICOM Import](https://weasis.org/en/tutorials/dicom-import/index.html#from-weasis-menu-or-toolbar).
