### ISSUE TITLE
Increase application font

### ISSUE THREAD

**Issue by hawodi** [nroduit/Weasis#168]
Hello,
The font size on Ubuntu 20.04 for the menu bar is pretty tiny and would like to change it. Any idea where I should look? I have looked at preferences but that seems for the image. Thanks

**Comment by nroduit** [comment]
You mean related to other applications.
I noticed that on my Ubuntu desktop the fractional scaling doesn't work, only the scaling with a factor 2 is working.

You can also force the scaling directly in Weasis by adding in Weasis.cfg:
java-options=-Dsun.java2d.uiScale=2.0

Fractional value is not supported (like 1.25). It could be a problem if you have a screen with an in-between definition (HiDPI).

On Windows, if you increase the display at 125% then Weasis is scaled automatically.

**Comment by hawodi** [comment]
Thanks
