### ISSUE TITLE
Estract Radiation Dose report to csv File

### ISSUE THREAD

**Issue by marcheschi** [nroduit/Weasis#170]
Hi
I'm trying to estract the content of an RDSR to a XSLSX or CSV file in order to be able to analyze it with other softwares.
I noticed that Weasis can extract very well such information in the dose report, and all information is numbered, is there a simple way I can use your library in order to create this a csv file as output?
Thank you
Kindest Regards
Paolo

**Comment by nroduit** [comment]
No, parsing DICOM SR is not part of [DICOM library](https://github.com/nroduit/weasis-dicom-tools). There is no separation of data management and presentation in this part and it contains elements directly linked to the viewer.

**Comment by marcheschi** [comment]
Thank you very much for your answer.
Best regards
Paolo
