### ISSUE TITLE
Create a series-level thumbnail/preview frame

### ISSUE THREAD

**Issue by kurmukovai** [nroduit/Weasis#172]
Hi, I wonder if it is possible to specify a picture to be displayed as a thumbnail for the whole series. As far as I understand right now Weasis chooses image (a single dicom frame) based on Image Patient Position. Is there any way to display the very first frame (or any other frame) as a thumbnail for the whole series displayed in the left part of the screen (see attached image)?

E.g. on the attached images, I want the very first frame to be used as a preview (on the left) and by default Weasis uses 37'th frame (in this particular case).
![Screenshot_20210208_114721](https://user-images.githubusercontent.com/14237010/107196238-6d87e200-6a03-11eb-9546-9d78fa90b546.png)

**Comment by nroduit** [comment]
By default the thumbnail match to the middle series position. You can rebuild a thumbnail but I just notice that it doesn't work anymore. The [issue](https://github.com/nroduit/Weasis/issues/174) has be fixed for the next release.

**Comment by nroduit** [comment]
We're not going to change this default behavior because often the first image can be completely black.

However, you can right-click to reconstruct the image according to the first in the series.
