### ISSUE TITLE
Can not build.

### ISSUE THREAD

**Issue by orionkubilay** [nroduit/Weasis#173]
Hi,
I can not build weasis version 3.7.0
My JRE version is 15.0.2, Maven 3.6.3

I can build some older weasis version. (for example Weasis/3.6.4-endodataRev46 ) but I ve got below error mesages when I ve tried build 3.7.0

Thanks in advanced.

[INFO] Results:
[INFO] 
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ weasis-core-api ---
[INFO] Building jar: D:\Project\Weasis\Weasis\weasis-core\weasis-core-api\target\weasis-core-api-3.7.0.jar
[INFO] 
[INFO] --- spotless-maven-plugin:2.6.1:check (default) @ weasis-core-api ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Weasis framework parent [weasis-parent] 3.7.0 ...... SUCCESS [  1.060 s]
[INFO] OpenCV plugins [weasis-opencv] 3.7.0 ............... SUCCESS [  0.185 s]
[INFO] OpenCV - Windows x86 [weasis-opencv-core-windows-x86] 4.5.0-dcm SUCCESS [  2.000 s]
[INFO] OpenCV - Windows x86-64 [weasis-opencv-core-windows-x86-64] 4.5.0-dcm SUCCESS [  0.627 s]
[INFO] OpenCV - Linux x86 [weasis-opencv-core-linux-x86] 4.5.0-dcm SUCCESS [  0.823 s]
[INFO] OpenCV - Linux amd64 [weasis-opencv-core-linux-x86-64] 4.5.0-dcm SUCCESS [  0.882 s]
[INFO] OpenCV - Mac amd64 [weasis-opencv-core-macosx-x86-64] 4.5.0-dcm SUCCESS [  0.644 s]
[INFO] Core parent [weasis-core-parent] 3.7.0 ............. SUCCESS [  0.022 s]
[INFO] Core - Core API [weasis-core-api] 3.7.0 ............ FAILURE [  4.963 s]
[INFO] Core - Core UI API (Swing) [weasis-core-ui] 3.7.0 .. SKIPPED
[INFO] Core plugins [weasis-core] 3.7.0 ................... SKIPPED
[INFO] ImageIO codecs [weasis-imageio-codec] 3.7.0 ........ SKIPPED
[INFO] Base parent [weasis-base-parent] 3.7.0 ............. SKIPPED
[INFO] Base - Multi-release parent [weasis-base-ui-mr] 3.7.0 SKIPPED
[INFO] Base - Multi-release java 8 UI [weasis-base-ui-base] 3.7.0 SKIPPED
[INFO] Base - Multi-release java 9 UI [weasis-base-ui-nine] 3.7.0 SKIPPED
[INFO] Base - Multi-release UI distribution [weasis-base-ui] 3.7.0 SKIPPED
[INFO] Base - Media explorer [weasis-base-explorer] 3.7.0 . SKIPPED
[INFO] Base - Image viewer (non-DICOM) [weasis-base-viewer2d] 3.7.0 SKIPPED
[INFO] Base plugins [weasis-base] 3.7.0 ................... SKIPPED
[INFO] DICOM parent [weasis-dicom-parent] 3.7.0 ........... SKIPPED
[INFO] DICOM - Codecs and parsers for DICOM [weasis-dicom-codec] 3.7.0 SKIPPED
[INFO] DICOM - Data explorer [weasis-dicom-explorer] 3.7.0  SKIPPED
[INFO] DICOM - Viewer (2D and MPR) [weasis-dicom-viewer2d] 3.7.0 SKIPPED
[INFO] DICOM - Viewer of DICOM Structured Report [weasis-dicom-sr] 3.7.0 SKIPPED
[INFO] DICOM - Viewer for ECGs [weasis-dicom-wave] 3.7.0 .. SKIPPED
[INFO] DICOM - Audio Player [weasis-dicom-au] 3.7.0 ....... SKIPPED
[INFO] DICOM - Send (DICOM and DICOMWeb protocols) [weasis-dicom-send] 3.7.0 SKIPPED
[INFO] DICOM - Query/Retrieve [weasis-dicom-qr] 3.7.0 ..... SKIPPED
[INFO] DICOM - Viewer for RTs (radiotherapy) [weasis-dicom-rt] 3.7.0 SKIPPED
[INFO] DICOM plugins [weasis-dicom] 3.7.0 ................. SKIPPED
[INFO] Acquire - Media explorer [weasis-acquire-explorer] 3.7.0 SKIPPED
[INFO] Acquire - Media editor [weasis-acquire-editor] 3.7.0 SKIPPED
[INFO] Acquire plugins [weasis-acquire] 3.7.0 ............. SKIPPED
[INFO] Weasis Launcher (Felix) [weasis-launcher] 3.7.0 .... SKIPPED
[INFO] Weasis framework weasis-framework 3.7.0 ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.463 s
[INFO] Finished at: 2021-02-08T15:26:38+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.6.1:check (default) on project weasis-core-api: The following files had format violations:
[ERROR]     src\main\java\org\weasis\core\api\command\Option.java
[ERROR]         @@ -12,81 +12,81 @@
[ERROR]          import·java.util.List;
[ERROR]          
[ERROR]          public·interface·Option·{
[ERROR]         -····/**
[ERROR]         -·····*·stop·parsing·on·the·first·unknown·option.·This·allows·one·parser·to·get·its·own·options·and
[ERROR]         -·····*·then·pass·the·remaining·options·to·another·parser.
[ERROR]         -·····*
[ERROR]         -·····*·@param·stopOnBadOption
[ERROR]         -·····*/
[ERROR]         -····Option·setStopOnBadOption(boolean·stopOnBadOption);
[ERROR]         +··/**
[ERROR]         +···*·stop·parsing·on·the·first·unknown·option.·This·allows·one·parser·to·get·its·own·options·and
[ERROR]         +···*·then·pass·the·remaining·options·to·another·parser.
[ERROR]         +···*
[ERROR]         +···*·@param·stopOnBadOption
[ERROR]         +···*/
[ERROR]         +··Option·setStopOnBadOption(boolean·stopOnBadOption);
[ERROR]          
[ERROR]         -····/**
[ERROR]         -·····*·require·options·to·precede·args.·Default·is·false,·so·options·can·appear·between·or·after·args.
[ERROR]         -·····*
[ERROR]         -·····*·@param·optionsFirst
[ERROR]         -·····*/
[ERROR]         -····Option·setOptionsFirst(boolean·optionsFirst);
[ERROR]         +··/**
[ERROR]         +···*·require·options·to·precede·args.·Default·is·false,·so·options·can·appear·between·or·after·args.
[ERROR]         +···*
[ERROR]         +···*·@param·optionsFirst
[ERROR]         +···*/
[ERROR]         +··Option·setOptionsFirst(boolean·optionsFirst);
[ERROR]          
[ERROR]         -····/**
[ERROR]         -·····*·parse·arguments.·If·skipArgv0·is·true,·then·parsing·begins·at·arg1.·This·allows·for·commands
[ERROR]         -·····*·where·argv0·is·the·command·name·rather·than·a·real·argument.
[ERROR]         -·····*
[ERROR]         -·····*·@param·argv
[ERROR]         -·····*·@param·skipArg0
[ERROR]         -·····*·@return
[ERROR]         -·····*/
[ERROR]         -····Option·parse(List<?·extends·Object>·argv,·boolean·skipArg0);
[ERROR]         +··/**
[ERROR]         +···*·parse·arguments.·If·skipArgv0·is·true,·then·parsing·begins·at·arg1.·This·allows·for·commands
[ERROR]         +···*·where·argv0·is·the·command·name·rather·than·a·real·argument.
[ERROR]         +···*
[ERROR]         +···*·@param·argv
[ERROR]         +···*·@param·skipArg0
[ERROR]         +···*·@return
[ERROR]         +···*/
[ERROR]     ... (206 more lines that didn't fit)
[ERROR] Violations also present in 155 other files.
[ERROR] Run 'mvn spotless:apply' to fix these violations.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :weasis-core-api

**Comment by nroduit** [comment]
This is related to check the code format. There is an issue on Windows with end of line char (required to set git autocrlf).

I removed the [check](https://github.com/nroduit/Weasis/commit/5f9ecfdcffbfd291d9f47809c665f0f26ebb3d52).

**Comment by orionkubilay** [comment]
Hi,

OK. I ve builded now.
Thanks.
