### ISSUE TITLE
on-demand loading or direct-read from CD

### ISSUE THREAD

**Issue by Infotrafic** [nroduit/Weasis#179]
When a CD is inserted and the button import&close is pressed, it can take a long time before we can use the viewer

Would it be possible to load only the first picture of each folder and load all remaining pictures on folder selection.

Reading directly the data from the CD would be an interesting alternative.

**Comment by nroduit** [comment]
It can be slow to read CDs when the order of the DICOMDIR does not match the order in which the files are written to the disc.

Try the DICOM directory import method without using DICOMDIR.

**Comment by Infotrafic** [comment]
I can confirm that loading is going much faster without using DICOMDIR. 
The main reason is that it is not making any copy from the CD to the disk.
Unfortunately making a copy from the CD to the disk is needed to have a nice user experience using large series of pictures.

How can we configure (recompile if needed) the path where the "Import from CD" button copies the pictures? The idea would be to store all pictures into RAM-disk. (/dev/shm in linux).

Thanks in advance for your answer.

**Comment by nroduit** [comment]
The CD button action searches for a volume (could be a USB device) with DICOMDIR in root folder see [here](https://github.com/nroduit/Weasis/blob/024e86048a4add8ed4e986193b51f091df3d23da/weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/DicomDirImport.java#L269)

For loading data at start, see https://nroduit.github.io/en/getting-started/weasis-protocol/#examples-to-load-images
