### ISSUE TITLE
GSPS object is not rendered properly

### ISSUE THREAD

**Issue by yigitsoy** [nroduit/Weasis#181]
First of all, thank for providing this great tool for the usage of the community.

**Describe the bug**
I am trying to display a GSPS object that I created together with the original CT DICOM series.  The GSPS object contains a binary segmentation (a rough brain extraction for example purposes) which I added to the Overlay Plane as bitmap.

**To Reproduce**
1. Load the CT series CT2 from [77654033_19950903.tar.bz2](https://archive.org/download/7765403319950903/77654033_19950903.tar.bz2)
2. Load the corresponding set of GSPS objects in the attachment [77654033_gsps.zip](https://github.com/nroduit/Weasis/files/6102247/77654033_gsps.zip)
3. Select YUNA_GSPS from the "Presentation State" menu (in the view area on the right)
4. The overlay is not visible.

**Expected behavior**
The overlay bitmap is shown on top of the original image.

**Desktop (please complete the following information):**
```
***** Configuration *****
  Last running version = 3.7.0
  Current version = 3.7.0
  Application name = Weasis
  Application Source ID = 419B40DE
  Application Profile = default
  Application local codebase = /Applications/Weasis.app/Contents/app
  Application codebase URL = file:/Applications/Weasis.app/Contents/app
  Application configuration file = file:/Applications/Weasis.app/Contents/app/conf/config.properties
  Application extension configuration file = file:/Applications/Weasis.app/Contents/app/conf/ext-config.properties
  User = mehmet
  User home directory = /Users/mehmet/.weasis
  Resources path = /Applications/Weasis.app/Contents/app/resources
  Preferences directory = /Users/mehmet/.weasis/preferences/mehmet/default
  Look and Feel = com.apple.laf.AquaLookAndFeel
  Languages path = file:/Applications/Weasis.app/Contents/app/bundle-i18n/
  Languages available = en,ar,bs_BA,bg_BG,zh,zh_CN,zh_TW,hr_HR,cs,fr,de,el,hu_HU,it,ja,ko,ms_MY,pl_PL,pt,pt_BR,ro,ru_RU,sr_RS,sk_SK,es,sv,tr,uk,vi,vi_VN
  OSGI native specs = macosx-x86-64
  HTTP user agent = Weasis/3.7.0 (Mac OS X; 10.16; x86_64; default; NATIVE)
  Operating system = Mac OS X 10.16 x86_64
  Java vendor = Oracle Corporation
  Java version = 16

  Java Path = /Applications/Weasis.app/Contents/runtime/Contents/Home
  Java max memory (less survivor space) = 2.0 GiB
***** End of Configuration *****
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5089181/110336097-d2dfea80-8024-11eb-9c22-29d11a7c712c.png)

**Traces**
If applicable, add log files from Weasis, Java Runtime or PACS.

**Comment by nroduit** [comment]
I publish a fix for this regression.

However, I think we should add an option to display overlays in transparency of a color or transform to 2D graphics. There is the same problem to display DICOM SEG (which should be supported in the next version). The latter would be more appropriate in this case than DICOM PR.

**Comment by yigitsoy** [comment]
Thanks for the quick fix. I think it is possible to set a preferred color via [GraphicLayerRecommendedDisplayCIELabValue](https://dicom.innolitics.com/ciods/grayscale-softcopy-presentation-state/graphic-layer/00700060/00700401) which can be used as the color for the entire GraphicLayer. I am not sure about the transparency though.

Is there going to be a release soon or is there a nightly build that I can test?

**Comment by yigitsoy** [comment]
Btw, I noticed that the `GraphicLayerSequence` was not set correctly in the GSPS objects I shared earlier. I attached the latest versions [here](https://github.com/nroduit/Weasis/files/6106668/77654033_gsps.zip).

**Comment by nroduit** [comment]
I just run a build [here](https://github.com/nroduit/Weasis/actions/runs/635006107)

**Comment by yigitsoy** [comment]
Perfect. I can verify that overlay is displayed correctly now. Thanks for your quick support. 

I haven't tested with `GraphicLayerRecommendedDisplayCIELabValue` yet with but having the possibility to assign/change colors/transparency of overlay or an  entire `GraphicLayer` in the GUI would be perfect in the future.

**Comment by nroduit** [comment]
Close this issue and open a [feature request](https://github.com/nroduit/Weasis/issues/184).
