### ISSUE TITLE
overlay data isn't rendered depending on transfer syntax

### ISSUE THREAD

**Issue by codepage949** [nroduit/Weasis#183]
overlay data is rendered if transfer syntax is 'Explicit VR Little Endian' .

but 'JPEG 2000 Image Compression' not.

overlay data and attributes related with overlay were the same.

could you give me some advice?

thank you.

**Comment by nroduit** [comment]
I do not understand the question. Provide a sample and explain what  are you expected.

**Comment by codepage949** [comment]
i uploaded samples.

one is 'Explicit VR Little Endian' of transfer syntax and other one is 'JPEG 2000 Image Compression (Lossless Only)'

and i expected screenshot below for both, but overlay was visible only on 'Explicit VR Little Endian'.

![image](https://user-images.githubusercontent.com/26968918/111020626-afdd7e00-840a-11eb-831a-a33f072b6c90.png)

[samples.zip](https://github.com/nroduit/Weasis/files/6134231/samples.zip)

**Comment by nroduit** [comment]
According to my knowledge, this image is not valid because it encodes an overlay.

This is the first time I see fragments for overlays. According to the [standard for encapsulation](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_A.4.html):
```
Overlay Data (60xx,3000)
shall have the Value Representation OB or OW and shall be encoded in Little Endian.
```

**Comment by codepage949** [comment]
you mean overlay data should not be encapsulated in any case, right?

it seems that library that i use make overlay data encapsulated for jpeg transfer syntax.

**Comment by codepage949** [comment]
i should need to ask about it to the library community.

thank you.
