### ISSUE TITLE
GSPS is not rendered correctly in 3.7.0

### ISSUE THREAD

**Issue by Ch00k** [nroduit/Weasis#187]
**Describe the bug**
The GSPS is only partially rendered in Weasis 3.7.0.
The GSPS contains objects of different colors: white and blue. The white part shows fine, but the blue one does not. In Weasis 3.6.2 the entire GSPS is displayed correctly.

**To Reproduce**
1. Download [weasis_gsps.zip](https://github.com/nroduit/Weasis/files/6198979/weasis_gsps.zip), unpack and open the two DICOM files in Weasis.
2. Select `AIDENCE VEYE` in GSPS dropdown menu.

**Expected behavior**
Both the white and the blue parts of the GSPS are displayed correctly.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.1
 - Java Rutime: Java version = 16
 - Weasis Version 3.7.0, 3.7.1 (unreleased)

**Additional context**
This could be related to https://github.com/nroduit/Weasis/issues/181, however I also tried the 3.7.1 version that fixed the problem in https://github.com/nroduit/Weasis/issues/181, but it does not fix this problem.

**Screenshots**
Weasis 3.7.0
<img width="1112" alt="370" src="https://user-images.githubusercontent.com/230214/112347916-96b8b500-8cc7-11eb-9658-e7217199f1ba.png">

Weasis 3.6.2
<img width="1112" alt="362" src="https://user-images.githubusercontent.com/230214/112347923-99b3a580-8cc7-11eb-9a9e-b4eef7de0cb2.png">

**Comment by nroduit** [comment]
Yes, the new version supports [Pattern On Opacity Attribute](https://dicom.innolitics.com/ciods/grayscale-softcopy-presentation-state/graphic-annotation/00700001/00700009/00700232/00700284) and in your case the opacity value is 0.0 => transparent

**Comment by Ch00k** [comment]
@nroduit sorry, I'm not sure I understand what you mean exactly. You mean it's a feature, not a bug? Should I fix my GSPS instead to make the blue text non-transparent?

**Comment by nroduit** [comment]
Yes, I was wondering if it would be safer not to allow the value 0.0 but at the same time it is a valid value.

**Comment by Ch00k** [comment]
I changed the PatternOnOpacity to 1.0 which made Weasis render the GSPS correctly. I guess this issue can be closed now. Thanks a lot for looking at it!
