### ISSUE TITLE
Weasis - Sante DICOM Viewer Pro batch studies retrieve iisue

### ISSUE THREAD

**Issue by lk7777** [nroduit/Weasis#188]
I am testing Sante DICOM Viewer Pro as a mini-PACS and trying to retrieve studies from it into Weasis portable (Windows 3.7.0).
It works only when studies are retrieved one by one but not in a batch. ClearCancas is able to retrieve studies from Sante in a batch. Weasis retrieves studies in a batch from dcm4chee with no issues. What could cause this issue?

Sante's log:

Connected with peer 10.10.5.101
Receiving A-ASSOCIATE-RQ...
A-ASSOCIATE-RQ was received from AE Title "WEASISLAP"
        - Presentation Context 1: 1.2.840.10008.5.1.4.1.2.2.2
        - Proposed transfer syntax 1: 1.2.840.10008.1.2
        - Proposed transfer syntax 2: 1.2.840.10008.1.2.1
        - Proposed transfer syntax 3: 1.2.840.10008.1.2.2

Sending A-ASSOCIATE-AC...
        - Presentation Context 1: 1.2.840.10008.5.1.4.1.2.2.2
        - Accepted transfer syntax 1: 1.2.840.10008.1.2

    - A-ASSOCIATE-AC was sent

Waiting for service request...
    - C-MOVE-RQ was received from AE Title "WEASISLAP"
        - Message Contents:
          Group	 Elem	 VR	 Size	 Data
          0000	 0000	 UL	 4	 94
          0000	 0002	 UI	 28	 1.2.840.10008.5.1.4.1.2.2.2
          0000	 0100	 US	 2	 21H
          0000	 0110	 US	 2	 1H
          0000	 0600	 AE	 10	 WEASISLAP 
          0000	 0700	 US	 2	 0H
          0000	 0800	 US	 2	 0H

        - Message Contents:
          Group	 Elem	 VR	 Size	 Data
          0008	 0052	 CS	 6	 STUDY 
          0020	 000D	 UI	 134	 1.2.840.113680.4.103.83076.20171101181503\1.2.840.113619.2.226.2680968.1494405234.0.347\1.2.840.113619.2.225.4899840.1491877167.0.486

    - C-MOVE-RSP was sent
        - Message Contents:
          Group	 Elem	 VR	 Size	 Data
          0000	 0000	 UL	 4	 116
          0000	 0002	 UI	 28	 1.2.840.10008.5.1.4.1.2.2.2
          0000	 0100	 US	 2	 8021H
          0000	 0120	 US	 2	 1H
          0000	 0800	 US	 2	 101H
          0000	 0900	 US	 2	 0H
          0000	 1020	 US	 2	 0H
          0000	 1021	 US	 2	 0H
          0000	 1022	 US	 2	 0H
          0000	 1023	 US	 2	 0H

 A-RELEASE-RQ was received from AE Title "WEASISLAP"

Sending A-RELEASE-AC...
    - A-RELEASE-AC was sent

Connection is closed (Service Duration: 0 sec)

**Comment by nroduit** [comment]
Please address your question to Sante DICOM Viewer Pro
