### ISSUE TITLE
Remote configuration service

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#189]
Hi Nicolas, in [this document](https://nroduit.github.io/en/getting-started/weasis-protocol/) under the title "Modify the launch parameters" there's a mention about _wcfg is the URL the remote Weasis configuration service_. But I couldn't find more info about it, could you point me to the relevant documentation or how to set this up?.

I would like to load a remote `resources.zip` from the locally installed weasis, i.e. from the `weasis://` protocol handler.

**Comment by nroduit** [comment]
There are several ways:
1. if connected to weasis.war with the parameter cdb, you can change the resources in it
2. You can add the property weasis.resources.url
3. wcfg is a custom service (not open source) that returns a list of properties related to context passed in query parameters. Ex:
```xml
<weasisConfig>
  <javaOptions>
    <property name="weasis.codebase.url" value="http://weasis/weasis-dev"/>
    <property name="felix.config.properties" value="http://weasis/weasis-dev/conf/config.properties"/>
    <property name="weasis.codebase.ext.url" value="http://weasis-dev/weasis-ext"/>
    <property name="felix.extended.config.properties" value="http://weasis-dev/weasis-ext/conf/ext-config-3d.properties"/>
    <!--    -->
    <property name="weasis.pref.url" value="http://weasis-dev/weasisconfig/ws/preferences"/>
    <property name="weasis.i18n" value="http://weasis-dev/weasis-i18n"/>
    <property name="apple.laf.useScreenMenuBar" value="true"/>
    <property name="weasis.help.url" value="http://wiki/display/DEVPUB/Weasis"/>
    <property name="gosh.args" value="-sc telnetd -p 17179 start"/>
  </javaOptions>
</weasisConfig>
```

**Comment by leonardorame** [comment]
Thanks, I'm trying to figure out how to send the params of method no 2.

To open a study I use this (this works):

```
weasis://$dicom:get -w https://host/route/12133
```
Now, to set the `weasis.resources.url` I thougt I should add `$dicom:config pro=weasis.resources.url http://host/route`:

```
weasis://$dicom:get -w https://host/route/12133 $dicom:config pro=weasis.resources.url https://host/route
```

But in the Weasis log I get a `org.apache.felix.gogo.runtime.CommandNotFoundException: Command not found: dicom:config` exception.

How should I define that property?

**Comment by leonardorame** [comment]
I found I was using `$dicom:config` instead of `$weasis:config`. If I repace that I get:

```
org.apache.felix.gogo.runtime.CommandNotFoundException: Command not found: weasis:config
```

**Comment by nroduit** [comment]
The context URI must be encoded and the property must be quoted.

weasis://$dicom:get -w https://host/route/12133 $weasis:config pro="weasis.resources.url https://host/route"

weasis://%24dicom%3Aget%20-w%20https%3A%2F%2Fhost%2Froute%2F12133%20%24weasis%3Aconfig%20pro%3D%22weasis.resources.url%20https%3A%2F%2Fhost%2Froute%22

**Comment by leonardorame** [comment]
Finally it worked by launching from javascript this way:

`weasis://%24dicom%3Aget -w http://host/route/12133 $weasis:config pro=weasis.resources.url http://host/route/resources.zip`

The first `$dicom:get` must be encoded, and the property without quotes.
