### ISSUE TITLE
Uppercase DCM Files cannot be imported

### ISSUE THREAD

**Issue by tmyistanbul** [nroduit/Weasis#190]
**Uppercase DCM File extention cannot be imported**
There was an issue when we try to import a study.
When a study made with entire uppercase DCM files weasis could load them to viewer.

**To Reproduce**
1. Have a dcm file with lowercase anydicom.dcm file
2. Change extention to ANYDICOM.DCM
3. Try to import the file
4. Noting been imported
5. Change the file back to anydicom.dcm
6. Try to import
7. File appears in study list

**Desktop:**
 - OS: [Windows]
 - Java Rutime: [1.8.0_291-b10]
 - Weasis Version [3.7.0]

**Comment by nroduit** [comment]
The dcm extension helps to detect DICOM files but it seems your files don't have the magic number DICM.

To be a valid DICOM file it should contain "DICM" after 128 bytes, see https://www.iana.org/assignments/media-types/application/dicom

I can change to support also ".DCM" extension

**Comment by tmyistanbul** [comment]
@nroduit, Thank you for your reply. It will be helpful for us to support the .DCM extention. We are not able to intervene the pacs working internals. And tried other solutions like writing an intermediary program convert files to valid .dcm extensions. If you extend this feature we will be appreciate it.

**Comment by nroduit** [comment]
The extension is a secondary problem because often DICOM files do not have an extension. It is much more important that the files contain the DICOM signature.
