### ISSUE TITLE
Java binaries not found in PATH when building on macOS

### ISSUE THREAD

**Issue by jeremypatrickdahan** [nroduit/Weasis#191]
**Describe the bug**
When building Weasis via GitHub actions (build-installer.yml worflow), the macOS version fails to build with a 'jpackage : command not found' error.
When inspecting the $PATH variable, `/Users/runner/hostedtoolcache/jdk/16.0.0/x64/bin` is present instead of ` /Users/runner/hostedtoolcache/jdk/16.0.0/x64/Contents/Home/bin`.

**To Reproduce**
- Fork the current master branch of the repo
- Launch the build-installer action

**Solution**
I imagine it is a problem with the `actions/setup-java@v1` action, but in the meanwhile, adding the following after the `actions/setup-java@v1` call seems to solve the issue.

```
      - name: Fix bug with jpackage and JAVA_HOME
        shell: bash
        if: matrix.wsystem == 'macosx'
        run: 'echo "$JAVA_HOME/Contents/Home/bin" >> $GITHUB_PATH'
```

**Comment by nroduit** [comment]
I've never seen the issue that you describe, see the last build https://github.com/nroduit/Weasis/actions/runs/891026578

**Comment by jeremypatrickdahan** [comment]
Indeed, I missed a recent commit (9f485fd270eabaddbb603059c0d0f8a5f6c4ce87) which updates the build workflow with actions/setup-java@v2.
My bad
