### ISSUE TITLE
Trailing whitespace in AE title of DICOM node

### ISSUE THREAD

**Issue by amasmiller** [nroduit/Weasis#192]
**Describe the bug**
Trailing whitespace in AE Title of DICOM Node is transmitted to server.

**To Reproduce**

1. Go to 'File'
2. Click on 'Preferences'
3. Select 'Dicom node list'
4. Create a new DICOM Calling Node.   Input a valid description, AE title, and hostname.   Add an extra space character at the end of the AE title, like so:

![image](https://user-images.githubusercontent.com/32115401/120657960-a0d6fc80-c44a-11eb-9201-4302c19b0792.png)

5.  Configure a DICOM server to allow the client with the same information as in previous step except with no space at the end of the AE title.  Example from ClearCanvas server:
![image](https://user-images.githubusercontent.com/32115401/120658962-86515300-c44b-11eb-8d6a-7fa19d87da6e.png)

6. Attempt to Import a DICOM image from the server.   WEASIS will continue displaying "Retreiving..", while the server logs an error.  Example from ClearCanvas Server log:

![image](https://user-images.githubusercontent.com/32115401/120659050-98cb8c80-c44b-11eb-8354-ea3e333bdfe4.png)

**Expected behavior**

Expected trailing whitespace from AE title to be ignored, per DICOM standard http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html:

![image](https://user-images.githubusercontent.com/32115401/120659173-b8fb4b80-c44b-11eb-8091-0d797c0b8206.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Java Rutime: JRE 16.0.1+9-24
 - Weasis Version v3.7.0

**Additional context**
Add any other context about the problem here [e.g. network issue: give information about anti-virus or network security software, firewall, proxy...]. 

**Screenshots**

**Traces**
If applicable, add log files from Weasis, Java Runtime or PACS.

**Comment by nroduit** [comment]
The VR definition is for storing value types in a DICOM object. In this case, the AeTitle is not stored in a DICOM object. However, I have added a trim when creating a DICOM node.
