### ISSUE TITLE
Build error: Intellij+Maven3.8+Openjdk11

### ISSUE THREAD

**Issue by paytam** [nroduit/Weasis#193]
I wanted to compile weasis from source code but, I faced 2 problems

These are my system specifications

> IntelliJ IDEA 2021.1.2 (Community Edition)
> Build #IC-211.7442.40, built on June 1, 2021
> Runtime version: 11.0.11+9-b1341.57 amd64
> VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
> Linux 4.19.0-16-amd64(linux mint- LMDE 4 Debbie)
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1981M
> Cores: 8(Intel© Core™ i7-8550U CPU @ 1.80GHz × 4)
> Non-Bundled Plugins: com.4lex4.intellij.solarized (2.3.0), com.mroche.JsonHelper (1.1.2), com.robohorse.robopojogenerator (2.3.0), com.vecheslav.darculaDarkerTheme (1.2.0), detekt (1.17.1), google-java-format (1.9.0.1), mobi.hsz.idea.gitignore (4.1.0), String Manipulation (8.15.203.000.3), com.godwin.json.parser (1.4.2), mw.unitv (1.6.1), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), AwesomeKotlin (1.0.3), SequenceDiagram (2.1.a4), com.github.affishaikh.kotlinbuildergenerator (1.0.4.RC), com.longforus.kotlincodesorter (1.2.2), zielu.gittoolbox (203.5.10), PlantUML integration (5.4.0), PythonCore (211.7442.45), com.koxudaxi.poetry (1.1.4), com.leinardi.pycharm.pylint (0.12.2)
> Kotlin: 211-1.5.10-release-891-IJ7142.45
> Current Desktop: X-Cinnamon(version 4.8.6)
> 
> apache maven 3.8.1
> 

=============================================
I used to use apache maven 3.8 which uses HTTPS protocol, but when you want to compile the source via "mvn clean install" command, it did not compile. because some packages-like the one in dicom-codec- are still in HTTP. If I downgrade the maven to 3.6.3 the problem solved(mvn clean install)

some more steps in intelij setting: 
in 

> build,execution,Deployment > compiler > java compiler

 you should uncheck the 
>use '--release' option for cross-compilation(java 9 and later)

**Comment by nroduit** [comment]
Yes maven 3.8 requires https repository. This [issue](https://github.com/nroduit/Weasis/commit/54ba6702db4ed53b900f63f297dbf02ee01973e1) has been updated some weeks ago.

**Comment by paytam** [comment]
if it's possible update the documentation in proper sections
