### ISSUE TITLE
Rotating ellipse feature

### ISSUE THREAD

**Issue by CALOPUS** [nroduit/Weasis#194]
Am I missing the option to rotate an ellipse to take measurements of a head circumference? In Obstetrics we need to take measurements of the head and abdominal circumference but the shape isn't always spherical or a true horizontal oval so we need an ellipse that can be on an angle rather than only stretched in the horizontal and vertical planes

How quickly could this be updated in the current version as I need a tool that does this as soon as possible....

The image attached shows where I'd like to be able to move the calipers to

![Ellipse calliper issues](https://user-images.githubusercontent.com/85951410/122079655-865f3480-cdf5-11eb-93ce-38c17207bab0.png)

**Comment by nroduit** [comment]
This functionality has been initiated but not completed. For the moment the only way to get measurements is to use lines.

**Comment by CALOPUS** [comment]
That’s great. How long do you think til it goes live?
Is there also a feature to play dicom videos rather than just scroll through frame by frame?

**Comment by nroduit** [comment]
Unfortunately, I don't have time to work on this project at the moment. So I can't estimate when this feature will be achieved.

Cine can be activated in toolbar (View > Toolbars)  or from the Image tool panel.
![Sélection_081](https://user-images.githubusercontent.com/993975/122263217-78cdab80-ced6-11eb-9cc5-febd71179400.png)

**Comment by CALOPUS** [comment]
Thanks! That’s great to know and good luck with the update whenever you have time!
