### ISSUE TITLE
Study labels

### ISSUE THREAD

**Issue by CALOPUS** [nroduit/Weasis#195]
I may be missing something here but when I load up dicom studies for one patient, they are simply numbered 1-8 rather than the individual file name that they have been given within windows explorer. I need to be able to identify which video corresponds to which file name - is it already a function that file name info is read and included or can be populated into the study, series and date info when you hover over a thumbnail? At the moment all this info is blank for my videos

**Comment by nroduit** [comment]
I'm not sure I understand the problem. Please provide more details or post an example. 

There is no direct relationship between the structure in the [DICOM Explorer](https://nroduit.github.io/en/tutorials/dicom-explorer/) part and the files. A file has no particular meaning and moreover DICOM ojbects can also arrive via the network.

**Comment by CALOPUS** [comment]
Thanks for asking for clarification:
I have all files linked to one patient grouped in to patient specific folders with a numerical ID.
***@***.***D76A94.E544E2C0]
If I open these files in weasis none of this information is provided – the patient is “unknown” and the studies are given numbers #1-3 rather than the step names that the files have been given but I would like to see these file names within Weasis
***@***.***D76A94.E544E2C0]

**Comment by nroduit** [comment]
No screenshot is visible, please drag and drop files in GitHub textbox.

**Comment by CALOPUS** [comment]
Thanks for asking for clarification:
I have all files linked to one patient grouped in to patient specific folders with a numerical ID.

![weasis 1](https://user-images.githubusercontent.com/85951410/123600129-46814f80-d7ee-11eb-8a47-af9956aa703e.jpg)
![weasis 2](https://user-images.githubusercontent.com/85951410/123600132-46814f80-d7ee-11eb-89ef-b2ff47465ec3.jpg)
If I open these files in weasis none of this information is provided – the patient is “unknown” and the studies are given numbers #1-3 rather than the step names that the files have been given but I would like to see these file names within Weasis

**Comment by nroduit** [comment]
I don't really understand why you asking that because filename has no meaning in DICOM. The attributes are in the file and [can be displayed in Weasis.](https://nroduit.github.io/en/tutorials/tags/).

The [DICOM Explorer panel](https://nroduit.github.io/en/tutorials/tags/) shows a structure that is related to those attributes.

**Comment by CALOPUS** [comment]
Ahhhh you may think the filename has no meaning but it is key to identifying which step of a scan is being looked at for my groups research within Weasis. The DICOM attributes within the file don’t contain this key information hence why I have renamed the files so that they are better identifiable. One of the attractions to using Weasis over other DICOM viewing software is the ability to open all files belonging to one patient at once but if the identifiers of each of those files are lost (because they’re not displayed anywhere) when imported into Weasis this advantage is lost and we will have to open files one at a time to avoid confusion or use a different DICOM viewer that retains the name of the file I have assigned to it.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
