### ISSUE TITLE
weasis bulid errow

### ISSUE THREAD

**Issue by muratdogan1** [nroduit/Weasis#199]
hi 

how can i fix the problem
![Adsız](https://user-images.githubusercontent.com/7044364/123813228-6489a580-d8fd-11eb-8a21-cc21bc43a239.png)

mvn clean install

[ERROR] Failed to execute goal on project weasis-dicom-tools: Could not resolve dependencies for project org.weasis:weasis-dicom-tools:jar:5.23.3: Failed to collect dependencies at org.dcm4che:dcm4che-core:jar:5.23.3: Failed to read artifact descriptor for org.dcm4che:dcm4che-core:jar:5.23.3: Could not transfer artifact

**Comment by nroduit** [comment]
I guess it should be related to this [event](https://groups.google.com/g/dcm4che/c/S9l7CjSaOoc). Now the maven repository seems to be up again.

**Comment by muratdogan1** [comment]
thank you for the information 
eclips ide how can i fix the following error



SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Murat%20Karatekin/.p2/pool/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.18.0.20210618-2246/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/C:/Users/Murat%20Karatekin/eclipse/jee-2021-03/eclipse/configuration/org.eclipse.osgi/6/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Murat%20Karatekin/.p2/pool/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.18.0.20210618-2246/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/C:/Users/Murat%20Karatekin/eclipse/jee-2021-03/eclipse/configuration/org.eclipse.osgi/6/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]

**Comment by nroduit** [comment]
You can refer to this [page](https://nroduit.github.io/en/getting-started/guidelines/) for the use of IDE.
