### ISSUE TITLE
Keyboard up and down for series scrolling functions

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#204]
Dear Weasis Team,

Thanks for wonderful dicom viewer with consistent updates. Recently I Recommended few radiologist to use this viewer, but The keyboard **Up and Down arrow functions for scrolling the series is not found** and they switched to radiant viewer.
I request you to enable the feature in the viewer,
if already this feature is exist kindly advise how to enable it.

**Comment by nroduit** [comment]
Key up and down are used by different contexts (like pan, drawing...). So it requires to click on the right mini-bar to use those keyboard keys. You can also use the scrool bar directly

However, the scroll in the series is rather used with the mouse wheel. Using the scroll with a mouse button also allows to use the acceleration functions (ctrl and shift => see [shortcuts](https://nroduit.github.io/en/basics/shortcuts/)).

![Weasis v3 7 1_088](https://user-images.githubusercontent.com/993975/129841027-d20ce216-862c-4171-b4a1-3c1cf88e0ca6.png)

**Comment by arunjoshtech** [comment]
Dear Nroduit,
Really thanks for such clear reply on my doubts.
But regret for my lack knowledge engaged your precious time to reply my query.  Thanks for for your commited and keep releasing new versions..
