### ISSUE TITLE
Is it possible to reorder the images in certain series?

### ISSUE THREAD

**Issue by scjohnconnor** [nroduit/Weasis#207]
In some scannings, the order of images in certain series are the opposite to others, is it possible to add a function that enables the users to reorder the images?

For example, T2WI images are listed from up to down, but T1WI images are from down to up, and I hope to change the order of T1WI images so it can synchronize wit T2WI.

Thanks a lot.

**Comment by nroduit** [comment]
The images of a series are sorted by default by intstance number (generated by the modality). Then it is possible to change this sorting for different needs.
![Sélection_122](https://user-images.githubusercontent.com/993975/130072653-bc5f9b01-d252-4efa-b878-df3c333037de.png)

The synchronization is based on the position vectors and therefore the sorting, whatever it is, has no effect on this.

**Comment by scjohnconnor** [comment]
> The images of a series are sorted by default by intstance number (generated by the modality). Then it is possible to change this sorting for different needs.
> ![Sélection_122](https://user-images.githubusercontent.com/993975/130072653-bc5f9b01-d252-4efa-b878-df3c333037de.png)
> 
> The synchronization is based on the position vectors and therefore the sorting, whatever it is, has no effect on this.

Thank you so much, I've found this function.
