### ISSUE TITLE
Plug-in fails to start if it uses a third party dependency

### ISSUE THREAD

**Issue by DanielBEskandar** [nroduit/Weasis#208]
I am trying to build a Weasis plug-in from the weasis-plugin-dicom-viewer-archetype. The problem is that the plugin fails to start when I include and use a third party dependency in the pom.xml file. The plug-in is not even seen by the viewer and no errors or warnings appear in the log file. The viewer runs as if there is no plug-in.

I am trying to include the json dependency in the pom.xml file of the new plug-in:

<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20210307</version>
</dependency>

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
