### ISSUE TITLE
How to disable Dicom Image Overlay on startup?

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#211]
I would like to disable Dicom Image Overlay option on startup (i.e.: in a resources.zip file). Of course, later the user can enable it if he wants.

Here's the option I want to disable:

![imagen](https://user-images.githubusercontent.com/1405017/135452460-e4e5000f-210d-4a9a-b04d-70c32a0657c9.png)

Is this possible?

**Comment by nroduit** [comment]
It's voluntary that the Image part has no persistence while the Dicom Annotations part keeps the changes even after closing Weasis.

The Overlays of the image are sometimes very important like the designation of the laterality. Allowing to change this behavior by default might confuse most users who won't find or think to change this option. For this reason, I am not in favor of this change.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
