### ISSUE TITLE
Apple silicon support - M1 (arm) processor for weasis-opencv on macOS

### ISSUE THREAD

**Issue by christianheilmann** [nroduit/Weasis#212]
We need to have an Apple silicon support - M1 (arm) processor for weasis-opencv.

As this part of the library is not public, I'm not able to compile it and contribute it with an Pull Request.

Please decide how to add this support:
1) Can you compile and add the Apple Silicon version of the the library to the repository?
or 
2) Can you give us temporary access if you don't own yourself an Apple Silicon Mac, that we can compile and provide you the library, for adding to the repository?

Apple will on long therm only sell Macs with Apple Silicon (M1) processor, so we need to support this architecture for macOS.

Maybe it is better also to change over to .dylib as this is the file format suggested by Java Community (2012):
https://bugs.openjdk.java.net/browse/JDK-8127215

**Comment by nroduit** [comment]
Indeed the sources of this library are not yet publicly distributed. Currently, I can only assume automated tasks through Github or by cross-compiling through Docker images.

Unfortunately, there is no way to automate the build without having Mac OS + hardware. I'm waiting for a solution from [Github](https://github.com/actions/virtual-environments/issues/2187).

Could you send me an email (available from my github account) and briefly describe the scope of use of this library.

**Comment by nroduit** [comment]
Will available in Weasis 4 and has proposed in dcm4che https://github.com/dcm4che/dcm4che/pull/1125

**Comment by woj-tek** [comment]
Hmm... is this available? Looking at https://weasis.org/en/getting-started/index.html it lists "macOS | x86 64-bit | PKG" and indeed when run activity monitor shows "Intel" as class, suggesting Rosetta emulation instead of native ARM build.
