### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by manikandan-ux** [nroduit/Weasis#213]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project weasis-dicom-codec: Could not resolve dependencies for project org.weasis.dicom:weasis-dicom-codec:jar:3.7.2-mybuild: Failed to collect dependencies at org.weasis:weasis-dicom-tools:jar:5.24.0 -> org.dcm4che:dcm4che-core:jar:5.24.0: Failed to read artifact descriptor for org.dcm4che:dcm4che-core:jar:5.24.0: Could not transfer artifact org.dcm4che:dcm4che-core:pom:5.24.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [dcm4che (http://maven.dcm4che.org, default, releases)] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project weasis-dicom-codec: Could not resolve dependencies for project org.weasis.dicom:weasis-dicom-codec:jar:3.7.2-mybuild: Failed to collect dependencies at org.weasis:weasis-dicom-tools:jar:5.24.0 -> org.dcm4che:dcm4che-core:jar:5.24.0

**Comment by nroduit** [comment]
https://www.dcm4che.org/maven2 was down yesterday.

**Comment by manikandancool7** [comment]
Thank you for the reply 

Can you tell me how to build the windows installer in linux machine
