### ISSUE TITLE
Is it possible to adjust slice thickness in MPR

### ISSUE THREAD

**Issue by Sloganso** [nroduit/Weasis#215]
Great Dicom viewer with versatile function and user friendly interface.

Is it possible to adjust the slice thickness in MPR view?

Have a good day!

**Comment by nroduit** [comment]
No, it is not real 3D. The missing orientations are generated only with the information of the original pixels.

**Comment by nroduit** [comment]
Duplicate of https://github.com/nroduit/Weasis/issues/390
