### ISSUE TITLE
OpenCV library: license and copyright details

### ISSUE THREAD

**Issue by uszeiss** [nroduit/Weasis#218]
I was not able to find the origin of the OpenCV libraries used in Weasis. In particular, where do [these DLLs](https://github.com/nroduit/mvn-repo/tree/master/org/weasis/thirdparty/org/opencv/opencv_java/4.5.3-dcm) come from?

I'd like to know how the libraries are licensed and what copyrights they come with. As far as I know, this depends on how they are built, e.g. what flags are used during compilation (to enable specific parts, for instance).

Could you be so kind as to provide some background information on this? This would help me understand which licenses and copyright I need to deal with when I use Weasis.

Keep up the great work.
Thanks!

**Comment by nroduit** [comment]
The sources of this library are not yet publicly distributed. The situation of the native library is:

- OpenCV (only core, imageproc, imagecodecs) => BSD
- OpenJPEG => BSD
- CharLS => BSD
- New API for DICOM in imagecodecs, fully developed by me => BSD

**Comment by uszeiss** [comment]
Thanks for your feedback.

If I understand correctly, the DLLs linked in my original post are customised versions of OpenCV, including an extension developed by you. And I assume by "BSD", you mean "BSD 3-clause" in the case of OpenCV and CharLS, but "BSD 2-clause" in the case of OpenJPEG.

Which BSD license applies to the new API for DICOM in imagecodecs?
And what is the name by which the library should be referenced in a Bill of Materials document of a project that uses the library? (OpenCV Weasis?, OpenCV Java? OpenCV Java Weasis?)

**Comment by nroduit** [comment]
The same as OpenCV => BSD 3-clause

The Java wrapper of the native library is the project [weasis-core-img](https://github.com/nroduit/weasis-core-img). We can name the project weasis-core-img (Java + native part).

**Comment by uszeiss** [comment]
Thanks for the clarification.

When can we expect the missing sources to be published? This would allows us to

1. list the copyright details of all sub-components
2. document the exact versions of OpenCV, OpenJPEG, and CharLS
3. scan for potential vulnerabilities

**Comment by nroduit** [comment]
Unfortunately, I can not set a deadline because currently my availability to work on open source projects is very limited.

**Comment by uszeiss** [comment]
I understand. Would you accept contributions that could help resolve this issue? Would you be available for guidance and reviews?

I'm asking because the missing parts block us from adopting Weasis. We are not able to fulfill our FOSS obligations if we cannot provide copyright statements and vulnerability reports for the full code that comes with Weasis.

**Comment by nroduit** [comment]
Please contact me directly by email (visible on my Github account) to arrange an appointment.

**Comment by nroduit** [comment]
More information at https://github.com/nroduit/Weasis/blob/master/3rd-party-licenses.md
