### ISSUE TITLE
Clear Canvas PACS WADO URL and C-GET Connections 

### ISSUE THREAD

**Issue by happymonk193** [nroduit/Weasis#220]
hi , i am looking for help , Clear Canvas PACS Ver13.0.... Successfully Install at Windows Server 2012 R2 with MS SQL server , the Server is receiving DICOM Images from Modality CT Scan MRI DR  working well with Clear Canvas Workstation Clint Desktop PC with Streaming.

i want to Connect Radiant , Weasis ,  with CC PACS Server.

The Server Log file is attach for reference.  
[ClearCanvas_ImageServer_2021-11-28.log](https://github.com/nroduit/Weasis/files/7614213/ClearCanvas_ImageServer_2021-11-28.log)

**Comment by nroduit** [comment]
From the information provided, I don't see anything that suggests a problem on the Weasis side. 
It would be better to post this issue for clearcanvas.

**Comment by happymonk193** [comment]
please see the attache Image Weasis 
![Error with C GET ](https://user-images.githubusercontent.com/94319794/143861762-442eacae-b611-4d41-b14a-551b70d751c1.png)
![WADO URL no images ](https://user-images.githubusercontent.com/94319794/143861779-1568af80-8e62-4276-ab8a-5f9344b57ec4.png)
please guide Enable Weasis Debug mode and explorer log file.

**Comment by nroduit** [comment]
Please describe one problem per issue and do not duplicate the request.
