### ISSUE TITLE
Weasis Image Rendraing Issues with Q./R PACS SEREVER UID Not Present

### ISSUE THREAD

**Issue by happymonk193** [nroduit/Weasis#221]
**Describe the bug** Weasis Ver3.7
  issues with Q/R Weasis communication with PACS Server 
C-GET fail: NO Presentation Context for Abstract Syntax: 1.2.840.1000.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model-GET Negotiated.

the file in weasis (C:\Program Files\Weasis\app\resources(store-tcs.properties)) the above UID not present.

[sop-classes.properties.txt](https://github.com/nroduit/Weasis/files/7614442/sop-classes.properties.txt)

**Comment by nroduit** [comment]
1.2.840.1000.5.1.4.1.2.2.3 doesn't exist in DICOM, I guess it should be 1.2.840.10008.5.1.4.1.2.2.3

**Comment by happymonk193** [comment]
Dear i cross check the **1.2.840.1000.5.1.4.1.2.2.3**  for clear canvas DIcom Statment its present its Query Retrive DICOM Statment page No5 
Query/Retrieve 
Study Root Information Model FIND Yes – Hierarchical only Yes 
Study Root Information Model MOVE Yes – Hierarchical only Yes 
please check your DICOM master tool file , real-sop-classes.properties also check weasis sop-classes.properties 
the said UID is not present (**1.2.840.1000.5.1.4.1.2.2.3**)
![query](https://user-images.githubusercontent.com/94319794/143860382-76d0224c-2816-48dd-a4b4-5dfb85c0bc62.png)
![Error with C GET ](https://user-images.githubusercontent.com/94319794/143860403-4c84e841-21ad-4189-b905-4ee96a12a1bb.png)

**Comment by happymonk193** [comment]
Prove CC PACS working and said UID Support by CC Software as per DICOM Statement. i think its good time working on weasis 
![CC PACS and CC workstation worklist](https://user-images.githubusercontent.com/94319794/143863341-ec4d546a-6e5f-4bbe-a829-1e10cbe4ce94.png)
![CC PACS and CC workstation Images](https://user-images.githubusercontent.com/94319794/143863356-e1b1f1a7-e47b-4686-99e4-b0cbe6823ecc.png)

**Comment by nroduit** [comment]
Please, let me know where you find something related to 1.2.840.1000.5.1.4.1.2.2.3 ?

The viewer of CC does not use C-GET but It seems to be a proprietary type of communication.

**Comment by happymonk193** [comment]
Dear i am facing problem at Weasis while Q/R C-GET or C FIND please see the attached logs for details belongs to PACS , i just enable debug logs in weasis , unfortunately no logs. please guide for logs , trace , debug....
[Weasis C GET.txt](https://github.com/nroduit/Weasis/files/7620450/Weasis.C.GET.txt)
error pop up at weasis screen 
![Error at Weasis](https://user-images.githubusercontent.com/94319794/143925583-1a72598e-0b8f-4510-ab51-7a3b7686212b.png)
indicating 1.2.840.1000.5.1.4.1.2.2.3 this code. i just change my workstation for cross check the issues same .
