### ISSUE TITLE
MPR VIEW OF SAGITAL AND CORONAL SHOWS LESS /ZOOM IN

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#223]
**Describe the bug**
Dear Sir,
The default sagittal and coronal view of MPR is showing middle part of it and in order to see full images of Sagittal and coronal we have to zoom out using tool inside Image tool. As a user it is bit trouble to do. what is the best practice to work on MPR view?

I have attached default MPR generated view and Zoom adjust view for your Kind reference. Looking forward your guidance and instructions.
Thanks and Regards
![mpr view weasis_defaul;t](https://user-images.githubusercontent.com/63642104/144332861-08a5a271-4cff-44a0-b768-03586b3c7d38.PNG)
![mpr full images3](https://user-images.githubusercontent.com/63642104/144332849-ab8868b8-8217-47f9-b06f-ffc0211465fd.PNG)
![mpr adjusting tool_weasis](https://user-images.githubusercontent.com/63642104/144332857-42d5768b-3d15-4ff8-9094-6cf50b1688cd.PNG)

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Java Rutime: [e.g. JRE-8_191-x86-64]
 - Weasis Version [e.g. 3.1.0]

**Additional context**
Add any other context about the problem here [e.g. network issue: give information about anti-virus or network security software, firewall, proxy...]. 

**Screenshots**

**Traces**
If applicable, add log files from Weasis, Java Runtime or PACS.

**Comment by nroduit** [comment]
This is the default operation with a synchronized zoom between the 3 views which can have different sizes. The best-fit value is based on the view containing the original images.

As the zoom is synchronized by default, you can simply zoom out if necessary or otherwise move the image with the area of interest in the center (with pan).

I don't consider this request as a bug but as a default configuration choice. Please argue how it should work.

**Comment by arunjoshtech** [comment]
Dear Sir,
Thanks for the the reply, 
May be attached UI reference may be helpful for such scenario.
THE LEFT DEFAULT VIEW IS AXIAL IMAGES BUT USER CAN VIEW THE AXIAL IMAGES BEFORE MPR ITSELF AND HAVE LESS SIGNIFICAN TO SHOW IN BIGGER WINDOW.
The below attached screen shots are for kind reference to enhance the MPR view.
![radiant viewer for mpr](https://user-images.githubusercontent.com/63642104/144888611-985a4cd7-beef-4eb6-85f2-a622b65a63a4.PNG)

![radiant viewer mpr](https://user-images.githubusercontent.com/63642104/144888615-b166d52f-0bd7-4b15-bb9e-0cfa0afe95a2.PNG)

![OHIF FOR WEASIS REFERENCES](https://user-images.githubusercontent.com/63642104/144888599-4b543e68-da4f-437a-bbdc-65096680077f.PNG)

**Comment by nroduit** [comment]
If the question is whether it is possible to change the layout of the views, the answer is yes (see screenshot). Other layouts could be added.

![image](https://user-images.githubusercontent.com/993975/145355902-a971d92e-56d2-45d1-9503-e31f27f9085b.png)

**Comment by arunjoshtech** [comment]
Dear Sir,
you have added all great features and changing layout is helping to resolve my query but other layout will be still much help to see all view without hide on or top of the layout.
Humbly requesting you to add other Layout will be more than enough.
Thanks for your patience to reply and clear my queries and moving for the next level of out come.

**Comment by arunjoshtech** [comment]
2a
.

**Comment by nroduit** [comment]
Do you mean a layout as OHIF?

**Comment by arunjoshtech** [comment]
> Do you mean a layout as OHIF?

Yes, Please add additional layout as attached image of OHIF and Radiant .

**Comment by nroduit** [comment]
It has been done, see https://github.com/nroduit/Weasis/issues/229
