### ISSUE TITLE
Weasis ISOWriter on 3.7.1+

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#225]
Hi Nicolas, do you know if Weasis ISOWriter works on newer versions of Weasis?.

**Comment by nroduit** [comment]
Yes it is packaged in weasis-ext of each version, see https://sourceforge.net/projects/dcm4che/files/Weasis/3.8.0/

**Comment by nroduit** [comment]
[isowriter plugin](https://github.com/nroduit/Weasis/issues/289) has been integrated into Weasis 4.0.1.
