### ISSUE TITLE
Bad render of specific instances with encapsulated transfer syntax

### ISSUE THREAD

**Issue by jmcoelloidonia** [nroduit/Weasis#226]
**Describe the bug**
When I try to render the attached DICOM in Weasis, it renders as its shown in the screenshot (I've also attached the same image rendered by Radiant, for comparison).

It's happening whenever a specific PACS give us their images as JPEGLossless:Non-hierarchical-1stOrderPrediction, the machine where the image was originally created doesn't seem to be relevant. I don't have access to other instances with other encapsulated transfer syntaxes, it may or may not happen in those.

**To Reproduce**
1. Open the attached dicom image in Weasis

**Expected behavior**
It should render correctly, as shown in the attachment showing Radiant.

**Desktop (please complete the following information):**
 - OS: Linux, 64-bits
 - Java Runtime: OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
 - Weasis Version 3.6.0

**Additional context**
Having done some tests myself, I suspect that the encapsulated image width and height values are transpose from the information in tags Rows (0028,0010) and Columns (0028,0011) (i.e. in this particular image Columns is 880 and Rows is 660. I suspect that the encapsulated image is 660x880 instead of 880x660). I assume that the image expects the viewer to ignore the jpeg parameters and use the DICOM parameters instead. I don't know enough of the standard to know if this approach is correct, but I suppose that this is a grey area and the vendor is using it to ensure vendor lock-in.

If you are going to transform the image for testing, be aware that gdcmconv from gdcm seems to have the same issue. dcmdjpls from dcmtk seems to work fine.

**Screenshots**
![2021-12-15-135647_4480x1080_scrot](https://user-images.githubusercontent.com/46027684/146190619-da99b7d2-7177-4699-b443-f8d476e74394.png)

![2021-12-15-135810_4480x1080_scrot](https://user-images.githubusercontent.com/46027684/146190732-c1e8fca5-1c2d-4c90-83a4-c393da5e94a6.png)

[dicom.zip](https://github.com/nroduit/Weasis/files/7719495/dicom.zip)

**Comment by nroduit** [comment]
Have you test with the latest version 3.8.0 ?

**Comment by jmcoelloidonia** [comment]
Sorry, I should have done that before.

Same result, it still renders the image the same way.

**Comment by nroduit** [comment]
Could you send a sample by email (available on my profile) ?

**Comment by nroduit** [comment]
For compressed images, Weasis retrieves the width and height of the image in the jpeg header if it exists. 

The problem with this image is that in the DICOM metadata the image size is correct but not jpeg header:
DICOM Columns: 880 => width
DICOM Rows: 660 => height

and in jpeg header:
![Sélection_029](https://user-images.githubusercontent.com/993975/146375300-fdcab2d5-d7dd-4099-a216-2d858dcd2b5c.png)

This image is corrupted for me. A reference tool like dcmtk does not allow to convert this image to jpeg or png.

I think it is important to check with the supplier of the equipment that produces these corrupted images.

**Comment by jmcoelloidonia** [comment]
According to the Implementation Class UID in the dicom header, all files seems to be coming from one of the machines in this dicom conformance statement from philips http://incenter.medical.philips.com/doclib/enc/fetch/2000/4504/577242/577256/588723/5144873/5144488/5144982/DICOM_Conformance_Statement_Achieva_R2.5.pdf%3fnodeid%3d5148397%26vernum%3d-2

Which is weird, since one of the images is an ecography.

I had success converting the image with dcmtk using dcmdjpls (simply with dcmdjpls <source> <destination>).

Researching this issue, the standard seems to consider this case as something that should not happen, but it gives some rules on how to tackle the situation.

In https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.html#para_07617cc6-a4a9-4751-9435-7b496910168d this can be read:

_When decompressing, should the characteristics explicitly specified in the compressed data stream (e.g., spatial subsampling or number of components or planar configuration) be inconsistent with those specified in the DICOM Data Elements, those explicitly specified in the compressed data stream should be used to control the decompression. The DICOM data elements, if inconsistent, can be regarded as suggestions as to the form in which an uncompressed Data Set might be encoded, subject to the general and IOD-specific rules for uncompressed Photometric Interpretation and Planar Configuration, which may require that decompressed data be converted to one of the permitted forms._

Which I may be missreading but it seems to me that we should treat the uncompressed jpg image (decoded using the information inside the jpg itself) as the "new" pixel data of the element, and to use the dicom parameters for reencoding. But I'm not sure if the columns and rows tags should be use in this case to redraw that pixel data.

We are going to try and talk with the manufacturer about this, probably we will ask them to send us images in Little Endian only, but I'll try to know more about this issue. It may be a bug or something.

**Comment by nroduit** [comment]
Thanks for the explanation. Indeed the standard suggests to privilege the parameters in the data stream (jpeg) except for the parameter Photometric Interpretation which influences the result of the decompression. 

My interpretation is that the image size belongs to the data structure of the decompression stream and therefore I prefer not to use DICOM values (because the reverse error also exists). However I added an error log for version 4:

`05.02.2022 10:11:23.955 *ERROR* [Image Loader-pool-2-thread-1] org.weasis.dicom.codec.DicomMediaIO: The native image size (660x880) does not match with the DICOM attributes(880x660)`
