### ISSUE TITLE
Support measurement computations across Ultrasound regions with different scale factors

### ISSUE THREAD

**Issue by amasmiller** [nroduit/Weasis#227]
Currently (as of v3.8.0), for Ultrasound files with multiple regions that have different scale factors, only the scale factors from the first region found in the file are used.

For example, as noted by the blue text in the the below picture, the measurement for the ultrasound region on the left is correct, but the measurement on the top right is not.  The region on the left and top right have different scaling factors (`PhysicalDelta...` in DICOM standard), but only the scaling factor from the region on the left appears to be used.

![image](https://user-images.githubusercontent.com/32115401/146243238-2598ca0a-bd3d-4d48-b332-202239111265.png)

This appears to be the result of only the first region found in the file being used for capturing the scale factors:  https://github.com/nroduit/Weasis/blob/v3.8.0/weasis-dicom/weasis-dicom-codec/src/main/java/org/weasis/dicom/codec/utils/Ultrasound.java#L44.

The DICOM file loaded in the above screenshot is here: (unzip for `.dcm` file):
[20211210125142192940.zip](https://github.com/nroduit/Weasis/files/7721849/20211210125142192940.zip)

If possible, it would be useful to show the correct measurement for a region if it has a different scale factor than the first region loaded.

**Comment by nroduit** [comment]
This is a regression from another fix. The default behavior: no calibration is applied when multiple spatial calibrations exist. So currently for this kind of image, only pixel units will be available as handling several regions of calibration required munch more changes.

**Comment by amasmiller** [comment]
Thanks.  I see the fix you checked in now only shows pixels.  This works for us.

**Comment by nroduit** [comment]
Thanks for the example because it's the first time I see an image with several spatial calibrations. I guess this is not very common.
