### ISSUE TITLE
Add new default layouts for panoramic screens and MPR

### ISSUE THREAD

**Issue by nroduit** [nroduit/Weasis#229]

**Comment by arunjoshtech** [comment]
In which version it will be updated to use? I have downloaded latest version in this morning and found this layout is not shown.
![weasis panoromic viewe](https://user-images.githubusercontent.com/63642104/146497950-423dfdd6-b5b7-4619-bb47-6bd23bed9bd8.PNG)

**Comment by nroduit** [comment]
It will be in the next release 3.8.1 (should be in January)
