### ISSUE TITLE
Default Left Mouse functions should be Series Scroll instead of Draw

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#230]
Dear sir,
once images loading into viewer the next options we need to do is series scrolling and left mouse default tool is draw which has no direct use in real time as per my observation. 
I request Left mouse default functions for series scrolling as standard since radiologist lacking the choosing facility features.
kindly consider

**Comment by nroduit** [comment]
The [default left mouse action is the Window/Level ](https://github.com/nroduit/Weasis/blob/master/weasis-core/weasis-core-ui/src/main/java/org/weasis/core/ui/editor/image/MouseActions.java#L48-L59)and this is what the majority of users want. The scrolling of the images is done by default with the mouse wheel.

However, these configurations are persistent by user and can be changed as needed from the toolbar. Moreover, it is possible to change the initial default configuration with the [preferences](https://nroduit.github.io/en/basics/customize/preferences/) overload either by using [weasis-pacs-connector](https://github.com/nroduit/weasis-pacs-connector#launch-weasis-with-other-parameters) or [by injecting a property at startup](https://nroduit.github.io/en/getting-started/weasis-protocol/#modify-the-launch-parameters). The properties for mouse actions are defined [here](https://github.com/nroduit/Weasis/blob/master/weasis-distributions/etc/config/ext-config.properties#L128-L135).

**Comment by arunjoshtech** [comment]
Dear Sir,
Thanks for the reply and detailed instructions.
