### ISSUE TITLE
Weasis icon at higher resolutions

### ISSUE THREAD

**Issue by alcir** [nroduit/Weasis#233]
Do you have the Weasis icon (and maybe the Dicomizer one) at 128x128, or better in svg?
Thanks.

**Comment by alcir** [comment]
For reference: https://github.com/flathub/flathub/pull/2703#discussion_r775267371

**Comment by nroduit** [comment]
Here are svg icons: [Logo.zip](https://github.com/nroduit/Weasis/files/7779257/Logo.zip)
