### ISSUE TITLE
Building on aarch64: is it supposed to work?

### ISSUE THREAD

**Issue by alcir** [nroduit/Weasis#234]
Warning: I'm not an expert, just try&error. Totally dumb.

On Linux aarch64, using
`mvn clean package -Dportable=true -P compressXZ -Dmaven.repo.local=../.m2/repository`

I get

```text
...
      [jar] Updating jar: /run/build/weasis/weasis-distributions/target/tmp/weasis-launcher.jar
[INFO] Executed tasks
[INFO] 
[INFO] --- build-xz-plugin:1.0.0:packFiles (xz) @ weasis-distributions ---
[INFO] Compressing 44 files
[INFO] 
[INFO] --- maven-dependency-plugin:3.2.0:copy (copy-bindex-lib) @ weasis-distributions ---
[INFO] Configured Artifact: org.osgi.util:bindex:2.2:jar
[INFO] Copying bindex-2.2.jar to /run/build/weasis/weasis-distributions/target/lib/bindex.jar
[INFO] 
[INFO] --- maven-assembly-plugin:3.3.0:single (zip-resources) @ weasis-distributions ---
[INFO] Reading assembly descriptor: src/assembly/zip-resources.xml
[INFO] Building zip: /run/build/weasis/weasis-distributions/target/resources.zip
[INFO] 
[INFO] --- launch4j-maven-plugin:2.1.2:launch4j (l4j-clui) @ weasis-distributions ---
[INFO] launch4j: Compiling resources
[INFO] launch4j: /run/build/weasis/weasis-distributions/../.m2/repository/net/sf/launch4j/launch4j/3.14/launch4j-3.14-workdir-linux/bin/windres: /run/build/weasis/weasis-distributions/../.m2/repository/net/sf/launch4j/launch4j/3.14/launch4j-3.14-workdir-linux/bin/windres: cannot execute binary file
[INFO] launch4j: Generated resource file...
[INFO] launch4j: LANGUAGE 0, 1
...
[ERROR] 
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (126): /run/build/weasis/weasis-distributions/../.m2/repository/net/sf/launch4j/launch4j/3.14/launch4j-3.14-workdir-linux/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j7301168338460211991rc /tmp/launch4j7105448729010801343o
    at net.sf.launch4j.Builder.build (Builder.java:149)
    at com.akathist.maven.plugins.launch4j.Launch4jMojo.doExecute (Launch4jMojo.java:439)
...
```

Indeed `net/sf/launch4j/launch4j/3.14/launch4j-3.14-workdir-linux/bin/windres` is an i386 binary. (Building on Linux x86_64, works, and it uses launch4j linux64 probably).
But since it is used to generate a windows launcher (as far as I can understand), is it possible to exclude this task?

**Comment by alcir** [comment]
Oh, OK. I had to put portable to false.

**Comment by nroduit** [comment]
You need to have `-Dportable=true` because currently the build script `package-weasis.sh` required this weasis-portable package.

The issue comes from an unneeded Windows binary. Anyway, you can build it by installing the linux package `ia32-libs` , see https://nroduit.github.io/en/getting-started/building-weasis/#building-weasis-distributions

**Comment by alcir** [comment]
> You need to have `-Dportable=true` because currently the build script `package-weasis.sh` required this weasis-portable package.

And what happens if I set `-Dportable=false`? At least on x86_64 it works anyway.

**Comment by nroduit** [comment]
No, only the web distribution package is built (weasis.war).

You should be able to build. What is your Linux distribution?

**Comment by alcir** [comment]
I'm tinkering with flatpak. Using the org.freedesktop.Sdk-21.08 and the openjdk17 extension.

These are the steps I'm following.
      - mvn clean install
      - cd weasis-distributions && mvn clean package -Dportable=false -P compressXZ -Dmaven.repo.local=../.m2/repository
      - unzip weasis-distributions/target/portable-dist/weasis-portable.zip
      - sed -i 's/PACKAGE=YES/PACKAGE=NO/' weasis-distributions/script/package-weasis.sh
      - sed -i 's/curl.*/#&/' weasis-distributions/script/package-weasis.sh
      - weasis-distributions/script/package-weasis.sh --input . --output tmp --jdk ${JAVA_HOME}
      - mv tmp/Weasis/bin /app/
      - mv tmp/Weasis/lib /app/

The Weasis launcher is created and the application works.

**Comment by nroduit** [comment]
Ok, it sounds good. I will check it.

**Comment by alcir** [comment]
For reference: https://github.com/flathub/flathub/pull/2703
