### ISSUE TITLE
Cannot display image with invalid shutter

### ISSUE THREAD

**Issue by xiaoluGood** [nroduit/Weasis#236]
![image](https://user-images.githubusercontent.com/8968472/148036898-6a40f2cd-cc4f-49c3-a293-354bfb929a42.png)

this is link the download link for the dcm.
https://1drv.ms/u/s!AjnqPSUP3b98inWdv5Jo7arELEGD?e=qlXPRs

**Comment by nroduit** [comment]
This image contains a polygonal shutter with only one point. This shutter type must be a closed shape, so required at least two points.

I will add a consistency check to fix this issue. Meanwhile, you can uncheck "Shutter" in the Display Tool panel on the right bar.
