### ISSUE TITLE
weasis-portable.zip 3.8.1 is missing viewer-win32.exe

### ISSUE THREAD

**Issue by gregkotsaftis** [nroduit/Weasis#245]
latest 3.8.1 release is missing file "viewer-win32.exe" from "weasis-portable.zip"

**Comment by nroduit** [comment]
I just upload again at https://sourceforge.net/projects/dcm4che/upload/Weasis/3.8.1/

The portable distribution is deprecated and will be completely removed in version 4. The reasons for this are described [here](https://nroduit.github.io/en/getting-started/#weasis-distributions).

**Comment by gregkotsaftis** [comment]
Thnx for uploading portable again.
I cannot find the reasons for removing portable from version 4! Is the link correct?

**Comment by nroduit** [comment]
This is mainly because some features cannot be supported in the portable version and it is difficult to maintain multiple distributions. 
However, I will see to give a procedure to create a portable version for Windows only.

**Comment by ada-s4c** [comment]
@nroduit 

>However, I will see to give a procedure to create a portable version for Windows only.

Any update on this?

**Comment by nroduit** [comment]
This can be done by making an ISO image containing the viewer, see [documentation](https://weasis.org/en/tutorials/dicom-export/index.html#cddvd-image).
