### ISSUE TITLE
Annotations/labels font size

### ISSUE THREAD

**Issue by xrsLT** [nroduit/Weasis#246]
Is it possible to increase annotations/label font size? All I can find in settings measurements labels. What about regular labels, like patient name, study id and etc? When we print dicom, all text on printed foto is very small. Can we increse that?

**Comment by nroduit** [comment]
No, the size of the general labels is defined according to the size of a view.

[The future version 4](https://github.com/nroduit/Weasis/actions/runs/2018837528) allows to define a font size for the whole application (from the preferences, see the screenshot). This also concerns the size of the fonts in the views which work a little bit differently than in the previous versions.
![image](https://user-images.githubusercontent.com/993975/160072741-731048b3-0ac1-4317-bd0d-3f7ae37a3ab9.png)


However, the printing issue remains in my todo list with the difficulty that the APIs for all systems are limited.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
