### ISSUE TITLE
Weasis viewer generate hidden dicom file on Mac OS

### ISSUE THREAD

**Issue by BigKu** [nroduit/Weasis#247]
I found viewer create hidden dcm file when open dcm file in weasis.
hidden file name start with `._.` it's look like `._.1231420124.dcm`

Is it possible to prevent automatic creation of hidden files?

![dicom hidden file](https://user-images.githubusercontent.com/28921150/159455846-aae3277c-ffee-4359-8cbf-944208073e3a.png)

**Comment by nroduit** [comment]
Weasis do not create any files when opening dcm files. This is related to the system, see https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
