### ISSUE TITLE
gcp-hcapi plugin

### ISSUE THREAD

**Issue by tuguldurs** [nroduit/Weasis#248]
**Describe the bug**
Thanks for putting together this awesome viewer! I am having trouble running the gcp-hcapi plugin with Weasis locally.

**To Reproduce**
Following the instructions I took just these steps:
1. Downloaded the latest jar file (v3.0.13) from [here](https://github.com/GoogleCloudPlatform/weasis-chcapi-extension).
2. "plugins" directory did not exist in my `weasis.codebase.url` (`/Applications/Weasis.app/Contents/app`), so I created one and put the plugin jar file there.
3. Added following line at the end of `conf/ext-config.properties`:
`felix.auto.start.85 = ${weasis.codebase.url}/plugins/weasis-chcapi-extension-3.0.13.jar`
4. Run Weasis executable.

**Expected behavior**
My understanding is that once the executable runs the user should see the new tab - Google DICOM Explorer right away, but it just shows the default tab (DICOM Explorer) alone.

**Desktop:**
 - OS: OSX 11.5.2
 - Weasis: 3.8.1

**Additional context**
The boot log (in `.weasis/log/log-X.X.log`) doesn't seem to report any errors. Though it will throw plugin installation fail error if I intentionally give wrong path in step#3 above.

**Screenshots**

**Traces**

thank you for your time!

**Comment by nroduit** [comment]
The google plugin contains some limitations to manage relationships between images, it is better to use an OAuth2 connection directly in Weasis (available in the last release). See this [post](https://github.com/nroduit/Weasis/issues/125).

**Comment by tuguldurs** [comment]
thank you, will try out the direct OAuth2 connection!

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
