### ISSUE TITLE
custom preset WINDOWS

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#249]
Dear Sir,

Is there any options to add custom preset window ?

Like bone windows lung window, need to add own window value.

**Comment by nroduit** [comment]
The [presets](https://github.com/nroduit/Weasis/blob/master/weasis-distributions/resources/presets.xml) are located in the resources folder, see how to [manage preferences and resources](https://nroduit.github.io/en/basics/customize/preferences/#customizeresources).

**Comment by arunjoshtech** [comment]
Thanks for your reply
