### ISSUE TITLE
Importing an annotations xml file doesn't work

### ISSUE THREAD

**Issue by andreashkh** [nroduit/Weasis#258]
Hi,

When exporting a case with annotations as jpg/png, a xml file is generated containing the annotations. Is there a way to import such a file? **Open Images** and **Import Dicom** seem to ignore the xml file that is placed in the same directory. 

Thanks!

**Comment by nroduit** [comment]
For DICOM, annotations are saved in a DICOM Presentation State file, see https://nroduit.github.io/en/tutorials/build-ko-pr/#presentation-state-pr-or-gsps

For non DICOM, an xml file is saved and it should be loaded when using "Open Images" but I just saw that it doesn't work. However, when I drag and drop the image, it opens the xml file of the annotations. So it's a bug.
