### ISSUE TITLE
Some views of the MPR are shifted when changing the layout

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#262]
Hi Sir,
Please observe the attached view on MPR panoramic window views issues to display sagittal  and coronal images.

https://user-images.githubusercontent.com/63642104/166115017-ae8f6f66-615d-4799-a1f1-9c719acb4a07.mp4

I need to use PAN  function to make the images to appear normal from hided view.
This issues in Exist in 3.8.1 also.

**Comment by nroduit** [comment]
Indeed the problem occurs when the zoom is at more than 100% and you change the layout.

As a workaround, you can right-click on one of the views and select Reset > Zoom.

**Comment by arunjoshtech** [comment]
And it happens even in 100% Zoom with 14 inch screen laptop.
I believe you may fix the the issues and make the release earliest.

**Comment by arunjoshtech** [comment]
Dear Sir,
It will be highly helpful if you can advise the expected Release for this Bug.
Please advise

**Comment by nroduit** [comment]
It will be fixed in the next release which should be published in June.

**Comment by arunjoshtech** [comment]
Dear Sir, 
I have tested with version 4.0.1 and found the issues persist. kindly advise
