### ISSUE TITLE
Check if Weasis is installed on the user machine

### ISSUE THREAD

**Issue by Diegovictorbr** [nroduit/Weasis#266]
Hello! I would like to know if there is a way to know in advance if Weasis is installed in the user computer based on a first interaction. 

Basically from my JavaScript application, I would ask the user to click a button to trigger some kind of check. If it is a URI, a true response from Weasis could indicate that there is a valid installation in the user machine, therefore activating all Weasis interactions on the system.

Is this possible?

**Comment by nroduit** [comment]
I don't think there is a good way to do that. See this [post](https://stackoverflow.com/questions/62657154/how-can-i-check-whether-an-application-is-installed-from-a-web-browser).
