### ISSUE TITLE
Saved 'Rolling log' property is not restored correctly.

### ISSUE THREAD

**Issue by AlexZaka** [nroduit/Weasis#267]
**Describe the bug**
Saved 'Rolling log' property is not restored correctly.

**To Reproduce**
1. Go to 'File-Preferences-Logging'
2. Set 'Rolling log' checkbox
3. Restart Weasis
4. 'Rolling log' property in 'File-Preferences-Logging' is not set

**Expected behavior**
'Rolling log' property selection must be preserved.

**Desktop (please complete the following information):**
 - OS: Mageia 8 Linux
 - Weasis Version 4.0.0-RC

**Additional context**
It seems there is a typo in LoggingPrefView.java. 

--- ./weasis-core/weasis-core-ui/src/main/java/org/weasis/core/ui/pref/LoggingPrefView.java.orig	2022-05-09 13:05:08.053013419 +0500
+++ ./weasis-core/weasis-core-ui/src/main/java/org/weasis/core/ui/pref/LoggingPrefView.java	2022-05-09 13:05:08.066013418 +0500
@@ -137,7 +137,7 @@
     }
     comboBoxStackLimit.setSelectedItem(limit >= 0 ? Integer.toString(limit) : "");
 
-    checkboxFileLog.setSelected(prefs.getBooleanProperty(AuditLog.LOG_FILE, false));
+    checkboxFileLog.setSelected(prefs.getBooleanProperty(AuditLog.LOG_FILE_ACTIVATION, false));
     spinner.setValue(getIntPreferences(AuditLog.LOG_FILE_NUMBER, 5, null));
     spinner1.setValue(getIntPreferences(AuditLog.LOG_FILE_SIZE, 10, "MB"));
     checkRollingLog();

**Comment by nroduit** [comment]
Thanks for reporting this bug and with the solution!
