### ISSUE TITLE
Change the text color

### ISSUE THREAD

**Issue by ukky17** [nroduit/Weasis#268]
I am having trouble in displaying PR text.

I have a PR dicom file that has `TextColorCIELabValue = [63658, 27358, 57178]` (which means yellow). However the PR is displayed as a white text on the Weasis viewer. I am wondering if it's possible to display the PR text in color.

Thank you in advance.

PS. I am using Weasis 3.8.1 on Mac OS.

**Comment by nroduit** [comment]
The style part is implemented for drawings but not for text. I think it was because it was difficult to make it fully compatible with the more generic way of displaying text on the image.

**Comment by ukky17** [comment]
Thank you for the reply.
