### ISSUE TITLE
Cannot disable dicom export & dicom send in Weasis with properties

### ISSUE THREAD

**Issue by yufoon2002** [nroduit/Weasis#269]
Hello!
I am using portable (desktop) version of Weasis using Windows10. I would like to disable the dicom export and dicom send function in the weasis. I access the weasis/conf/ext-config.properites configuration file. I changed  "#weasis.export.dicom=false" to "weasis.export.dicom=false" (removing the hash ahead) and also changed "#weasis.export.dicom.send=false" to "weasis.export.dicom.send=false" (also removing the hash ahead) inside the config file. However, there is no effect. I have tried this in both version 3.8.1and the latest version 4.0 which did not work in both versions. I have tried disabling the main menu bar by removing the hash ahead of the line #weasis.menu.menubar=false similar to the above method which works successfully (menubar disappears after changing config file). Can you help me? Thank you in advance.

**Comment by nroduit** [comment]
Thanks for reporting. It seems to be a bug, I have to check.

**Comment by yufoon2002** [comment]
Thank you for your reply. I notice there is a comment ########## Properties which are not stored in local preferences and not visible in GUI, always applied from the server-side  ########## above the the export configuration line. I am not sure whether this implies this configuration can only be applied if the application is accessed using web server and it not applicable if it is runs in desktop portable application mode. If this is really the case, can I request the configuration for allowing export & dicom send can also be configured if this app is running in portable desktop mode? Thank you very much for your help.

**Comment by yufoon2002** [comment]
I have checked again when the weasis is launched from a web server and the disable dicom export / dicom-send configuration can work properly. I would be grateful if you can allow configuration of these functions using stand-alone / portable version of weasis in the next release. Thank you very much.
