### ISSUE TITLE
Patient name is not selected after study reload.

### ISSUE THREAD

**Issue by AlexZaka** [nroduit/Weasis#270]
Patient name is not selected in Patient combo box after study reload.

1. Import some study with 'Import DICOM' -> 'Local Device' or 'DICOM Zip'.
2. Remove study from thumbnail pane with 'Remove this Study' or 'Remove this Patient'.
3. Import once more the same study.
4. Patient name is not selected in Patient combo box.

Patient Name of certain study, series thumbnails of which are shown in Thumbnail Pane, should be selected in Patient combo box.

 - OS: Mageia 8 Linux
 - Weasis Version 4.0.0-RC
 
Here is my suggestion to solve this issue:

```
--- ./weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/DicomExplorer.java.orig	2022-05-14 13:31:15.426025130 +0500
+++ ./weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/DicomExplorer.java	2022-05-14 13:43:54.743966836 +0500
@@ -801,6 +801,9 @@
 ``
     if (modelPatient.getIndexOf(patient) < 0) {
       modelPatient.addElement(patient);
+      if (patientCombobox.getSelectedIndex() < 0) {
+        patientCombobox.setSelectedItem(patient);
+      }
     }

``` 

![Screenshot_20220515_164506](https://user-images.githubusercontent.com/105201856/168473004-cae92043-32d1-4745-a2a8-fb63741dbbda.jpg)

**Comment by nroduit** [comment]
Thanks for reporting. Tis is related also to another bug when opening new tab.
