### ISSUE TITLE
Allow import of password protected zip dicom file 

### ISSUE THREAD

**Issue by yufoon2002** [nroduit/Weasis#273]
Weasis allow import of dicom files which are compressed in zip format. However, if the zip file is protected by password, the weasis cannot open the zip file.  

It would be a good idea if weasis can also import zipped dicom files which are protected by password in the next release and ask the user to enter password after initiating the import if password has been set during the previous compression of zip file. 

Thank you very much.

**Comment by nroduit** [comment]
Add zip4j as the native Java does not handle zip encryption.
