### ISSUE TITLE
Patient and study duplication at DICOMDIR import.

### ISSUE THREAD

**Issue by AlexZaka** [nroduit/Weasis#276]
While DICOMDIR import, Patient and Study are loaded twice. No matter what kind of import, CD-ROM or zipped file with DICOMDIR.

1. Import some study with DICOMDIR from CD-ROM or Zipped file.
2. Patient name in patient combo is loaded twice like in Pic-1.
3. After deletion of patient or study from thumbnail tab, the Patient Name and Study Date still present in corresponding combos like in Pic-2.

 - OS: Mageia 8 Linux
 - Weasis Version 4.0.1-SNAPSHOT

![Pic-1](https://user-images.githubusercontent.com/105201856/170350957-b1d33198-7985-431c-935e-ee21d59069cc.png)
![Pic-2](https://user-images.githubusercontent.com/105201856/170350968-a19083be-07c7-40a4-a961-0432e95e713e.png)

It seems there is a superfluous code in DicomDirLoader.java:

```
--- ./weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/DicomDirLoader.java.orig	2022-05-24 08:49:25.000000000 +0500
+++ ./weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/DicomDirLoader.java	2022-05-24 22:57:34.068804943 +0500
@@ -108,13 +108,13 @@
                 }
               });
     }
-    for (LoadSeries loadSeries : seriesList) {
-      String modality = TagD.getTagValue(loadSeries.getDicomSeries(), Tag.Modality, String.class);
-      boolean ps = ("PR".equals(modality) || "KO".equals(modality)); // NON-NLS
-      if (!ps) {
-        loadSeries.startDownloadImageReference(wadoParameters);
-      }
-    }
+//    for (LoadSeries loadSeries : seriesList) {
+//      String modality = TagD.getTagValue(loadSeries.getDicomSeries(), Tag.Modality, String.class);
+//      boolean ps = ("PR".equals(modality) || "KO".equals(modality)); // NON-NLS
+//      if (!ps) {
+//        loadSeries.startDownloadImageReference(wadoParameters);
+//      }
+//    }
     return seriesList;
   }

```

**Comment by nroduit** [comment]
I cannot reproduce this issue. Could you share a data sample?

**Comment by AlexZaka** [comment]
[encryptedDICOM.zip](https://github.com/nroduit/Weasis/files/8779332/encryptedDICOM.zip)
Password - 12345678

**Comment by nroduit** [comment]
Fixes the patient merge problem when demographic identifiers are different within the same exam.

The Issuer of Patient ID field varies between DICOM files which should not be possible.
