### ISSUE TITLE
in 3.8.1 linux shell file is written with windows EOL instead of unix EOL 

### ISSUE THREAD

**Issue by poltpolt** [nroduit/Weasis#277]
Please check the [GitHub issues system](https://github.com/nroduit/Weasis/issues), the [forum](https://groups.google.com/group/dcm4che) and/or this [website](../getting-started) first to see if your problem has not been reported yet.

**Describe the bug**
Viever-linux.sh is writen with windows EOL instead of UNIX EOL
unable to run until I edit and replace EOL to UNIX

**To Reproduce**
sh viewer-linux.sh

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS 10.15.1]
 - Weasis Version [e.g. 3.1.0]

**Additional context**
Add any other context about the problem here [e.g. network issue: give information about anti-virus or network security software, firewall, proxy...]. 

**Screenshots**

**Traces**
If applicable, add [log files from Weasis](https://nroduit.github.io/en/faq/#how-to-enable-weasis-logging) or from the DICOM archive.

**Comment by nroduit** [comment]
Viever-linux.sh no longer exists in the current branch because the portable version has been abandoned in favor of the installers.
