### ISSUE TITLE
Opening strategy is not working as expected for local device import.

### ISSUE THREAD

**Issue by AlexZaka** [nroduit/Weasis#302]
Opening strategy is not working as expected for local device import with opening options "Only the firs patient (remove previous)" and "All the patients (remove previous)".

1. Go to 'File -> Import -> DICOM -> Local Device'
2. Choose some folder with DICOM files
3. Select "All the patients (remove previous)"  option for the "Open in new tab" listbox
4. See that no tab is opened for chosen DICOM study

**Expected behavior**
At least one tab should be opened for the chosen DICOM study.

**Desktop (please complete the following information):**
 - OS: Mageia 8 linux
 - Weasis Version 4.0.1

**Comment by nroduit** [comment]
Thank you for reporting this problem. I have indeed noticed trouble with the feature "remove the previous tabs".
