### ISSUE TITLE
Weasis viewer problem when I open studies recursively

### ISSUE THREAD

**Issue by cedg31** [nroduit/Weasis#311]
Hi team,

I have a very strange problem with Weasis.
When trying to open dicom files downloaded locally in my computer errors appear on any viewer if we try to open the wole study folder or batch. 
This was ok when downloading ad opening same images last week.

But when I try to open studies by studies it's ok ?

When i try to open study folder recursively I have no problem and the log are like this :

20.07.2022 18:09:42.540 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: TAP sag
20.07.2022 18:09:42.779 *DEBUG* [AWT-EventQueue-0] org.weasis.core.api.media.data.ImageElement: Asking for reading image: 1.2.826.0.1.3680043.10.436.2743928743954068168661722373880403595
20.07.2022 18:09:42.779 *DEBUG* [Image Loader-pool-4-thread-1] org.weasis.dicom.codec.DicomMediaIO: Start reading dicom image frame: 0 sopUID: 1.2.826.0.1.3680043.10.436.2743928743954068168661722373880403595
20.07.2022 18:09:42.848 *DEBUG* [Thumbnail Loader-pool-5-thread-1] org.weasis.core.api.media.data.ImageElement: Asking for reading image: 1.2.826.0.1.3680043.10.436.2102780595400955389035356348047620683
20.07.2022 18:09:42.848 *DEBUG* [Image Loader-pool-4-thread-1] org.weasis.dicom.codec.DicomMediaIO: Start reading dicom image frame: 0 sopUID: 1.2.826.0.1.3680043.10.436.2102780595400955389035356348047620683

When i try to open Study rep recursively I have an error and this in my log :

20.07.2022 18:08:49.879 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.DicomExplorer: Add series: TAP cor
20.07.2022 18:08:49.893 *DEBUG* [Thumbnail Loader-pool-5-thread-1] org.weasis.core.api.media.data.ImageElement: Asking for reading image: 1.2.826.0.1.3680043.10.436.1054495391633108515341415171683712114
20.07.2022 18:08:49.893 *DEBUG* [Image Loader-pool-4-thread-1] org.weasis.dicom.codec.DicomMediaIO: Start reading dicom image frame: 0 sopUID: 1.2.826.0.1.3680043.10.436.1054495391633108515341415171683712114
20.07.2022 18:08:49.893 *ERROR* [Image Loader-pool-4-thread-1] org.weasis.dicom.codec.DicomMediaIO: The native image size (0x0) does not match with the DICOM attributes(512x807)
20.07.2022 18:08:49.926 *DEBUG* [Thumbnail Loader-pool-5-thread-1] org.weasis.core.api.media.data.ImageElement: Asking for reading image: 1.2.826.0.1.3680043.10.436.4983143517400631109857512228821946538
20.07.2022 18:08:49.936 *DEBUG* [Image Loader-pool-4-thread-1] org.weasis.dicom.codec.DicomMediaIO: Start reading dicom image frame: 0 sopUID: 1.2.826.0.1.3680043.10.436.4983143517400631109857512228821946538
20.07.2022 18:08:49.936 *ERROR* [Image Loader-pool-4-thread-1] org.weasis.dicom.codec.DicomMediaIO: The native image size (0x0) does not match with the DICOM attributes(512x807)

If someone have any idea ?

Thanks a lot.

OS: version Windows 11
Weasis Version : 4.0.1

**Comment by nroduit** [comment]
According to the logs the images seem to be corrupted and therefore cannot be read.

Check the contents of the directories. Try with other viewers.

**Comment by cedg31** [comment]
Thanks for your answer.

I read the log too ;)

But why there is no problem when I open study by study ?

**Comment by cedg31** [comment]
And I try it wiith other viewer like Radiant andd it's ok, but there is no recursive option so I open study by study.

**Comment by nroduit** [comment]
Are you sure there are no hidden folders with the same images but corrupted?

There is not much I can do without being able to reproduce the problem.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
