### ISSUE TITLE
Measurement Tool - Rectangle drag method

### ISSUE THREAD

**Issue by Gjunryeol** [nroduit/Weasis#321]
Hi Weasis team

I would like to ask a question about one problem
If possible, I'll even get the answer

**Is your feature request related to a problem? Please describe.**
I am unfamiliar with the drag format when using the rectangle of the measure tool

**Describe the solution you'd like**
I am trying to change the drag method of mesuretool-rectangle

**Describe alternatives you've considered**
I think it's okay to change the drag event, but I don't know what code to change because I don't have the expertise.

I didn't speak English well, so I used a translator. If there's something you don't understand, please let me know!
thank you

**Comment by nroduit** [comment]
Please describe more precisely what is the problem and what is the proposed improvement because only with this information I will not do anything.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
