### ISSUE TITLE
Icons not showing correctly on 4.0.2

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#322]
Hi, I just installed 4.0.2 on a Windows 10 Home 64bit and the icons and thumbnails are shown as red squares:

![imagen](https://user-images.githubusercontent.com/1405017/182603999-fc05e5ba-1c88-4464-83a0-2365afc16151.png)

**Comment by mathiasfink** [comment]
please check the resources folder

**Comment by nroduit** [comment]
How do you run weasis and is the "weasis.resources.url" property overloaded? see [Preferences](https://nroduit.github.io/en/basics/customize/preferences/).
