### ISSUE TITLE
Chinese display error in DICOM information

### ISSUE THREAD

**Issue by xiaoluGood** [nroduit/Weasis#324]
hi
I compiled the weasis source code, and want to change the problem of Chinese display error.
I use $dciom: get - W http://...xml to load DICOM, I want to use patient info in XML to replace those Chinese error,
How can I modify the source code

**Comment by nroduit** [comment]
Please explain first what the problem is because if it is a bad encoding it can come from the files that are loaded.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
