### ISSUE TITLE
Do not export all the images of a series in non-dicom files

### ISSUE THREAD

**Issue by hetalsma** [nroduit/Weasis#327]
Dear mr Roduit,
When exporting all image files to JPEG:
File -> Export -> DICOM->export to 'JPEG 2000' 
The images is in the folder are not complete. Only the first in the serie from a study is exported.
Is it possible to export all series in a study.

Best wishes,

Herman Talsma

**Comment by nroduit** [comment]
Yes it seems to be a bug. The export works for all formats except jpeg2000.

**Comment by hetalsma** [comment]
Thank you, the same for JPEG Lossy, PNG and TIFF. The DICOM files are exported ok.

**Comment by nroduit** [comment]
By testing with several examples, I can export all types except jpeg 2000.

If the images can't be exported in jpg, png or tif, could you provide a sample?

**Comment by hetalsma** [comment]
[TestCaren, Carina.zip](https://github.com/nroduit/Weasis/files/9476514/TestCaren.Carina.zip)

This is an example...

**Comment by nroduit** [comment]
Thanks, it is not the same issue that I've seen. In this case, the image within the series has always 1 as the instance number which is used for the image index in the filename.
