### ISSUE TITLE
SCROLL after PAN resetting Image into centre of the canvas

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#328]
hi sir, i have added a video for observation.
I want to pan the image in different place of can was then to scroll it but it is getting reset to default position. A doctor expressed concern over it. So I have made a comparison with Radiant viewer

https://user-images.githubusercontent.com/63642104/188684820-c1f7e4c2-77bf-48b0-b90f-073af316a3ac.mp4

https://user-images.githubusercontent.com/63642104/188684839-b3b5c2fb-bcfb-4504-a34d-8bc36ce7761e.mp4

 shown in this video

**Comment by nroduit** [comment]
This is the normal behavior when in "Resize to best fit" mode where with every change the image is zoomed to the size of the view from the center. This is the default mode for a standard view.

By changing the zoom mode or the zoom factor, the "best fit" mode is no longer applied and therefore the image will no longer be recentered. MPR views are not in "Best Fit" by default.

**Comment by nroduit** [comment]
A note has been added in the documentation: https://nroduit.github.io/en/tutorials/zoom/

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.

**Comment by arunjoshtech** [comment]
This Issues is not resolved. it is not acceptable behavior as per Radiologist feedback

**Comment by nroduit** [comment]
For me, this issue has been solved, see the explanation in the documentation above.

When the zoom is in best-fit mode, then it's normal behavior to recenter the image. As soon as the zoom is changed, the PAN position is preserved.
