### ISSUE TITLE
Measure in MM instead of PX

### ISSUE THREAD

**Issue by Kolumor** [nroduit/Weasis#330]
Hello team! 
I need to configure weasis so that the measurements taken are in milimiters instead of pixels. I couldnt find a way to do it.
Could you please help me?

**Comment by nroduit** [comment]
If you think this is a problem related to Weasis, please describe the problem so that it can be reproduced.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
