### ISSUE TITLE
VIEWER INTERNAL CONTROLS NOT SHOWING.

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#332]
Dear sir,
I have attached the video of very rare behavior of weasis application on the particular pc.
I tried to resolve by reinstall / install different version but not helped.
Please refer this two video.

https://user-images.githubusercontent.com/63642104/191500202-0fa29e6b-5141-4d1a-8f52-182d2c18eb61.mp4

https://user-images.githubusercontent.com/63642104/191500213-f964c702-43d7-410c-adf3-495a3978ad07.mp4

**Comment by nroduit** [comment]
Please specify which version is used and look [in the log files](https://nroduit.github.io/en/faq/#how-to-enable-weasis-logging) to see if there are any errors. Otherwise, I need a procedure to reproduce the problem.

**Comment by arunjoshtech** [comment]
This happened for all the versions i tested in this PC. I missed to collect log file.
So I will close the issues until I get access next time.
