### ISSUE TITLE
Weasis parses data from gsps file?

### ISSUE THREAD

**Issue by wangwenzhao1** [nroduit/Weasis#336]
Weasis parses data from gsps file

**Comment by nroduit** [comment]
Please provide a clear description of what you expected. At this point, no answer can be given. As a reminder, this place allows you to submit bugs or request new features

**Comment by wangwenzhao1** [comment]
Weasis parses dicom tag and pixel in gsps file

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
