### ISSUE TITLE
Ellipse Tool

### ISSUE THREAD

**Issue by scope-antofa** [nroduit/Weasis#341]
Hi  @nroduit ,   congratulation for this proyect :

in Weasis 2.5.x with the ellipse tool you could create ellipse to both sides (moving the mouse to the right ,moved the ellipse to the right, and moving the mouse to the left, moved it to the left, 
this tool(or library)works perfectly on Windows 10. 

The Issue is in Weasis 4.0.2, only lets create ellipse to the right, moving the mouse to the left is also drawn to the right, doesn't work like before.

I am trying to find the differences in this file, on both version, to try to correct it and contribute.
I could see that in version 4 the extends EllipseGraphic class was changed. (2.5: extends RectangleGraphic-->4.0(master):extends ObliqueRectangleGraphic)
And also that the library was no longer used: **import java.awt.geom.Ellipse2D**;

Please i need help, guidance
 or (documentation) for this module. I need it to work like before.
I hope something can be done.
Thank you very much.

**weasis/weasis-core/weasis-core-ui/src/main/java/org/weasis/core/ui/model/graphic/imp/area/EllipseGraphic.java**

**Weasis 2.5:**

package org.weasis.core.ui.model.graphic.imp.area;

**import java.awt.geom.Ellipse2D;**
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.weasis.core.api.image.measure.MeasurementsAdapter;
import org.weasis.core.api.image.util.MeasurableLayer;
import org.weasis.core.api.image.util.Unit;
import org.weasis.core.ui.Messages;
import org.weasis.core.ui.model.utils.bean.MeasureItem;
import org.weasis.core.ui.model.utils.bean.Measurement;
import org.weasis.core.ui.util.MouseEventDouble;

@XmlType(name = "ellipse")
@XmlRootElement(name = "ellipse")
public class EllipseGraphic extends **RectangleGraphic** {
    private static final long serialVersionUID = 3296060775738751236L;

    public static final Icon ICON = new ImageIcon(EllipseGraphic.class.getResource("/icon/22x22/draw-eclipse.png")); //$NON-NLS-1$

    public static final Measurement AREA = new Measurement(Messages.getString("measure.area"), 1, true, true, true); //$NON-NLS-1$
    public static final Measurement PERIMETER =
...

**Weasis 4.0:**

....
`package org.weasis.core.ui.model.graphic.imp.area;

import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.awt.geom.Line2D;
import java.awt.geom.Path2D;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import org.weasis.core.api.gui.util.GeomUtil;
import org.weasis.core.api.image.measure.MeasurementsAdapter;
import org.weasis.core.api.image.util.MeasurableLayer;
import org.weasis.core.api.image.util.Unit;
import org.weasis.core.api.util.ResourceUtil;
import org.weasis.core.api.util.ResourceUtil.ActionIcon;
import org.weasis.core.ui.Messages;
import org.weasis.core.ui.model.utils.bean.MeasureItem;
import org.weasis.core.ui.model.utils.bean.Measurement;
import org.weasis.core.ui.util.MouseEventDouble;
import org.weasis.core.util.MathUtil;

@XmlType(name = "ellipse")
@XmlRootElement(name = "ellipse")
public class EllipseGraphic extends **ObliqueRectangleGraphic** {`
....

 - OS: Windows 10
 - Weasis Version [4..0.2]

**Comment by nroduit** [comment]
The tools for drawing rectangles and ellipses have evolved and now allow you to draw these shapes in any direction when previously it was only in the x and y axes.

This feature was [desired by users](https://github.com/nroduit/Weasis/issues/194) and allows a rotation of the canvas while still being able to edit all shapes.

The ellipse is drawn by tracing its major axis and adjusting its width. Then, it is just necessary to get used to the control points that have changed: some allow both resizing and rotation and others change the size and move on one of the axes.

If there are things that need to be improved, first describe the changes precisely and then make sure to find the implementation consistent with all the drawing mechanisms.

**Comment by nroduit** [comment]
See https://github.com/nroduit/Weasis/issues/404

Please reopen this issue if it has not been resolved in the current version.
