### ISSUE TITLE
Volumetric Rendering Feature

### ISSUE THREAD

**Issue by yvedant** [nroduit/Weasis#348]
Hello! While I was exploring the tool, I found that the only feature that was missing was the Volumetric Rendering. This is very widely used in cases of Oncology. It would be a great to have feature. 

Thanks and keep up the good work 👍

**Comment by nroduit** [comment]
See https://github.com/nroduit/Weasis/issues/329

**Comment by nroduit** [comment]
see https://github.com/nroduit/Weasis/issues/389
