### ISSUE TITLE
Duplicate the same location ROI at different series

### ISSUE THREAD

**Issue by m0705327** [nroduit/Weasis#349]
**Is your feature request related to a problem? Please describe.**
It is not possible to quickly draw ROIs at the same position on different sequence images. I have to compare values between different sequences.

**Describe the solution you'd like**
Copy and paste function when selecting the ROI(s), and it must be able to operate on different series (views).

**Describe alternatives you've considered**
Rectangle or circle can use the center, height, width and angle to copy the same position as much as possible. But this method cannot be used for polygons

Hi, I searched the online help page, tutorial and the github issue, and neither mentioned copying ROI or similar functionality.
Hope you can add this feature in the next version.
Thanks.

**Comment by nroduit** [comment]
This is possible by using the context menu and selecting one or more graphics.

![image](https://user-images.githubusercontent.com/993975/200817808-fe13dc43-2285-47f4-9ef8-e51b16cf724e.png)

![image](https://user-images.githubusercontent.com/993975/200817835-ee4430e1-f8d3-4af0-abc0-84fa5ae14fda.png)

**Comment by m0705327** [comment]
Thanks, I usually use the right click as the pan function so it will not automatically jump out of the menu function when selecting the ROI.
