### ISSUE TITLE
Image is not successfully saved to DCM4CHE after edit in weasis

### ISSUE THREAD

**Issue by mikite** [nroduit/Weasis#351]
I installed weasis in dcm4che，it seems that these marks aren't saved to dcm4che after draw marks on the opend images.
Marks aren't displayed when reopen in weasis from dcm4che web, any suggestion?

**Comment by nroduit** [comment]
Could you elaborate by giving an example with screenshots because currently I don't understand the problem.

**Comment by mikite** [comment]
I drawed a yellow rectange on the image then close Weasis. While reopen this yellow rectange disappears. I wanna know wheather Weasis not save the mark or I miss some steps?
![image](https://user-images.githubusercontent.com/5226661/201683728-270e17cd-cf09-404a-8443-e00586de54ec.png)

**Comment by nroduit** [comment]
The drawings must be saved in a DICOM PR, see the [documentation](https://nroduit.github.io/en/tutorials/build-ko-pr/index.html#presentation-state-pr-or-gsps) .

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
