### ISSUE TITLE
mv: cannot stat 'build-installer/Weasis-4.0.2.msi': No such file or directory

### ISSUE THREAD

**Issue by mikite** [nroduit/Weasis#352]
When I try to build installer on windows with command:

**weasis-distributions/script/package-weasis.sh --input ./weasis-distributions/target/native-dist/weasis-native --output build-installer --jdk /home/.jdks/temurin-18.0.1**

error shows: **mv: cannot stat 'build-installer/Weasis-4.0.2.msi': No such file or directory**

I'm not sure how to fix this, should I change the build-installer.yml to adjust my local build enironment?
Any suggestion will be appreciated, thanks!

**Comment by nroduit** [comment]
The documentation has been [updated](https://nroduit.github.io/en/getting-started/building-weasis/).

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
