### ISSUE TITLE
Weasis doens't load all DICOM-files if opened off a DFS/network-share

### ISSUE THREAD

**Issue by GitWork0ne** [nroduit/Weasis#353]
Weasis doesn't load all DICOM-Files, if they're loaded from a Network share (as in UNC-Path - \\server\share\) or a DFS-path that points to a share.

1. Select a folder or files with the open-dialog "local device" / "dicomdir" or drag&drop them into the view-area of Weasis.
2. Click on 'Import and Close' / wait for the pictures to load
4. Not all pictures of the selected files/folder/dicomdir are loaded

**Expected behavior**
All imported files are opened

**Desktop:**
- OS: Windows 10 22H2 (VDI/VM)
- Weasis Version 4.0.3

**Workaround**
If i map that same share to a drive-letter or from the local C:\-drive, all pictures are loaded correctly.
My tests were consistent. It always loaded the same images. In some cases/scans, everything was loaded. So it may be that its not that reproducable with all pictures.

**Traces**
[boot-1.0.log](https://github.com/nroduit/Weasis/files/10089662/boot-1.0.log)
[default.log](https://github.com/nroduit/Weasis/files/10089663/default.log)
[boot-0.0.log](https://github.com/nroduit/Weasis/files/10089664/boot-0.0.log)

Thank you in advance

**Comment by nroduit** [comment]
This behavior is normal because a network-share is not a file system. Indeed it is possible to see it as a file system only if the share is mapped with a letter.

Otherwise, it is possible [to use a URI ](https://stackoverflow.com/questions/10416736/reading-a-file-over-a-network-path)but only one image can be loaded at a time (the notion of a folder does not exist).

**Comment by GitWork0ne** [comment]
Thank you for clarifying. I'm just a little confused because it's not a clear scenario. Under the described circumstances some pictures consistently open, some never open. I also saw an error in the attached "default.log"
`org.weasis.dicom.codec.DicomMediaIO: Cannot read DICOM: java.lang.IllegalStateException`
After a quick search, it seems the error points to a method being called during an "illegal" time and that this could happen when a method gets called in an iteration/loop.
When i took a closer look on the error message, it leads me to the code that gets/uses the metadata of the files (DICOMMediaIO).
But this also makes no sense to me. If there would be a problem with the metadata/images/file share, it would be consistent so it should also not work on all other pictures or if i mapped it to a drive-letter.
I think at this point i need to stop trying to make sense of it and just map the share to a letter, to avoid any potential problems.
Thanks for your help

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
