### ISSUE TITLE
Reading DicomFile From  CD/DVD Drive is very slow

### ISSUE THREAD

**Issue by superdyco** [nroduit/Weasis#355]
**Describe the bug**

Reading Dicom From  CD/DVD Drive is very slow

I'm sure it's not a hardware problem, I use different Viewer does not happen

have any idea to fix it ?

**To Reproduce**
1. Export DICOM CD/DVD IMAGE And Checked [ADD Weasis] option
2. Export ISO and Burn to CD/DVD drive
3. Open Drive and execute run.bat, it takes about 5 minutes to start the program, and than takes about 1 minute to show Dicom

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Weasis Version 4.0.2

**Comment by nroduit** [comment]
Running the viewer on a CD is indeed quite slow.

As no direct solutions exist, there are 2 options to avoid this:

1. Read the CD with a locally installed viewer as described in README.html
2. Install the ISO on a USB stick.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
