### ISSUE TITLE
Could not find artifact org.weasis.core:weasis-core-img:pom:4.6.0-jdk11

### ISSUE THREAD

**Issue by learnr27** [nroduit/Weasis#358]
https://github.com/nroduit/mvn-repo/tree/master/org/weasis/core/weasis-core-img

**Comment by learnr27** [comment]
weasis-distributions/script/package-weasis.sh --input ./weasis-distributions/target/native-dist/weasis-native --output build-installer --jdk C:/Program Files/Java/jdk-17.0.5

![image](https://user-images.githubusercontent.com/11416545/207238219-cc20d541-fbaa-43af-8d48-b05de0ccbaa7.png)

**Comment by nroduit** [comment]
The master branch contains ongoing structural transformations and therefore requires modifications for the build scripts

**Comment by shivinfosystem** [comment]
facing same issue

![image](https://user-images.githubusercontent.com/29331063/208289764-404c4e36-8010-4460-a0c6-965fa319064c.png)

any solution and suggestion please.

**Comment by arunvc** [comment]
work around, 

1. build weasis-core-img
```
git clone https://github.com/nroduit/weasis-core-img.git
cd weasis-core-img
mvn clean install
```

2. add the jar to your mvn local repo
```
mvn install:install-file   \
-Dfile=<path_in_your_system>/weasis-core-img/target/weasis-core-img-4.6.0-jdk11.jar \ 
-DgroupId=org.weasis.core  \  
-DartifactId=weasis-core-img    \
-Dversion=4.6.0-jdk11  \
-Dpackaging=jar \
-DgeneratePom=true

```

**Comment by nroduit** [comment]
This issue has been fixed.
