### ISSUE TITLE
send transfer syntax configurable

### ISSUE THREAD

**Issue by marcheschi** [nroduit/Weasis#359]
Hi 
I think it could be very useful the possibility to be able to configure the store transfer syntax for cstore operations.
For example Implicit Little Endian or others. 
Thank you
Paolo

**Comment by nroduit** [comment]
By default, all transfer syntaxes found in the images are negotiated. I don't see the benefit of reducing the syntaxes. It may cause errors if the destination does not support the chosen syntax.

Currently when the destination does not support a syntax, the implicit or explicit little endian (decompression) is automatically negotiated.

**Comment by marcheschi** [comment]
Ok, I understand your point of view.
I'm facing a problem where the CD/DVD robot that I'm using is not capable to understand the transfer syntax coming from a new installed Multi Energy CT 
Using the new Unlimited Characters (UC) VR
https://dicom.innolitics.com/ciods/ct-image/multi-energy-ct-image/00189362/00189365/00189367
Simply the ROBOT fails , a workaround is to choose ILE in sending the images for example.
I

**Comment by nroduit** [comment]
You can use [dcmtk](https://support.dcmtk.org/docs/storescu.html) to force syntax. However, for jpeg color image, it is not a good idea.

Otherwise, you have to restrict the syntaxes on the robot if the configuration allows it.

**Comment by marcheschi** [comment]
Yes I solved the problem by using only ILE on the robot until we have a better solution from the vendor.
Thank you
