### ISSUE TITLE
Custom Export Folder Names

### ISSUE THREAD

**Issue by mervinTEE** [nroduit/Weasis#360]
Hi, I was wondering if there's any way we can customise our own export formats. The export output folder name seems to be cut off (attached image below). I'm using it on windows10,  Weasis 4.0.3. 

![image](https://user-images.githubusercontent.com/31720342/208342915-1b9030ec-54e5-4d1a-9366-a7a53cb7fcea.png)

**Comment by nroduit** [comment]
Currently, there is no option to remove the limit on the number of characters per folder. This ensures compliance for all systems and media.

**Comment by MervinTEE** [comment]
Will there be any way that we can tweak on our own or have some parts of the folder variables removed? For example, if I don't need "MR" is there any means for me to remove the variable to prevent it from be part of the folder name?

**Comment by nroduit** [comment]
No, the only option is to have a hash value instead of the folder name.
