### ISSUE TITLE
How to set 'authorization access token' when fetching an image to XML manifest(no WADO server) ?

### ISSUE THREAD

**Issue by windstar20** [nroduit/Weasis#364]
Hi

When I loading Weasis through WADO URL without server like below

**command test 1.**
`weasis://$weasis:config auth=[my token] $dicom:get -w "https://dev.mypath/weasis.xml"`

or

**command test 2.**
`weasis://$dicom:get -w "https://dev.mypath/weasis.xml"`

* The generated xml document on the path is the image below.
**https://dev.mypath/weasis.xml**
<img width="1491" alt="스크린샷 2022-12-28 오후 4 53 32" src="https://user-images.githubusercontent.com/62827205/210025483-3f18844c-ef3c-4c65-9ee1-62d78b27132e.png">

* Below is the weasis screen.
<img width="1391" alt="스크린샷 2022-12-28 오후 4 54 07" src="https://user-images.githubusercontent.com/62827205/210025724-23079ac1-90fe-429f-a73e-b99ce07aa2aa.png">

**but the image doesn't appear.**
The authorization accees token check when the image is fetched from the server.

i read weasis document many times. [https://nroduit.github.io/en](https://github.com/nroduit/Weasis/discussions/url)
**i'm waiting for your help. 🙏🏽**

**Comment by nroduit** [comment]
The parameter auth is for basic authentication.

If you generate the manifest on your own, you can add headers defined [here](https://github.com/nroduit/Weasis/blob/master/weasis-dicom/weasis-dicom-explorer/src/main/resources/config/manifest.xsd#L117-L122). 
Ex. `<httpTag key="Authorization" value="Bearer your-token" />`

**Comment by windstar20** [comment]
> The parameter auth is for basic authentication.
> 
> If you generate the manifest on your own, you can add headers defined [here](https://github.com/nroduit/Weasis/blob/master/weasis-dicom/weasis-dicom-explorer/src/main/resources/config/manifest.xsd#L117-L122). Ex. `<httpTag key="Authorization" value="Bearer your-token" />`

I don't know what to say! 🙏🏽
Thank you for your answer.
I solved the problem thanks to you.
