### ISSUE TITLE
LUT (black/white colour scales) of some plain radiographs becomes inverted after upgrading to Weasis 4.0.3

### ISSUE THREAD

**Issue by yufoon2002** [nroduit/Weasis#372]
After upgrading to Weasis 4.0.3, the LUT (black/white colour scales) of certain (but not all) plain radiograph becomes inverted (white colour becomes black colur and vice versa, radiograph image looks like fluoroscopy images). User has to click `invert LUT' in order to revert back to the correct / original LUT. The problem persists despite changing to different computers. The LUT of those plain radiograph could be properly displayed in the earlier versions of Weasis (e.g. 4.0.2 and 4.0.1) by default without the need to click `invert LUT'. Can you help me to investigate. Thank you very much.

**Comment by nroduit** [comment]
Are they associated with a DICOM Presentation State?

I need an example to provide an answer.

**Comment by yufoon2002** [comment]
I have prepared several dicom files for testing. You canr refer to the following link of the shared storage. Thank you very much.

https://drive.google.com/file/d/1oexFJZdxC-Wsqy6iaZ6eArAHe9COeBQP/view?usp=sharing

**Comment by nroduit** [comment]
According to my understanding, it is normal to display these images according to the pixel values because there are 2 successive inversions:

(0028,0004) | CS | PhotometricInterpretation | MONOCHROME1
-- | -- | -- | --
(2050,0020) | CS | PresentationLUTShape | INVERSE

See the [explanation](https://groups.google.com/g/comp.protocols.dicom/c/Wzt_06RbF5c) on the DICOM forum

**Comment by nroduit** [comment]
[inverted2.zip](https://github.com/nroduit/Weasis/files/10694697/inverted2.zip)

**Comment by nroduit** [comment]
Finally I got the confirmation that the previous implementation was correct. So I will change it again.

**Comment by yufoon2002** [comment]
> Finally I got the confirmation that the previous implementation was correct. So I will change it again.

Thank you very much for your help. You can take your time to fix it.
