### ISSUE TITLE
Radiograph images suddenly become very bright after slightly lower the window level in Weasis

### ISSUE THREAD

**Issue by yufoon2002** [nroduit/Weasis#373]
When I try to open certain radiographs in weasis, while I try to slightly lower the window level by dragging the mouse downwards, the images sudden becomes very bright and the window level and width becomes difficult to manipulate again afterwards. This happens in the latest Weasis 4.0.3 and also the earlier versions of Weasis. I test those radiographs in other dicom viewers in which the manipulaton of window level and window width works properly. I have attached a sample dicom for illustration. Thank you. very much for your help. 

https://drive.google.com/file/d/1BTG9zmA_xXBAjbiuoJWEY9jAawFhQ7Px/view?usp=sharing

**Comment by nroduit** [comment]
Thank you for reporting this problem. Indeed in this case the min/max values of the Level are not correct. It seems to be due to the fact that the VOI LUT has a higher range than the data which is really exceptional.

**Comment by yufoon2002** [comment]
> Thank you for reporting this problem. Indeed in this case the min/max values of the Level are not correct. It seems to be due to the fact that the VOI LUT has a higher range than the data which is really exceptional.

Thank you very much for your reply. Manipulation of images in Weasis is great most of the time for most of the images, but it happens that the above mentioned odd situation of bizzare windowing appearance occurs after minor manipulatoin of the the window level occasionally. I guess this may be due to some odd / infrequent setting by the acquiring radiographic machine or the operators. Anyway it would be great if enhancement in this issue can be made in the next release. Thank you very much again for your help.

**Comment by nroduit** [comment]
It has been fixed and will be in the next release.

**Comment by yufoon2002** [comment]
> It has been fixed and will be in the next release.

Thank you very much for your help.
