### ISSUE TITLE
Improvement of measure feature.

### ISSUE THREAD

**Issue by superegi** [nroduit/Weasis#374]
When you start your multiple measurement in the same exam you have to go to the menu and find and select the requested measurement. 
Example: in one exam I have to measure seven bones, and in each time I have to go to the menu losing a lot of time.
In the other hand, when you finish your measure you lose the ability of measure her the same thing again.

Allow shortcut configuration or settings, especially for meause features, like Cobb angle or open angle.
Allow to keep the same measure when you finish, because probably you will need to measure another segment right on the way.

![image](https://user-images.githubusercontent.com/50183741/217844406-a1a5bf53-523a-4a40-8740-137bad0f7ce8.png)
(English not my first language, sorry)

**Comment by nroduit** [comment]
There are possibilities to be more direct:
1) Select the graphics, copy and paste them on another image, see https://github.com/nroduit/Weasis/issues/349#issuecomment-1308608911
2) Uncheck "Draw only once"
![image](https://user-images.githubusercontent.com/993975/218093908-a1dfb400-bb29-4c2f-9c63-10faa3fe5406.png)

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
