### ISSUE TITLE
Cannot load DICOM DX with invalid patient orientation

### ISSUE THREAD

**Issue by Andersss747** [nroduit/Weasis#376]
Specific DICOMs doesn't open correctly in Weasis opened from local archive. Originally exported from RemoteEye Viewer. Can be imported without any problem to other DICOM-viewers. Weasis shows inverted picture of loaded DICOMs in DICOM explorer and crashes the function of the program.

**To Reproduce**
1. Import DICOMs from local archive.
2. See error

**Desktop (please complete the following information):**
 - OS: Edition	Windows 10 Enterprise Version 22H2 Installed on	‎22-‎06-‎2022 OS build19045.2604 Experience	Windows Feature Experience Pack 120.2212.4190.0
 - Weasis Version 4.0.3

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/125662878/219654298-f204f0a7-6fa2-4494-bb6e-249c2ffeff7a.jpg)

DICOMs not working: https://we.tl/t-HvjFgDSS5D

Thank you in advance!

**Comment by nroduit** [comment]
These files contain several invalid values. I guess due to anonymization.

The next release will allow to display these images even with not valid information (so ignored)

**Comment by Andersss747** [comment]
Hi!

Thank you for your rapid response. The result were the same before anonymization. I look forward to test the new update!

Have a nice day!

Bests
Anders
