### ISSUE TITLE
Weasis and Dicomizer don't start maximized within Compiz (in MX-Linux)

### ISSUE THREAD

**Issue by madmax2615** [nroduit/Weasis#383]
**Describe the bug**
On MX-Linux 19.4 xfce 64 bit (a Debian based distro), when Compiz is enabled, Weasis and Dicomizer do not start with a maximized window.
I always have to use the Maximize button in the upper right corner of the Weasis window manually, which is extremely annoying.
I even tried to fix that using the CompizConfig Settings Manager, but it didn't help.

**To Reproduce**
I went into...
Window management
Fixed Window Placement
Windows with fixed placement mode
There, I tried to associate the "Maximized" feature with the Weasis window title.
But no chance, Weasis still keeps on starting in window mode, i.e. not maximized.

I also tried to add the "--maximized" switch (without the "") to the starter of Weasis and Dicomizer, but still in vain.

That bug does not happen with Compiz disabled, but I definitely prefer Compiz enabled.

**Desktop (please complete the following information):**
I tried the .deb's of both Weasis 4.0.2 and 4.0.3 in vain (the amd64 version).
I even tried the weasis flatpak, but still no chance.

Even the uninstallation of the Weasis_....deb didn't work with Compiz enabled.
Weasis was still available even after I tried the uninstallation.
I had to switch from Compiz to Xfwm4 first, to get Weasis uninstalled properly.

Used versions:
MX-Linux 19.4 xfce 64 bit
compiz 2:0.8.18
Weasis 4.0.2 and 4.0.3 (deb or flatpak, of course, only one of these at a time)

Please, somebody, have a look at this!

EDIT:
Let me add, I'm on a dual screen system ,with the main screen on the right hand and I wonder, if there's a way to show the splash screen of Weasis and Dicomizer in the middle of the main screen. 
So far, the splash screen is being displayed somewhere on the left edge of the right screen, which doesn't look fine on a dual screen system.

**Comment by nroduit** [comment]
This could be related to the issue described in the UI framework. See https://github.com/JFormDesigner/FlatLaf/issues/632
Waiting for a new release.

**Comment by nroduit** [comment]
I have updated to Flatlaf 3.1. Could you try with the [current snapshot version](https://github.com/nroduit/Weasis/suites/12220368888/artifacts/646067055)?

**Comment by madmax2615** [comment]
@ nroduit 
I just tried that download.
When I used the deb of that package (because my MX Linux is a Debian based distro), there was almost no installation visible, and therefore I was quite confused, but afterwards I tried to start Weasis, as well as Dicomizer, and both of them did indeed appear maximized.

The only issue left now is that the white Weasis splash screen is displaced on my two monitor system.
It appears at the right edge of the left monitor, but my main monitor is the right one.
Is there any way to fix this, please, in order to make the splash screen appear in the middle on the main monitor, please?

**Comment by nroduit** [comment]
Thanks for your feedback. So I will close the issue.

I can't change the position of the first splash screen because it is linked to the native launcher. It should appear on the main screen.

The preferences can only act on the main window.

**Comment by madmax2615** [comment]
As for the splash screen, I usually have Compiz enabled. 
There are some more apps and tools with displaced windows, but I can move them to the wanted position by setting x and y coordinates within the "Window placing" section of the Compiz config settings manager.
This is possible as long as I have windows with title bars. 
But since splash screens don't have titles, I wonder, is there perhaps anything else I can use to make Compiz identify the splash screen of Weasis in order to move it to another position?
