### ISSUE TITLE
Dicom files can't be opened by double-clicking them from the system file explorer.

### ISSUE THREAD

**Issue by Siequu** [nroduit/Weasis#385]
hello
Dicom files can't be opened by double-clicking them from the system file explorer.
Program Weasis starts normally but without opened dicom file
**To Reproduce**
Click two times left button mouse on dicom file.
Weasis is my default dicom viewer

**Expected behavior**
Program open and i can see my content of dicom file

**Desktop (please complete the following information):**
 - OS: w10 21h2
 - Weasis Version : everyone

gratefully Michał

**Comment by nroduit** [comment]
Please provide a reproducible example because I do not observe this problem.

Does the file open correctly when opened from the File > Open > DICOM menu?

**Comment by Siequu** [comment]
I check on another pc with new installation of windows 10 and it worked fine. I will try format computer that doesn't work and check after it .

**Comment by Siequu** [comment]
hello this is my log. first half is open program with file dicom then normal open program without file:

02.06.2023 15:50:08.435 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
02.06.2023 15:50:08.545 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
02.06.2023 15:50:08.545 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 0 = C:\Users\user\Downloads\0003.DCM
02.06.2023 15:50:08.605 *INFO* [main] org.weasis.launcher.ConfigData: Properties: {weasis.user=user, weasis.name=Weasis, weasis.version=4.1.1, weasis.config.hash=-155083918, weasis.path=C:\Users\user\.weasis, weasis.launch.type=NATIVE, weasis.codebase.url=file:/C:/Program%20Files/Weasis/app, weasis.pref.local.session=true, weasis.codebase.local=C:\Program Files\Weasis\app, felix.extended.config.properties=file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties, felix.config.properties=file:/C:/Program%20Files/Weasis/app/conf/config.properties, weasis.source.id=64D59807, weasis.profile=default, http.agent=Weasis/4.1.1 (Windows 10; 10.0; amd64; pf:default; rv:4.1.1) Java/20.0.1}
02.06.2023 15:50:08.629 *INFO* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 57 468
02.06.2023 15:50:08.689 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = pl_PL
02.06.2023 15:50:08.689 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = pl_PL
02.06.2023 15:50:08.689 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = DEBUG
02.06.2023 15:50:08.690 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = true
02.06.2023 15:50:08.691 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 20
02.06.2023 15:50:08.691 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 20MB
02.06.2023 15:50:08.691 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 50
02.06.2023 15:50:08.691 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
02.06.2023 15:50:08.910 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of flatlaf.uiScale = null
02.06.2023 15:50:09.574 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
02.06.2023 15:50:09.575 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
02.06.2023 15:50:09.633 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = 3.6.2
  Current version = 4.1.1
  Application name = Weasis
  Application Source ID = 64D59807
  Application Profile = default
  Application local codebase = C:\Program Files\Weasis\app
  Application codebase URL = file:/C:/Program%20Files/Weasis/app
  Application configuration file = file:/C:/Program%20Files/Weasis/app/conf/config.properties
  Application extension configuration file = file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties
  User = user
  User home directory = C:\Users\user\.weasis
  Resources path = C:\Program Files\Weasis\app\resources
  Preferences directory = C:\Users\user\.weasis\preferences\user\default
  Look and Feel = org.weasis.launcher.FlatWeasisTheme
  Languages path = file:/C:/Program%20Files/Weasis/app/bundle-i18n/
  Languages available = 
  OSGI native specs = windows-x86-64
  HTTP user agent = Weasis/4.1.1 (Windows 10; 10.0; amd64; pf:default; rv:4.1.1) Java/20.0.1
  Operating system = Windows 10 10.0 amd64
  Java vendor = Eclipse Adoptium
  Java version = 20.0.1
  Java Path = C:\Program Files\Weasis\runtime
  Java max memory (less survivor space) = 2,9 GiB
***** End of Configuration *****
02.06.2023 15:50:09.636 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

02.06.2023 15:50:09.954 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-viewer2d-3.6.2
02.06.2023 15:50:09.965 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.osgi.util.function-1.1.0
02.06.2023 15:50:09.974 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: vecmath-1.7.0
02.06.2023 15:50:09.983 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-explorer-3.6.2
02.06.2023 15:50:09.994 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-send-3.6.2
02.06.2023 15:50:10.003 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-sr-3.6.2
02.06.2023 15:50:10.021 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.apache.felix.configadmin-1.9.18
02.06.2023 15:50:10.031 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-api-3.6.2
02.06.2023 15:50:10.040 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-qr-3.6.2
02.06.2023 15:50:10.050 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.osgi.util.promise-1.1.1
02.06.2023 15:50:10.060 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.apache.felix.metatype-1.2.2
02.06.2023 15:50:10.072 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-opencv-core-windows-x86-64-4.4.0-dcm
02.06.2023 15:50:10.084 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.apache.felix.gogo.shell-1.1.2
02.06.2023 15:50:10.094 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: jaxb-osgi-2.3.2
02.06.2023 15:50:10.104 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: slf4j-api-1.7.30
02.06.2023 15:50:10.113 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-au-3.6.2
02.06.2023 15:50:10.124 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-img-4.4.0.1
02.06.2023 15:50:10.136 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-ui-3.6.2
02.06.2023 15:50:10.146 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: docking-frames-1.1.3p1
02.06.2023 15:50:10.158 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.apache.felix.scr-2.1.20
02.06.2023 15:50:10.168 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.apache.felix.gogo.command-1.1.0
02.06.2023 15:50:10.178 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-codec-3.6.2
02.06.2023 15:50:10.189 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-viewer2d-3.6.2
02.06.2023 15:50:10.199 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: org.apache.felix.gogo.runtime-1.1.2
02.06.2023 15:50:10.209 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-ui-3.6.2
02.06.2023 15:50:10.220 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-wave-3.6.2
02.06.2023 15:50:10.230 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-imageio-codec-3.6.2
02.06.2023 15:50:10.240 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-viewer2d-i18n-2.0.0
02.06.2023 15:50:10.250 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-explorer-i18n-2.0.0
02.06.2023 15:50:10.259 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-send-i18n-2.0.0
02.06.2023 15:50:10.270 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-sr-i18n-2.0.0
02.06.2023 15:50:10.279 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-api-i18n-2.0.0
02.06.2023 15:50:10.289 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-qr-i18n-2.0.0
02.06.2023 15:50:10.300 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-au-i18n-2.0.0
02.06.2023 15:50:10.310 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-ui-i18n-2.0.0
02.06.2023 15:50:10.321 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-codec-i18n-2.0.0
02.06.2023 15:50:10.331 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-viewer2d-i18n-2.0.0
02.06.2023 15:50:10.347 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-ui-i18n-2.0.0
02.06.2023 15:50:10.358 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-wave-i18n-2.0.0
02.06.2023 15:50:20.415 *INFO* [main] org.weasis.launcher.WeasisLauncher: Logs has been delegated to the OSGI service and can be read in C:\Users\user\.weasis\log\default.log
02.06.2023 15:50:20.475 *SEVERE* [AWT-EventQueue-0] org.weasis.launcher.WeasisLauncher: Execute command
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.weasis.launcher.WeasisLauncher.commandSessionExecute(WeasisLauncher.java:648)
	at org.weasis.launcher.WeasisLauncher.lambda$executeCommands$4(WeasisLauncher.java:383)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.apache.felix.gogo.runtime.SyntaxError: bad unicode
	at org.apache.felix.gogo.runtime.BaseTokenizer.escape(BaseTokenizer.java:115)
	at org.apache.felix.gogo.runtime.BaseTokenizer.skipQuote(BaseTokenizer.java:153)
	at org.apache.felix.gogo.runtime.Tokenizer.next(Tokenizer.java:191)
	at org.apache.felix.gogo.runtime.Parser.next(Parser.java:289)
	at org.apache.felix.gogo.runtime.Parser.statement(Parser.java:326)
	at org.apache.felix.gogo.runtime.Parser.program(Parser.java:234)
	at org.apache.felix.gogo.runtime.Closure.<init>(Closure.java:84)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:178)
	... 17 more
02.06.2023 15:52:06.116 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
02.06.2023 15:52:06.200 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
02.06.2023 15:52:06.239 *INFO* [main] org.weasis.launcher.ConfigData: Properties: {weasis.user=user, weasis.name=Weasis, weasis.version=4.1.1, weasis.config.hash=-155083918, weasis.path=C:\Users\user\.weasis, weasis.launch.type=NATIVE, weasis.codebase.url=file:/C:/Program%20Files/Weasis/app, weasis.pref.local.session=true, weasis.codebase.local=C:\Program Files\Weasis\app, felix.extended.config.properties=file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties, felix.config.properties=file:/C:/Program%20Files/Weasis/app/conf/config.properties, weasis.source.id=64D59807, weasis.profile=default, http.agent=Weasis/4.1.1 (Windows 10; 10.0; amd64; pf:default; rv:4.1.1) Java/20.0.1}
02.06.2023 15:52:06.262 *INFO* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 57 477
02.06.2023 15:52:06.312 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = pl_PL
02.06.2023 15:52:06.312 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = pl_PL
02.06.2023 15:52:06.313 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = DEBUG
02.06.2023 15:52:06.313 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = true
02.06.2023 15:52:06.313 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 20
02.06.2023 15:52:06.314 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 20MB
02.06.2023 15:52:06.314 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 50
02.06.2023 15:52:06.314 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
02.06.2023 15:52:06.480 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of flatlaf.uiScale = null
02.06.2023 15:52:07.016 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
02.06.2023 15:52:07.017 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
02.06.2023 15:52:07.031 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = 4.1.1
  Current version = 4.1.1
  Application name = Weasis
  Application Source ID = 64D59807
  Application Profile = default
  Application local codebase = C:\Program Files\Weasis\app
  Application codebase URL = file:/C:/Program%20Files/Weasis/app
  Application configuration file = file:/C:/Program%20Files/Weasis/app/conf/config.properties
  Application extension configuration file = file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties
  User = user
  User home directory = C:\Users\user\.weasis
  Resources path = C:\Program Files\Weasis\app\resources
  Preferences directory = C:\Users\user\.weasis\preferences\user\default
  Look and Feel = org.weasis.launcher.FlatWeasisTheme
  Languages path = file:/C:/Program%20Files/Weasis/app/bundle-i18n/
  Languages available = 
  OSGI native specs = windows-x86-64
  HTTP user agent = Weasis/4.1.1 (Windows 10; 10.0; amd64; pf:default; rv:4.1.1) Java/20.0.1
  Operating system = Windows 10 10.0 amd64
  Java vendor = Eclipse Adoptium
  Java version = 20.0.1
  Java Path = C:\Program Files\Weasis\runtime
  Java max memory (less survivor space) = 2,9 GiB
***** End of Configuration *****
02.06.2023 15:52:07.034 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

02.06.2023 15:52:07.431 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-send-i18n
02.06.2023 15:52:07.442 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-viewer3d-i18n
02.06.2023 15:52:07.453 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-viewer2d-i18n
02.06.2023 15:52:07.463 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-viewer2d-i18n
02.06.2023 15:52:07.475 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-au-i18n
02.06.2023 15:52:07.486 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-explorer-i18n
02.06.2023 15:52:07.498 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-qr-i18n
02.06.2023 15:52:07.507 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-isowriter-i18n
02.06.2023 15:52:07.517 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-sr-i18n
02.06.2023 15:52:07.527 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-wave-i18n
02.06.2023 15:52:07.537 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-base-ui-i18n
02.06.2023 15:52:07.547 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-rt-i18n
02.06.2023 15:52:07.557 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-dicom-codec-i18n
02.06.2023 15:52:07.561 *INFO* [main] org.weasis.launcher.AutoProcessor: Uninstall unused bundle: weasis-core-i18n
02.06.2023 15:52:11.141 *INFO* [main] org.weasis.launcher.WeasisLauncher: Logs has been delegated to the OSGI service and can be read in C:\Users\user\.weasis\log\default.log

I think problem is written in but i didn't understand it:

02.06.2023 15:50:20.475 *SEVERE* [AWT-EventQueue-0] org.weasis.launcher.WeasisLauncher: Execute command
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.weasis.launcher.WeasisLauncher.commandSessionExecute(WeasisLauncher.java:648)
	at org.weasis.launcher.WeasisLauncher.lambda$executeCommands$4(WeasisLauncher.java:383)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.apache.felix.gogo.runtime.SyntaxError: bad unicode
	at org.apache.felix.gogo.runtime.BaseTokenizer.escape(BaseTokenizer.java:115)
	at org.apache.felix.gogo.runtime.BaseTokenizer.skipQuote(BaseTokenizer.java:153)
	at org.apache.felix.gogo.runtime.Tokenizer.next(Tokenizer.java:191)
	at org.apache.felix.gogo.runtime.Parser.next(Parser.java:289)
	at org.apache.felix.gogo.runtime.Parser.statement(Parser.java:326)
	at org.apache.felix.gogo.runtime.Parser.program(Parser.java:234)
	at org.apache.felix.gogo.runtime.Closure.<init>(Closure.java:84)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:178)
	... 17 more

**Comment by nroduit** [comment]
The file path according to this log looks OK
> 02.06.2023 15:50:08.545 INFO [main] org.weasis.launcher.ConfigData: Main arg 0 = C:\Users\user\Downloads\0003.DCM

But when the command is executed with that path, the parser says there's a non unicode character.
There may be an invalid hidden character.
> Caused by: org.apache.felix.gogo.runtime.SyntaxError: bad unicode
> at org.apache.felix.gogo.runtime.BaseTokenizer.escape(BaseTokenizer.java:115)
