### ISSUE TITLE
Localization does not work for weasis-core-api and weasis-core-ui in Weasis-snapshot after version 4.0.3.

### ISSUE THREAD

**Issue by AlexZaka** [nroduit/Weasis#386]
**Describe the bug**
Localization partially does not work for weasis-core-api and weasis-core-ui in Weasis-snapshot after version 4.0.3.

**To Reproduce**
1. Build and start latest Weasis-snapshot.
2. Try to change language to somewhat else than English.
3. Menu items File-Preferences-General and File-Preferences-Viewer are not localized.

**Desktop (please complete the following information):**
 - Mageia-8 Linux
 - Latest Weasis-snapshot Version
 
![Screenshot_20230408_101541](https://user-images.githubusercontent.com/105201856/230704655-8de5095f-421e-4142-a513-3be41fe8ac7b.png)

**Comment by nroduit** [comment]
This is due to the merging of the API and UI modules in version 4.1.0. The changes are in progress.
