### ISSUE TITLE
Unable to import thirdparty opencv dependencies in gradle build

### ISSUE THREAD

**Issue by sleepkever** [nroduit/Weasis#39]
When i try to import the provided Opencv dependencies in a gradle build I have, i get the following error:
```
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve org.weasis.thirdparty.org.opencv:opencv_java:4.0.0-dcmR2.
  Required by:
      project :
   > Could not resolve org.weasis.thirdparty.org.opencv:opencv_java:4.0.0-dcmR2.
      > inconsistent module metadata found. Descriptor: oorg.weasis.thirdparty.org.opencv:libopencv_java:4.0.0-dcmR2 Errors: bad group: expected='org.weasis.thirdparty.org.opencv' found='oorg.weasis.thirdparty.org.opencv'
        bad module name: expected='opencv_java' found='libopencv_java'
```
It looks like the modulename is not corrected after a copy operation and the group contains a typo.

**To Reproduce**
Have a gradle build with at minimum the following and one java file in the source directory:
```gradle
plugins {
    id 'java'
}

group 'weasis'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    maven {
        name = 'dcm4che-github'
        url "https://raw.github.com/nroduit/mvn-repo/master/"
    }
    mavenCentral()
}

dependencies {
    compile(group: 'org.weasis.thirdparty.org.opencv', name: 'opencv_java', version: '4.0.0-dcmR2') {
        artifact {
            name = 'opencv_java'
            type = 'dll'
            classifier = 'windows-x86-64'
        }
        artifact {
            name = 'opencv_java'
            type = 'dll'
            classifier = 'windows-x86'
        }
    }
}
```

**Expected behavior**
I can import the dependencies as required.

**Desktop:**
 - OS: macOs 10.13.6
 - Java Runtime: 1.8.0_181
 - Weasis Version: - 
 - Gradle version: 4.10.2

**Additional context**
I think that just fixing the typo will fix the issue but I'm not sure where this is stored in the build proces to fix it permananently. I could submit a PR for the current poms in the repository for you if that would help?

**Comment by nroduit** [comment]
It has been changed from 'oorg.weasis.thirdparty.org.opencv' to 'org.weasis.thirdparty.org.opencv'

**Comment by nroduit** [comment]
Should be fixed in the script and the [repository](https://github.com/nroduit/mvn-repo/commit/70edfbd8a407aeb81cb0ae698c10988d674b18cd)
