### ISSUE TITLE
Persistence of search criteria in the Q/R

### ISSUE THREAD

**Issue by vnmarcel** [nroduit/Weasis#400]
This is more like a feature request. Every time the DICOM Query/Retrive box is opened, the "search criteria" tab is empty. I think if it retains the last search criteria or even the last search result would be nice to save some repetitive mouse clicks.

Thanks

**Comment by nroduit** [comment]
I will change the behavior to apply the last item selected in the combo box when the Q/R window is opened.

In this way, it will be enough to click on Search to apply the criteria of the last selected item (and Empty will be the first and the default item).
