### ISSUE TITLE
Can't load 3D CT scan with odd size

### ISSUE THREAD

**Issue by botanikas** [nroduit/Weasis#414]
Can't load 3D CT scan. Program shows 100% status information and nothing going on. I have tried on several different PCs with different graphic cards and result is the same.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Weasis Version 4.1.0

![Screenshot_1](https://github.com/nroduit/Weasis/assets/46492387/e2dc2d19-8fa6-4fc3-a3e8-50ea9e74de43)
![Screenshot_2](https://github.com/nroduit/Weasis/assets/46492387/9df14067-95ec-467d-a2b6-b899c683cb0e)

**Comment by nroduit** [comment]
Please [activate the log files ](https://nroduit.github.io/en/tutorials/logging/)and transmit the result when loading the textures.

**Comment by botanikas** [comment]
[default.log](https://github.com/nroduit/Weasis/files/11528556/default.log)
[boot-0.0.log](https://github.com/nroduit/Weasis/files/11528558/boot-0.0.log)

**Comment by nroduit** [comment]
Some observations from the logs:
- The graphics driver (27.20.100.9171) is not the latest version available (27.20.100.9664)
- There are no errors when loading the volume
- The images have an odd size (397x397) which is not common and I have already noticed that it sometimes causes problems. Can you try to force the subsampling by modifying [the max size (X/Y) of the 3d texture](https://nroduit.github.io/en/tutorials/dicom-3d-viewer/index.html#3d-viewer)? Set 256 (will decrease the rendering quality)

**Comment by botanikas** [comment]
Changing 3d texture size to 256x256 solves the problem.
GPU driver is lockdown to PC manufacturer and it is latest available. If I try to completely uninstall with DDU tool and than install latest from Intel, I get device not started in device manager event tab. Overall it's not related to GPU, because the same situation on others GPU's

**Comment by nroduit** [comment]
I will try to reproduce the problem and see how it can be fixed

**Comment by botanikas** [comment]
Speaking about image size, our CT scans from odontology clinic, so area of interest is quite small.
