### ISSUE TITLE
PROBLEM: Weasis can't find my graphic card

### ISSUE THREAD

**Issue by Umacu** [nroduit/Weasis#420]
Hi. When I try to open the 3D viewer, Weasis launch me this:
![image](https://github.com/nroduit/Weasis/assets/134670150/6cc67aa7-3eda-44d0-a1a4-2774b99e06ec)

Then, when I check the preferences I see this:
![image](https://github.com/nroduit/Weasis/assets/134670150/024b866a-f97b-4d34-91b7-8e135c99cae1)

Even if I check "Enable" doesn't work. I've already checked my openGL version and supports 4.3 as says in the page: https://nroduit.github.io/en/tutorials/dicom-3d-viewer/index.html.
I have a GTX 1660 Ti, it works just fine on radiant. What's the problem here?
![image](https://github.com/nroduit/Weasis/assets/134670150/5ad5951f-d44b-4245-ac66-4ac3c7bc3806)

**Comment by nroduit** [comment]
You need to check the [log files](https://nroduit.github.io/en/tutorials/logging/) to see what happens on startup.

Check the [note section of the documentation](https://nroduit.github.io/en/tutorials/dicom-3d-viewer/index.html) if not the right card has been selected.

**Comment by botanikas** [comment]
I have had the same problem. I just deleted folder C:\Users\%USERPROFILE%\.weasis which contains configuration settings. For me, Weasis GUI sometimes can't save configuration. I have noticed with OpenGL support enable/disable and when changing texture size manually with keyboard number input, unless you change with up and down arrows.

**Comment by nroduit** [comment]
So I guess is more related to https://github.com/nroduit/Weasis/issues/421
