### ISSUE TITLE
Can't open compressed images on windows version

### ISSUE THREAD

**Issue by renatofs** [nroduit/Weasis#422]
On MAC version my exam open normal, but when I open the same exam on latest windows version I got an error about compressed image.

**To Reproduce**
Just open the attached images on weasis

**Expected behavior**
On MAC OS version the image open normally.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Weasis Version: 4.1.1

**Comment by nroduit** [comment]
There is no file. It is necessary to make a zip to be able to attach a file directly in the post.

**Comment by renatofs** [comment]
I've attached the file now, tks.

The same DICOM works on MAC and Linux, but not on Windows

[VX_exame_794347_1686158488262_corrompido_weasis.zip](https://github.com/nroduit/Weasis/files/11680301/VX_exame_794347_1686158488262_corrompido_weasis.zip)

**Comment by nroduit** [comment]
I've tried and I can open them without any problem on Windows 10 and 11.

The problem you're seeing is certainly related to the [256-character path limit on Windows 10](https://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows). Path of your files are already about 200 characters long.

**Comment by renatofs** [comment]
Hi,

It seems to meet that the problem is not that. I changed the file name, with a shorter one. Or that another way to fix it?

I also recorded a video to show you the problem.

Thank you in advance

https://www.loom.com/share/5ce4317d47784414874669d1f9f091bf

**Comment by nroduit** [comment]
Your file is not  [a dicom zip](https://dicom.nema.org/medical/dicom/current/output/chtml/part12/chapter_v.html). It should contain a dicomdir file and file should not be larger than 8 characters.

**Comment by nroduit** [comment]
You can use Weasis[ to create a DICOM ZIP](https://weasis.org/en/tutorials/dicom-export/index.html#dicom-export) (select export to DICOM ZIP).

**Comment by renatofs** [comment]
Thank you very much Nicolas,

But I still couldn't make it works. I tried changed the file name and also the structure.

What don't make sense to me is that some exams work and others not.

Can you change the folder that I sent to you and send to me for test.

**Comment by nroduit** [comment]
I checked again on Windows and I can confirm that it's simply a problem of path length, which is a limitation under Windows. By renaming the files, it works correctly.

Even if Weasis has a certain tolerance for reading DICOM ZIP, it is necessary to respect the DICOM standard which takes into account this limitation on certain systems or media.
Here is DICOM ZIP built with Weasis
