### ISSUE TITLE
Multiframe image fixed/varibale framerate (Frame Time Vector support 0018,1065)

### ISSUE THREAD

**Issue by ATSandrearicci** [nroduit/Weasis#424]
When a multiframe with variable or fixed framerate is open is not shown with the correct framerate.

Weasis should look in tag 0028,0009 FrameIncrementPointer to know where read the information about framerate.
If it points to 0018,1063 Frame Time the framerate is fixed at this nominal value. 
If it points to 0018,1065 Frame Time Vector framerate is variable and the time between frames is identified in this vector in millisecond

**Comment by nroduit** [comment]
Thank you for reporting this problem. I have implemented the use of the pointer. 

For the variable framerate, does it mean that the speed must change during the cine for a series? If so, can you provide a sample?

**Comment by ATSandrearicci** [comment]
Andrea Ricci has shared a OneDrive for Business file with you. To view it, click the link below.

[icon]
weasis_20230726_125723335.zip<https://atsmedsrl-my.sharepoint.com/personal/andrea_ricci_atsmed_it/Documents/weasis_20230726_125723335.zip>

Hi Nicolas,

It's me that have to say thank you for your job.
I'm glad to be able to help you making weasis even better.

Attached a file with variable framerate:

dcmdump 20230726125720698.RF.dcm +L -M +P 0018,1065
(0018,1065) DS [0,125,124,124,126,125,124,125,124,125,124,125,125,125,124,125,125,124,125,124,125,124,125,124,125,124,125,124,125,124,125,124,126,125,124,125,999,1001,998,1000,999,999,1001] # 172, 1 FrameTimeVector


I started @ 8 i/s and last frames was acquired @ 1 i/s.
Unfortunately, I have nothing but detector noise to show you right now.


Best regards

Andrea Ricci
System Engineer

***@***.***
Via A. Volta, 10 | 24060 Torre de' Roveri.BG.Italy
phone +39 035.584338
atsmed.it

**Comment by nroduit** [comment]
Can you please share again because I cannot download the sample?

**Comment by ATSandrearicci** [comment]
Let's try with wetransfer.

Andrea Ricci
System Engineer

***@***.***
Via A. Volta, 10 | 24060 Torre de' Roveri.BG.Italy
phone +39 035.584338
atsmed.it

**Comment by ATSandrearicci** [comment]
I sent a link with wetransfer some days ago.

Andrea Ricci
________________________________

**Comment by ATSandrearicci** [comment]
Link is expired now, i have to upload it again tomorrow.
Do you have any online pacs where i can store it, maybe?

Andrea Ricci
________________________________

**Comment by nroduit** [comment]
I've just checked and I haven't received any links.

Please send a link directly to my e-mail.

**Comment by ATSandrearicci** [comment]
I need a real email, probably.


Andrea Ricci
System Engineer

***@***.***
Via A. Volta, 10 | 24060 Torre de' Roveri.BG.Italy
phone +39 035.584338
atsmed.it

**Comment by ATSandrearicci** [comment]
Uploaded here:

https://www.atsmed.eu/download/weasis_20230726_125723335.zip

Andrea Ricci
System Engineer

***@***.***
Via A. Volta, 10 | 24060 Torre de' Roveri.BG.Italy
phone +39 035.584338
atsmed.it


From: Andrea Ricci
Sent: 11 August 2023 12:53
To: nroduit/Weasis ***@***.***>; nroduit/Weasis ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [nroduit/Weasis] Multiframe image fixed/varibale framerate (Frame Time Vector support 0018,1065) (Issue #424)

I need a real email, probably.


Andrea Ricci
System Engineer

***@***.***
Via A. Volta, 10 | 24060 Torre de' Roveri.BG.Italy
phone +39 035.584338
atsmed.it

**Comment by nroduit** [comment]
OK, I've got it!

**Comment by nroduit** [comment]
I implement the variable speed for multiframe but I think there is an issue with your sample. The multiple value separation of FrameTimeVector is a comma, whereas in[ DICOM it should be a backslash](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.4.html).
See https://github.com/nroduit/Weasis/issues/497
