### ISSUE TITLE
Patient name search NOT WORKING CORRECTLY.

### ISSUE THREAD

**Issue by drochinuk** [nroduit/Weasis#428]
### Describe the bug. What happened?

Im running WEASIS 4.1.2 last update, and when conducting a search on PATIENT NAME FIELD, using just a name and even the wildcard * it doesnt return any names, i can only do it using PATIENT ID, that works fine, but when using PATIENT NAME, noting is listed.

runing weasis on a macbook pro with MacOS ventura 13.4 

### What version of Weasis are you running?

weasis 4.1.2

### On which system the problem occurs?

macOS

### Relevant log output

```shell
as described above i get no results using patient name (only name) even using the wildcard
```

**Comment by nroduit** [comment]
This problem cannot be reproduced. It has been tested with different PACS.
More details are needed when querying, such as log output in Weasis and the system being queried.

**Comment by drochinuk** [comment]
Can I send a short video? Thanks and kind regardsDr. R. G. Rochin, ***@***.***@nuvimedix.comOn 21 Jun 2023, at 13:55, Nicolas Roduit ***@***.***> wrote:﻿
This problem cannot be reproduced. It has been tested with different PACS.
More details are needed when querying, such as log output in Weasis and the system being queried.

**Comment by nroduit** [comment]
I need the [log output](https://weasis.org/en/tutorials/logging/) of Weasis.

**Comment by AlexZaka** [comment]
I would like to clarify this problem. Usually some dates and modalities are used to filter studies. With default limit=10 it may result in a number of pages of studies. So staying on a page>1 if someone try to additionally filter studies with patient name, ID or so on, it may dramatically reduce the number of studies. Maybe one study or very few. But the current page is still >1.
I think the best solution is to reset current page to 1 if something is changed in search criteria.

**Comment by drochinuk** [comment]
Hi there and thanks for your input.  

Ive tried to upload the default.log and i get error message here "something went  really wrong and can't proccess that file"

Anyway exploring this further learned that serach is CASE sensitive, so I was able to make searches accordingly with the use of wildcards *

Thanks again, and kind regards I appreciate your imput.

22.06.2023 12:31:10.857 *INFO* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP[pcid=1, status=ff00H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
22.06.2023 12:31:10.857 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Command:
(0000,0002) UI [1.2.840.10008.5.1.4.1.2.2.1] AffectedSOPClassUID
(0000,0100) US [32800] CommandField
(0000,0120) US [1] MessageIDBeingRespondedTo
(0000,0800) US [0] CommandDataSetType
(0000,0900) US [65280] Status

22.06.2023 12:31:10.858 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Dataset:
(0008,0005) CS [ISO_IR 100] SpecificCharacterSet
(0008,0020) DA [20230504] StudyDate
(0008,0030) TM [100410] StudyTime
(0008,0050) SH [] AccessionNumber
(0008,0052) CS [STUDY] QueryRetrieveLevel
(0008,0054) AE [DCM4CHEE] RetrieveAETitle
(0008,0056) CS [ONLINE] InstanceAvailability
(0008,0061) CS [MR] ModalitiesInStudy
(0008,0080) LO [] InstitutionName
(0008,0090) PN [] ReferringPhysicianName
(0008,0201) SH [] TimezoneOffsetFromUTC
(0008,1030) LO [RM LUMBAR SYC] StudyDescription
(0010,0010) PN [MONTEJO HERNANDEZ ADAN] PatientName
(0010,0020) LO [405391] PatientID
(0010,0021) LO [] IssuerOfPatientID
(0010,0030) DA [19870201] PatientBirthDate
(0010,0040) CS [M] PatientSex
(0020,000D) UI [1.3.46.670589.11.48199.5.0.16052.2023050410040916050] StudyIns
(0020,0010) SH [725727849] StudyID
(0020,1206) IS [30] NumberOfStudyRelatedSeries
(0020,1208) IS [43] NumberOfStudyRelatedInstances

22.06.2023 12:31:10.858 *INFO* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP[pcid=1, status=ff00H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
22.06.2023 12:31:10.858 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Command:
(0000,0002) UI [1.2.840.10008.5.1.4.1.2.2.1] AffectedSOPClassUID
(0000,0100) US [32800] CommandField
(0000,0120) US [1] MessageIDBeingRespondedTo
(0000,0800) US [0] CommandDataSetType
(0000,0900) US [65280] Status

22.06.2023 12:31:10.858 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Dataset:
(0008,0005) CS [ISO_IR 100] SpecificCharacterSet
(0008,0020) DA [20230413] StudyDate
(0008,0030) TM [085757] StudyTime
(0008,0050) SH [] AccessionNumber
(0008,0052) CS [STUDY] QueryRetrieveLevel
(0008,0054) AE [DCM4CHEE] RetrieveAETitle
(0008,0056) CS [ONLINE] InstanceAvailability
(0008,0061) CS [PR\MR] ModalitiesInStudy
(0008,0080) LO [] InstitutionName
(0008,0090) PN [] ReferringPhysicianName
(0008,0201) SH [] TimezoneOffsetFromUTC
(0008,1030) LO [RM CRANEO] StudyDescription
(0010,0010) PN [ORDONEZ HERNANDEZ CRISTIAN DANIEL] PatientName
(0010,0020) LO [413670] PatientID
(0010,0021) LO [] IssuerOfPatientID
(0010,0030) DA [20000730] PatientBirthDate
(0010,0040) CS [M] PatientSex
(0020,000D) UI [1.3.46.670589.11.48199.5.0.16052.2023041308575628068] StudyIns
(0020,0010) SH [726501476] StudyID
(0020,1206) IS [29] NumberOfStudyRelatedSeries
(0020,1208) IS [40] NumberOfStudyRelatedInstances

22.06.2023 12:31:10.858 *INFO* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP[pcid=1, status=ff00H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
22.06.2023 12:31:10.858 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Command:
(0000,0002) UI [1.2.840.10008.5.1.4.1.2.2.1] AffectedSOPClassUID
(0000,0100) US [32800] CommandField
(0000,0120) US [1] MessageIDBeingRespondedTo
(0000,0800) US [0] CommandDataSetType
(0000,0900) US [65280] Status

22.06.2023 12:31:10.859 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Dataset:
(0008,0005) CS [ISO_IR 100] SpecificCharacterSet
(0008,0020) DA [20230519] StudyDate
(0008,0030) TM [102138] StudyTime
(0008,0050) SH [] AccessionNumber
(0008,0052) CS [STUDY] QueryRetrieveLevel
(0008,0054) AE [DCM4CHEE] RetrieveAETitle
(0008,0056) CS [ONLINE] InstanceAvailability
(0008,0061) CS [PR\MR] ModalitiesInStudy
(0008,0080) LO [] InstitutionName
(0008,0090) PN [] ReferringPhysicianName
(0008,0201) SH [] TimezoneOffsetFromUTC
(0008,1030) LO [RM RODILLA DER] StudyDescription
(0010,0010) PN [OROZCO HERNANDEZ YAMILEM DEL ROSARIO] PatientName
(0010,0020) LO [080997] PatientID
(0010,0021) LO [] IssuerOfPatientID
(0010,0030) DA [19970908] PatientBirthDate
(0010,0040) CS [F] PatientSex
(0020,000D) UI [1.3.46.670589.11.48199.5.0.16752.2023051910213384018] StudyIns
(0020,0010) SH [727024895] StudyID
(0020,1206) IS [29] NumberOfStudyRelatedSeries
(0020,1208) IS [494] NumberOfStudyRelatedInstances

22.06.2023 12:31:10.859 *INFO* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP[pcid=1, status=ff00H
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
22.06.2023 12:31:10.859 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Command:
(0000,0002) UI [1.2.840.10008.5.1.4.1.2.2.1] AffectedSOPClassUID
(0000,0100) US [32800] CommandField
(0000,0120) US [1] MessageIDBeingRespondedTo
(0000,0800) US [0] CommandDataSetType
(0000,0900) US [65280] Status

22.06.2023 12:31:10.859 *DEBUG* [pool-6-thread-1] org.dcm4che3.net.Dimse: WEASIS_QR->DCM4CHEE(3) >> 1:C-FIND-RSP Dataset:
(0008,0005) CS [ISO_IR 100] SpecificCharacterSet
(0008,0020) DA [20230616] StudyDate
(0008,0030) TM [075058] StudyTime
(0008,0050) SH [] AccessionNumber
(0008,0052) CS [STUDY] QueryRetrieveLevel
(0008,0054) AE [DCM4CHEE] RetrieveAETitle
(0008,0056) CS [ONLINE] InstanceAvailability
(0008,0061) CS [PR\MR] ModalitiesInStudy
(0008,0080) LO [] InstitutionName
(0008,0090) PN [] ReferringPhysicianName
(0008,0201) SH [] TimezoneOffsetFromUTC
(0008,1030) LO [RM CERVICAL] StudyDescription
(0010,0010) PN [RODRIGUEZ HERNANDEZ GUADALUPE] PatientName
(0010,0020) LO [188491] PatientID
(0010,0021) LO [] IssuerOfPatientID
(0010,0030) DA [19581212] PatientBirthDate
(0010,0040) CS [M] PatientSex
(0020,000D) UI [1.3.46.670589.11.48199.5.0.13912.2023061607505787000] StudyIns
(0020,0010) SH [726760257] StudyID
(0020,1206) IS [35] NumberOfStudyRelatedSeries
(0020,1208) IS [421] NumberOfStudyRelatedInstances

**Comment by nroduit** [comment]
Yes by default it is case-sensitive but if you query in uppercase it is case-insensitive. See this [post](https://groups.google.com/g/dcm4che/c/zz2JbCwah5s).

**Comment by Shkurat1975** [comment]
Good afternoon. I have a similar problem with Weasis 4.1.2: if in DICOM reception/transmission in the search criteria in the Patients Name field use Cyrillic, then the search is not performed correctly. A list of studies is displayed in the name of which the number of characters is the same as the word entered in the search. Please help with this problem.

**Comment by nroduit** [comment]
@Shkurat1975 There is no demonstrated problem with the original issue. So it's necessary to open another issue and describe the problem with logs. It's important to demonstrate that the problem concerns Weasis and not the PACS.

**Comment by Shkurat1975** [comment]
Thank you. I'll do that.
