### ISSUE TITLE
Add shortcut to close current patient/image with "Ctrl+W" 

### ISSUE THREAD

**Issue by unsafeunaudited** [nroduit/Weasis#429]
### Is your feature request related to a problem? (optional)

I was expecting Weasis to have the basic functionality of closing the active image or patient with a shortcut, usually Ctrl+W. It is the same shortcut for closing the active elements in Firefox, Chrome, Windows Explorer, and other programs such as MS Office, LibreOffice, GNOME Apps, etc.

### Description of the new feature/enhancement

Pressing Ctrl+W would close the actively loaded image, same as pressing the close [X] button with the label  "Remove this view from the screen"

### Additional context (optional)

First post on Github. Sorry I am a Radiologist, not a coder (hopefully that would change in the future). Love the project - Weasis. Much appreciated FOSS alternative.

**Comment by nroduit** [comment]
This shortcut is in the docking library and is currently ctrl + F4.

I will try to change it and also display the tab shortcuts in the contextual menu.
