### ISSUE TITLE
Images blanking out randomly

### ISSUE THREAD

**Issue by hashitha** [nroduit/Weasis#43]
**Describe the bug**
When scrolling through CTs sometimes all the images blank out. This issue is random so very difficult to reproduce. This has happened on 3 different computers all running windows 10 and latest weasis build. I have also noticed that this happens mainly after doing and mpr.

This issue is not there on version 2.6.3. 

![image](https://user-images.githubusercontent.com/10569142/48269113-ba219300-e471-11e8-80b7-8d4042ff8b1c.png) 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - java version 1.8.0_161
 - Weasis Version 3.0.3

**Comment by nroduit** [comment]
Did you try with a release version?
How do you run weasis ? portable / JWS / from the IDE
Do you launch several instances at the same time?

**Comment by hashitha** [comment]
Did you try with a release version? Yes, I have tried version 3.0.0-RC1, 3.0.1, 3.0.3 all have the same problem. I feel like it might be an issue with opencv because when it was blank I had someone connect to my computer via Teamviewer for something else and the images started working again.

How do you run weasis? Running it in windows portable

Do you launch several instances at the same time?  Only one instance is running

**Comment by nroduit** [comment]
Are you running a 32-bit JRE?
Did you try to change the max memory allocated in viewer-win32.l4j.ini?

**Comment by hashitha** [comment]
I have tried setting max memory with no luck. 
Java runtime is 1.8.0_144-b01 
yes it is running 32 bit
I can try 64 bit, but where do I set that up?

**Comment by nroduit** [comment]
Since version 3, I would recommend using a 64-bit JRE as the 64-bit implementation is now complete.

Currently, If you have 32 and 64-bit JRE installed on your system, the portable distribution will choose the 32-bit version. This will change in the next release 3.1. So at the moment uninstall the 32-bit JRE.

If you run the 32-bit version, try to reduce the memory allocated, like:
```
# Min and max memory of the application, default values are "-Xms64m" and "-Xmx768m"
-Xms64m
-Xmx256m
```
Let me know if it changes something

**Comment by hashitha** [comment]
I set the memory as you said and it works better but the issue is still there. I will try 64 bit and see

**Comment by hashitha** [comment]
@nroduit I have now tested with 64 bit in windows 10. I have removed and installed 64bit from here 
https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

with no luck and I have also change the memory to 
```
# Min and max memory of the application, default values are "-Xms64m" and "-Xmx768m"
-Xms64m
-Xmx256m
```
with no luck. This is with the latest code

**Comment by nroduit** [comment]
I've seen the issue you described but only with old 32-bit PC. You can see in the About window what is the running architecture (should be windows-x86-64):
![selection_021](https://user-images.githubusercontent.com/993975/49380613-5f96f200-f712-11e8-913f-5b8bd989acd6.png)
Another problem could be the access to the images (e.g. an Internet security software or anitivirus).

The next release of weasis will contain the final release 4 of opencv. So I can share with you a portable version to test.

**Comment by nroduit** [comment]
Please try the new [native package](https://nroduit.github.io/en/getting-started/). Reopen the issue if you do not believe the issue to be resolved.
