### ISSUE TITLE
Only view/downloading 100 dicom instances while using DICOM Web (Web Node)

### ISSUE THREAD

**Issue by jaymaity-tws** [nroduit/Weasis#436]
### Describe the bug. What happened?

Using Windows version
connected to Dicom Web from Azure.
It is downloading only 100 dicom instances for a particular series.

### What version of Weasis are you running?

4.1.2

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
Please provide information that enables us to observe the problem and/or reproduce it with a detailed procedure.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
