### ISSUE TITLE
Weasis doesn't detect CD-ROM under Debian 12

### ISSUE THREAD

**Issue by Aztks** [nroduit/Weasis#437]
### Describe the bug. What happened?

Weasis doesn't detect CD-ROM under Debian 12. It doesn't see the DICOMs or DICOMDIRs even when manually choosing the folder.
Same goes for files shared over the LAN. Only locally copied files work.

### What version of Weasis are you running?

4.1.2

### On which system the problem occurs?

Linux

### Additional contextual elements

debian 12, Lenovo ThinkCentre M710q, Intel® Core™ i5-7400T × 4, Mesa Intel® HD Graphics 630 (KBL GT2), 8 gb RAM

**Comment by nroduit** [comment]
Which is the installer type DEB, SNAP, or Flatpack?

Weasis cannot open files on a network drive which is not a file system, see https://github.com/nroduit/Weasis/issues/353

**Comment by Aztks** [comment]
> Which is the installer type DEB, SNAP, or Flatpack?
Hi, SNAP.

**Comment by Aztks** [comment]
Hi, I removed the SNAP and installed the deb. Now it all works - reads CDs and accesses the mounted network share.

**Comment by nroduit** [comment]
SNAP package runs in a constrained environment (sandbox). The [configuration](https://github.com/nroduit/Weasis/blob/master/snap/snapcraft.yaml#L98-L118) should allow removable devices but I noticed this is not always the case.
