### ISSUE TITLE
Selected graphic does not get updated

### ISSUE THREAD

**Issue by eduardomineo** [nroduit/Weasis#44]
Selected graphic (Draw & Measure) does not get updated.

1. Open Weasis
2. Import some DICOM Image
3. Add some drawing or measure to the first image of the series
4. Scroll to the next image and add some drawing or measure
5. Go back and forth scrolling the series: the table of properties at Draw&Measure tab only gets updated when graphics of the first image is selected

I managed to get it work properly by editing org.weasis.core.ui.editor.image.DefaultView2d.setImage and adding the call eventManager.updateComponentsListener(this) after each call to setGraphicManager.

 - OS: Windows 10
 - jdk1.8.0_191
 - Weasis 3.0.3 (Release)

![weasis](https://user-images.githubusercontent.com/17097594/48435119-cb64eb00-e762-11e8-8903-c950f3ef7dc8.gif)

**Comment by nroduit** [comment]
This bug is a regression.

I'm not sure adding eventManager.updateComponentsListener(this) is the right way to fix the issue because it will trigger a lot of operations.

**Comment by eduardomineo** [comment]
Thanks!
