### ISSUE TITLE
Option to show a colorbar mapping to LUT

### ISSUE THREAD

**Issue by bilal-tasdelen** [nroduit/Weasis#441]
### Description of the new feature/enhancement

Correct me if I am wrong, but currently I could not find an option to show a colorbar mapping the values of the LUT. This is very useful when looking at the quantitative maps (e.g. T1, T2, diffusion, B1 maps in MRI). Having that would be very valuable for quantitative imaging.

Sometimes scanners automatically embed one DICOMs, but they are typically low resolution and hard to read. 

### Proposed technical implementation details (optional)

Attached is an example of how it looks like from another tool.
![image](https://github.com/nroduit/Weasis/assets/7375605/12538702-6357-4d30-97e9-c944beb73185)

**Comment by nroduit** [comment]
By going to the display panel and selecting Lookup Table, you can display the pseudo-color bar with modality values (e.g. Hounsfield for CT).

You can also display the [histogram](https://weasis.org/en/tutorials/histo/) linked to modality values and the windowing value that modifies color mapping.

![image](https://github.com/nroduit/Weasis/assets/993975/0798fd2d-618e-4e6d-9910-1fd5a1d193ab)

**Comment by bilal-tasdelen** [comment]
@nroduit Oh, I totally missed the Lookup Table option in the display panel, my bad! Thank you so much!
Closing...
