### ISSUE TITLE
Auto Scroll to next serious after reaching the end of cuurent serious 

### ISSUE THREAD

**Issue by dontrantino** [nroduit/Weasis#444]
### Is your feature request related to a problem? (optional)

no

### Description of the new feature/enhancement

Can we add an option ( on / off ) as continiuos scrolling .
while scrolling on a serious , if the option is on the view continue scrolling to the next serious with mouse scroll.
Auto Scroll to next serious after reaching the end of cuurent serious

**Comment by nroduit** [comment]
Currently, some major features with a high priority must be implemented and the resources on this project are very limited. We need contributors for this kind of feature.

**Comment by nroduit** [comment]
This feature is available in other ways: navigate through the Patient/Study/Series/Image structure using only keyboard shortcuts. See Tip on this [page](https://weasis.org/en/tutorials/dicom-explorer/).
