### ISSUE TITLE
Loading Serious from Orthanc web 

### ISSUE THREAD

**Issue by dontrantino** [nroduit/Weasis#445]
### Describe the bug. What happened?

Loading a study from othanc web take a bit longer when the study has more than 500 images .
Can we make it load the first image of the sequences then load the rest to make it more fast while loading the study .

### What version of Weasis are you running?

4.1.2

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
I'm sorry, but I don't understand either the problem or the proposed improvement.

Please provide information that enables us to observe the problem and/or reproduce it with a detailed procedure.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
