### ISSUE TITLE
MalformedURLException error when fetching instance-level data via DICOMweb

### ISSUE THREAD

**Issue by simas112** [nroduit/Weasis#469]
### Describe the bug. What happened?

**Description:**
When launching Weasis via a browser with a specified DICOMweb URL, I am encountering a java.net.MalformedURLException error. This error suggests that the base URL provided in the initial call isn't being concatenated or passed along correctly to subsequent calls made by Weasis. This problem arises even though the same request works as expected via Postman.

**URL used:** 
weasis://$dicom:rs --url "http://127.0.0.1:9998/dicomweb/qido" -r "studyUID=1.3.12.2.1107.5.1.4.105623.30000022070607060960700000028" -H "x-header: aAFcadfga45FDa"

**The following error message is observed in the logs:**
20.09.2023 14:21:15.977 *ERROR* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS all instances with seriesUID 1.3.12.2.1107.5.1.4.105623.30000022070606171892000001108 java.net.MalformedURLException: no protocol: /dicomweb/studies/1.3.12.2.1107.5.1.4.105623.30000022070607060960700000028/series/1.3.12.2.1107.5.1.4.105623.30000022070606171892000001108/instances?includefield=00080018,00200013,00081190

### What version of Weasis are you running?

4.2.0

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
First, you need to use a URL that represents all dicomweb services, not just Qido see this [issue](https://github.com/DICOMcloud/DICOMcloud/issues/59).

Then the retrieve URL can be the one provided by the server if the server returns RetrieveURL, see a similar [issue](https://github.com/nroduit/Weasis/issues/432).
