### ISSUE TITLE
Key Image creation and load

### ISSUE THREAD

**Issue by RoshniVijay** [nroduit/Weasis#47]
**Describe the bug**
When Creating key object selection, the key image informaion is written to 0040,a375 instead of 0040,a730 tag.
Similarly while reading a kos, weasis reads from a375 tag and marks all the sop instances referred as key images, which is wrong.
Similary while creating key images for multiframe data, the frame details are not added

**To Reproduce**
1. Go to '...' Load a multiframe data
2. Click on '....' Mark and image frame as key image say 5th frame out of 10
3. Scroll down to '....' Export the data
4. See error : check the tags for key image sop instances.- Data only present in a375. no sop instance information in a730 tag which is incorrect. similarly the frame number of the key image is also not available.

**Expected behavior**
The correct key images are present in a730 tag, and it has to be read from (and written to) this tag.

**Desktop (please complete the following information):**
 - OS: Windows
 - Java Rutime: Any version
 - Weasis Version [e.g. 3.0.3]

**Additional context**
Add any other context about the problem here [e.g. network issue: give information about anti-virus or network security software, firewall, proxy...]. 

**Screenshots**

**Traces**
If applicable, add log files from Weasis, Java Runtime or PACS.

**Comment by nroduit** [comment]
According to my knowledge, the mandatory attribute to reference the key images is Current Requested Procedure Evidence Sequence (0040,A375). See the DICOM standard:
http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.6.2.html#table_C.17.6-2

Let me know why do you think it is wrong.

**Comment by nroduit** [comment]
Reopen the issue if you do not believe the issue to be resolved.
