### ISSUE TITLE
Delete multiple measurement in single click instead of One by one

### ISSUE THREAD

**Issue by arunjoshtech** [nroduit/Weasis#477]
### Description of the new feature/enhancement

Dear team,
After making multiple measurement over particular images if I need to delete I have to do in one by one. Instead I want to to delete multiple measurement line in single mouse functionality either by select multiple measurement line and delete or delete all measurement

**Comment by nroduit** [comment]
Please check the [documentation](https://weasis.org/en/basics/shortcuts/index.html#graphics) first.

**Comment by arunjoshtech** [comment]
Thanks for your reply and support
