### ISSUE TITLE
Defect on screen (everything red)

### ISSUE THREAD

**Issue by jignacioe860** [nroduit/Weasis#478]
### Describe the bug. What happened?

When i open WeAsis, every button is red and without transparency, so I can see nothing.
In preferences, it does not allow me to change de red color.
![Captura de pantalla 2023-10-20 122829](https://github.com/nroduit/Weasis/assets/148568018/06545ce3-e7e8-45f3-83af-cc3395be2999)

### What version of Weasis are you running?

4.2.0

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
Is it a version downloaded from the [website](https://weasis.org/en/getting-started/download-dicom-viewer)?

**Comment by nroduit** [comment]
[Provide the boot log file](https://weasis.org/en/tutorials/logging/)

**Comment by jignacioe860** [comment]
[boot-0.0.log](https://github.com/nroduit/Weasis/files/13057055/boot-0.0.log)

**Comment by jignacioe860** [comment]
I have another called "boot-0.0.log.lck" that I can not upload.

I just realized that when I reinstalled the program it opens normally (without the error) but when it opens automatically (when I open a patient to write a radiology report) the problem appears again.

**Comment by jignacioe860** [comment]
![image](https://github.com/nroduit/Weasis/assets/148568018/176a597a-18cf-431b-8242-f2aff0bba83e)

**Comment by nroduit** [comment]
You launch Weasis with a command that modify the resources:
```
20.10.2023 14:43:21.322 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 0 = weasis://%24dicom%3Aget%20-w%20https%3A%2F%2Fsantaclara.informemedico.com.ar%2Fcgi-bin%2Fwado%2Fweasis%2F65097%20%24weasis%3Aconfig%20pro%3Dweasis.resources.url%20https%3A%2F%2Fsantaclara.informemedico.com.ar%2Fweasis%2Fresources.zip/

java.io.FileNotFoundException: C:\Users\Espa 56\.weasis\data\7B8F7A00\resources\svg\logo\WeasisAbout.svg (El sistema no puede encontrar la ruta especificada)
```
Do not install both versions (msi and store)

**Comment by jignacioe860** [comment]
What do I have to do? 
 In this moment, I only have the store version and it continues.

PS: I don't launch it myself, it automatically from a web, I don't know if that changes something.

Thank you for your time and support.

**Comment by nroduit** [comment]
Sorry, but the following don't come from the official version:
https://santaclara.informemedico.com.ar/weasis/resources.zip

We do not provide support for problems caused by modifications.
