### ISSUE TITLE
About DCM parsing Chinese garbled characters

### ISSUE THREAD

**Issue by DDX1126** [nroduit/Weasis#480]
### Is your feature request related to a problem? (optional)

When the patient's name in the DCM file is Chinese, garbled characters will occur

### Description of the new feature/enhancement

I want to parse the Chinese when parsing the DCM file

**Comment by nroduit** [comment]
Please provide an example and describe the good and bad results.
Otherwise, this request will not be processed.

**Comment by nroduit** [comment]
The description you provided is too vague or incomplete to allow us to properly understand and implement it.

To reopen the issue and move forward with investigating the feature request, please provide more detailed information,
