### ISSUE TITLE
Cyrillic search returns "UNKNOWN" names

### ISSUE THREAD

**Issue by Aztks** [nroduit/Weasis#495]
### Describe the bug. What happened?

I get name "UNKNOWN" in search from the PACS server (Orthanc) whenever the name is in Cyrillic.
(The Cyrillic name is displayed correctly in Orthanc explorer.)
Could this be fixed somehow?

### What version of Weasis are you running?

4.2.0

### On which system the problem occurs?

Linux

### Additional contextual elements

![image](https://github.com/nroduit/Weasis/assets/45974840/7efbf353-9c59-47ac-976e-93487160fc68)

**Comment by nroduit** [comment]
Please supply DICOM logs, see this [page](https://weasis.org/en/tutorials/logging/) to activate the rolling log files.

In Weasis, when the name equals null, it is replaced by "UNKNOWN".  There is no known encoding problem for Q/R. Have you tried another Q/R tool?

**Comment by Aztks** [comment]
[default.log](https://github.com/nroduit/Weasis/files/13447957/default.log)

Here's a log. Whats q/r?
You may notice the cyrillic name is properly written in the log - "БАКСИ", but it doesn't show in the search result - it shows as UNKNOWN.

**Comment by Aztks** [comment]
Resolved - changed the default encoding in the config of Orthanc to UTF8 (it was default Latin1).

**Comment by Aztks** [comment]
.

**Comment by nroduit** [comment]
Also the metadata seem to not fully consistent:

`23.11.2023 10:10:23.961 *WARN* [Image Downloader-pool-11-thread-1] org.weasis.dicom.codec.utils.DicomMediaUtils: Inconsistent Patient ID + Issuer of Patient ID between DICOM objets: 0218UNKNOWN and 0218БАКСИ`
