### ISSUE TITLE
font size setting of Labels on image does not affect actually.

### ISSUE THREAD

**Issue by a347807131** [nroduit/Weasis#498]
### Describe the bug. What happened?

1, change the specified setting
2, draw an whatever shap
3, then its measure text size does not change.

---

### debug report.

i found its size come from view2d component throght method `public Font getFont()`，but the component owns two ways to get the font size. the first that is correct is to get the font size from ViewCanvas interface, howerver its overrode but by its super class `JComponent`.

### What version of Weasis are you running?

4.1.2

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
Yes, this is an old feature that is no longer active. I don't think it's a good idea to set an absolute value, as the entire graphical interface can change [depending on the scaling factor](https://weasis.org/en/tutorials/theme/).

This feature should be removed or converted to relative values.

**Comment by nroduit** [comment]
Fixed in next release, It will use the [flatlaf scale fonts](https://www.formdev.com/flatlaf/typography/)

**Comment by a347807131** [comment]
nice done, boddy.
