### ISSUE TITLE
Allows configuring HTTP timeout of WADO through properties

### ISSUE THREAD

**Issue by nroduit** [nroduit/Weasis#50]
Name of system property:
UrlConnectionTimeout (default value is 5000 ms)
UrlReadTimeout (default value is 15000 ms)

Set a new value:
System.setProperty("UrlReadTimeout", 20000);
At launch: -DUrlReadTimeout=20000

**Comment by ranasrule** [comment]
Where are these properties supposed to be configured in Weasis when accessing via JNLP ?

**Comment by ranasrule** [comment]
I'm launching Weasis via JNLP and have set the new properties in the JNLP file but I dont think they are being applied...please see screenshot below at the following link >>> https://i.imgur.com/TeeZUd4.png
