### ISSUE TITLE
SR

### ISSUE THREAD

**Issue by doQLiV** [nroduit/Weasis#500]
### Describe the bug. What happened?

The structured report is not imported.

### What version of Weasis are you running?

4.2.1

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
Thank you for your bug report. Unfortunately, we are unable to investigate this bug without more information. Please provide more information about the bug, including the steps necessary to reproduce it and any relevant screenshots or [error logs](https://weasis.org/en/tutorials/logging/) (if possible a DICOM sample). Once we have more information, we can investigate the bug and determine if it is a valid issue.

**Comment by nroduit** [comment]
If you are unable to provide more information, we will be closing this issue.
