### ISSUE TITLE
IMPORT DICOM

### ISSUE THREAD

**Issue by drabinashsingh** [nroduit/Weasis#510]
### Is your feature request related to a problem? (optional)

SEARCH CRITERIA TAB NEEDS TO BE MORE USER FRIENDLY AND EASILY ACCESSIBLE. ( SEE THE INTERFACE OF RADIANT VIEWER)

### Description of the new feature/enhancement

IN THE DICOM SOURCE PAGE THERE SHOULD BE SEARCH CRIETERIA. IT IS WASTE OF TIME AND ENERGY TO USE 2 TABS FOR THE SAME THING EVERYTIME.

**Comment by unsafeunaudited** [comment]
Welcome!

@drabinashsingh Kindly edit your post as all caps text is considered uncultured and very much rude in online conversation.

With regards to "search criteria tab should be more user friendly" you did not even specify on how to fix the problem. Simply asking to copy a competing product is infringement on the copyright of Radiant. Also if you like Radiant so much, you should keep using it as it is a paid product and Weasis is volunteer work. 

Saying that Weasis wastes your time and energy is quite a thing to say to the face of the dev of a volunteer product.

The dev owes you nothing. Period.

**Comment by nroduit** [comment]
I share the comments above made by @unsafeunaudited.

In addition, the DICOM Query/Retrieve section is a secondary addition to the interface, to cover all methods of retrieving data from a PACS. However, the preferred way of using Weasis is to search in a third-party portal (Patient Record, PACS, VNA, RIS...) and then retrieve data with [pacs-connector integration](https://weasis.org/en/basics/customize/integration) or directly in DICOMWeb.

**Comment by nroduit** [comment]
Your issue is written in all caps, which is generally considered shouting in online communication. This isn't constructive or helpful to the project. Moreover, the arguments lack objective elements.

We're closing this issue.
