### ISSUE TITLE
‘Display DVH char’, there is no response after clicking this button；

### ISSUE THREAD

**Issue by nowpast** [nroduit/Weasis#521]
### Describe the bug. What happened?

I installed it on both mac and win computers. The latest version is used to view DICOM RT files. The display function is normal, but the DVH function does not respond;
<img width="1440" alt="image" src="https://github.com/nroduit/Weasis/assets/18032533/bdc23a5f-a8fd-4477-807c-3c3ed36e45aa">

### What version of Weasis are you running?

Latest version 4.3；

### On which system the problem occurs?

Windows, macOS

**Comment by nroduit** [comment]
As there have been a few changes to the RT module in version 4.3.0, please let me know if any exams are not displaying correctly.
