### ISSUE TITLE
Can't open DX studies

### ISSUE THREAD

**Issue by raitkook** [nroduit/Weasis#525]
### Describe the bug. What happened?

Every DX study that is from chest I'm getting "DICOM file cannot be read" error. All other DX studies are fine.

![image](https://github.com/nroduit/Weasis/assets/29194267/d3147aef-8b9b-4e5d-bf3c-38aa8760aa16)

### What version of Weasis are you running?

4.3.0

### On which system the problem occurs?

Windows

### Relevant log output

```shell
15.03.2024 12:47:06.167 *ERROR* [Dicom Model-pool-3-thread-1] org.weasis.dicom.codec.DicomMediaIO: Cannot read DICOM: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at org.dcm4che3.img.util.DicomObjectUtil.isPolygonValid(DicomObjectUtil.java:211)
	at org.dcm4che3.img.util.DicomObjectUtil.getShutterShape(DicomObjectUtil.java:191)
	at org.weasis.dicom.codec.utils.DicomMediaUtils.setShutter(DicomMediaUtils.java:322)
	at org.weasis.dicom.codec.DicomMediaIO.writeInstanceTags(DicomMediaIO.java:526)
	at org.weasis.dicom.codec.DicomMediaIO.setMimeType(DicomMediaIO.java:409)
15.03.2024 12:47:06.177 *INFO* [AWT-EventQueue-0] org.weasis.dicom.explorer.LoadDicom: End of loading DICOM locally
```

**Comment by nroduit** [comment]
This image contains a polygon shutter.

Could you share a sample?  It seems to me that there's a bug in this method that checks the validity of a polygon.

**Comment by raitkook** [comment]
File anonymized.

[IMG-0001-00001_anon.zip](https://github.com/nroduit/Weasis/files/14632905/IMG-0001-00001_anon.zip)

**Comment by nroduit** [comment]
Thanks for providing a sample. I can confirm that this is indeed a bug. It will be fix in the next release.

**Comment by nroduit** [comment]
However, this shutter is strange in that it displays the entire image. It doesn't do its job of masking an area of the image.
