### ISSUE TITLE
MIP rebuild resets the image preset

### ISSUE THREAD

**Issue by spacemanssd** [nroduit/Weasis#528]
### Describe the bug. What happened?

MIP is very useful for detecting lung nodules. 
Some CT's though may have only the mediastinum window on their Dicom files. On these cases I change the **Image Preset** to **Lung**.
![image](https://github.com/nroduit/Weasis/assets/40655140/a74cdfe5-db95-4c31-bd99-1e823e3ddf02)
Then when I click on "Build MIP" the image preset resets to default! 
![image](https://github.com/nroduit/Weasis/assets/40655140/7c9ae46f-f99f-42f4-9695-c9a5089b07de)

_Feature Suggestion:_ It would be extremely useful to be able to change the MIP settings throw the "Image tool panel"!!

### What version of Weasis are you running?

4.3.0

### On which system the problem occurs?

Windows

**Comment by nroduit** [comment]
As the MIP view is very particular, we'd have to make a lot of changes to make all the tools accessible, and no longer have a modal window. Moreover, a future version will include the MIP view in 3D views.

So the simplest change is to integrate the windowing and presets into the MIP window. When the series is rebuilt, the current windowing is saved if it doesn't exist in the presets.
