### ISSUE TITLE
oblique MPR feature.

### ISSUE THREAD

**Issue by mostafasabra** [nroduit/Weasis#578]
### Is your feature request related to a problem? (optional)

no the feature is not related to bug

### Description of the new feature/enhancement

oblique MPR feature. the ability to rotate image in MPR View with sychronized all layout

**Comment by arunjoshtech** [comment]
In reality this feature is most needed and wanted  and user shifting to Radiant by referring this lack of tools

**Comment by nroduit** [comment]
Duplicate of https://github.com/nroduit/Weasis/issues/390

@arunjoshtech  As a user of this open-source application, you already benefit from its powerful features free of charge. If you need the oblique MPR immediately, you can use paid alternatives. Alternatively, if you'd rather see features in Weasis, you can participate, whether it's coding, testing or feedback that can help extend its capabilities over time.

**Comment by a347807131** [comment]
@nroduit where i could get the alternatives by the way? And is there any possiblility for you to share with me your docs and codes you already got if convenient？ I also want to develop this feat in Weasis.
Thanks for your works.

**Comment by nroduit** [comment]
@a347807131 The oblique MPR has been published in the current master branch. However, there are still improvements to be made. It should be included in the next release.
