### ISSUE TITLE
How to compare two study at different date?

### ISSUE THREAD

**Issue by xiaoluGood** [nroduit/Weasis#611]
### Description of the new feature/enhancement

hi. What if the same body part of the same patient is study at different date? It is need to synchronize the position or image index 
 of number and position line

**Comment by nroduit** [comment]
In DICOM, the [Frame of Reference UID](https://dicom.innolitics.com/ciods/ct-image/frame-of-reference/00200052) defines a shared spatial coordinate system across series. When this UID is the same between two series, it means that the spatial coordinates (e.g., location and orientation of voxels) are expressed in the same 3D coordinate system. So the viewer can automatically define a common position.

For the synchronization of different exams, they have to be done manually as long as they don't share the same Frame of Reference UID and for the moment there are no such tools.

**Comment by xiaoluGood** [comment]
Thank you for your answer.
