### ISSUE TITLE
3D Stl file Open Does not work

### ISSUE THREAD

**Issue by marcheschi** [nroduit/Weasis#68]
Hi
I have a study with 3D Stl model and PDF embedded dicom files.
I can import in viewer both files and I can open PDF with external viewer, 

I tried to do the same with Stl 3d file but I'm not able to open, it does not show anything.

**To Reproduce**
Try with the attached file:

[stlpaolo.dcm.zip](https://github.com/nroduit/Weasis/files/2889517/stlpaolo.dcm.zip)

**Expected behavior**
To be able to open it with external default 3D Viewer
**Desktop (please complete the following information):**
 - OS: Linux mint 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Java Rutime:  java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

- Weasis Version: 3.1.0-SNAPSHOT also on 3.0.4
![image](https://user-images.githubusercontent.com/3910408/53173282-a5fc3e80-35e7-11e9-8b49-bc112a2cf64b.png)

**Comment by nroduit** [comment]
Weasis accept to load any encapsulated DICOM but it will map to a system application associated with the file extension.

It would be possible to view the STL file with the OpenCV library integrated into Weasis, but it will require some integration effort.

Currently, some major features with a high priority must be implemented and the resources on this project are very limited. So we need contributors to implement this kind of features.

**Comment by marcheschi** [comment]
Hi
Thank you for your reply,
I installed meshlab on my linux but it seems that weasis does not call meshlab (with xdg-open).
So I added application/octet-stream (this is how xdg-open recognize the file ) to meshlab.desktop and I did a:

sudo xdg-mime default meshlab.desktop application/octet-stream

I added a workaround with a bash script to call a proper renamed .stl file because meshlab does not open tmp files.
In the end I succeeded in open the file.

This is tricky, maybe could be useful an option in preferences in order to open  a specific mime-type with the right executable.
Thank you
Paolo

**Comment by nroduit** [comment]
It wasn't correct what I said. Weasis try to open the default application associated with the mime type defined in the DICOM (in your case: (0042,0012) [LO] MIMETypeOfEncapsulatedDocument: model/stl).

So you need an application that registers the mime type "model/stl".

**Comment by marcheschi** [comment]
Hi
The stl file is not recognized by xdg-open as model/stl but instead as application/octet-stream

$ xdg-mime query filetype stl_tac_binary.stl 
application/octet-stream

Paolo

**Comment by nroduit** [comment]
Yes but application/octet-stream is something generic.

I miss something, the model/stl mime type has been registered recently by the DICOM standard, see https://www.iana.org/assignments/media-types/model/stl

Currently the stl file is [extracted with an .tmp extension](https://github.com/nroduit/Weasis/blob/master/weasis-dicom/weasis-dicom-codec/src/main/java/org/weasis/dicom/codec/DicomEncapDocSeries.java#L59) because model/stl is not defined [here](https://github.com/nroduit/Weasis/blob/master/weasis-core/weasis-core-api/src/main/resources/mime-types.properties#L417). I will add model/stl to the list so the extracted file will have the .stl extension.

**Comment by marcheschi** [comment]
Yes I agree.
So I have created a .local/share/mime/packages/application-stl.xml

<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
    <mime-type type="application/stl">
        <comment>stl 3d file</comment>
        <icon name="application-stl"/>
        <glob-deleteall/>
        <glob pattern="*.stl"/>
    </mime-type>
</mime-info>

Installed it with:
xdg-mime install ~/.local/share/mime/packages/application-stl.xml

Now 
$ xdg-mime query filetype stl_tac_binary.stl
application/stl

Now this is correct.

This modification of weasis  will solve the problem of Meshlab.

Thank you

Paolo
