### ISSUE TITLE
build error: weasis-dicom-codec

### ISSUE THREAD

**Issue by chaohuang** [nroduit/Weasis#80]
I'm following the [instructions](https://nroduit.github.io/en/getting-started/building-weasis/) to build Weasis on Windows, but I get the following error when I install the plug-ins by running `mvn clean install`:

[ERROR] Failed to execute goal on project weasis-dicom-codec: Could not resolve dependencies for project org.weasis.dicom:weasis-dicom-codec:bundle:3.5.2-SNAPSHOT: Could not find artifact org.weasis:weasis-dicom-tools:jar:5.16.2-SNAPSHOT

The screenshot:
![image](https://user-images.githubusercontent.com/1179764/58054480-8a81d080-7b0f-11e9-950c-44a3a2812555.png)

My system information:
 - OS: Windows 10
 - Java version "1.8.0_211"
 - Javac 12.0.1
 - Java SE Runtime Environment (build 1.8.0_211-b12)

**Comment by nroduit** [comment]
This a temporary situation before releasing weasis-dicom-tools:jar:5.16.2. You can build https://github.com/nroduit/weasis-dicom-tools
