### ISSUE TITLE
DICOM query retreive

### ISSUE THREAD

**Issue by djamelmaila** [nroduit/Weasis#88]
i can't dind the DICOM Query/retreive botton in my weasis.
**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Java Rutime: JRE-8_191-x64
 - Weasis Version [e.g. 3.1.0]

**Comment by nroduit** [comment]
![Sélection_007](https://user-images.githubusercontent.com/993975/61429667-7dbf0480-a927-11e9-8a9d-f0c85a7e73d9.png)
