### ISSUE TITLE
Weasis Viewer does not open new Study Tab if a study was already loaded in Dicom Explorer

### ISSUE THREAD

**Issue by devon-mahadevan** [nroduit/Weasis#89]
**Describe the bug**
We are facing the problem that Weasis Viewer does not open a new Study Viewer/Image Tab if a study was already loaded and included in the Dicom Explorer (leftbar). 
We are using Weasis Viewer with Java Web Start from Dcm4CHee GUI.
We also reproduced this behaviour on your Live Demo.

Thank you very much for you help.

Regards,
Devon

**To Reproduce**
To reconstruct the issue you can following this steps on your demo viewer:

1. you open study from Patient Test Compression in Weasis Viewer
2. you open study from Patient Test, Photometric in same Weasis Viewer - > you have now 2 Viewer Tabs
3. you close study from Test Compression  -> by clicking on (X) Viewer Tab
4. you open again study from Test Compression -> **Weasis Viewer does not create/open a new Tab -> you have to select manually the Patient Test Compression from the List**

![image](https://user-images.githubusercontent.com/52287252/60272296-29aa9c80-98f4-11e9-81ec-db8bcd7ffa8f.png)

**Expected behavior**
Is this a software issue/bug or do we have the possible to change Tabs behaviour/setting?

**Desktop:**
 - OS: Windows
 - Java Rutime: RE-8_191-x86-64
 - Weasis Version 3.0.3 & 3.0.4
- dcm4chee 5.13.3

**Comment by nroduit** [comment]
Implemented in https://github.com/nroduit/Weasis/issues/285
