### ISSUE TITLE
Query/Retrieve accessible as tool on main window with adjustable presets

### ISSUE THREAD

**Issue by mkauzlar** [nroduit/Weasis#92]
**Is your feature request related to a problem? Please describe.**
Every time I need to retrieve some studies from the PACS I need to go to Import DICOM --> Q/R --> Set the search parameters which are reset all the time --> Import

**Describe the solution you'd like**
It would be handy to have a Q/R button on the toolbar with defaults that can be set there (Modality, Time: Today, Yesterday, last week etc). Clicking again on Q/R button should continue querying with the last presets giving a list of results. At this point one just chooses the Study which gets automatically imported.

Thank you

**Comment by nroduit** [comment]
Implemented in https://github.com/nroduit/Weasis/issues/237 and https://github.com/nroduit/Weasis/issues/400
