### ISSUE TITLE
.deb Linux package crash: java.lang.IllegalArgumentException: invalid version

### ISSUE THREAD

**Issue by schirmermischa** [nroduit/Weasis#93]
I have installed the v3.5.1 .deb package without problems reported by the installer.
Upon launch, I get the following Warnings, and ultimately a "severe" exception:

org.weasis.launcher.WeasisLauncher: Cannot not start framework: java.lang.IllegalArgumentException: invalid version "": invalid format

Thank you very much for looking into this!

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/opt/Weasis/app/felix.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17.07.2019 17:16:09.211 *INFO* [FelixStartLevel] org.apache.sling.commons.log.internal.LogManager: LogManager: Logging set up from context
17.07.2019 17:16:09.411 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.
17.07.2019 17:16:09.412 *INFO* [FelixStartLevel] org.weasis.core.api.internal.cv.NativeOpenCVCodec: Native OpenCV is activated
17.07.2019 17:16:09.413 *INFO* [FelixStartLevel] org.weasis.core.api.internal.Activator: Register Image Codec Plug-in: OpenCV imgcodecs
17.07.2019 17:16:09.424 *INFO* [FelixStartLevel] org.weasis.core.api.internal.Activator: Register Image Codec Plug-in: Sun java imageio
17.07.2019 17:16:09.501 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Activate DicomCodec
17.07.2019 17:16:09.620 *INFO* [FelixStartLevel] org.weasis.core.api.internal.Activator: Register Image Codec Plug-in: dcm4che
17.07.2019 17:16:09.816 *INFO* [AWT-EventQueue-0] org.weasis.core.ui.internal.Activator: Register series viewer plug-in: Default System Application
17.07.2019 17:16:09.937 *INFO* [AWT-EventQueue-0] org.weasis.base.ui.gui.WeasisWin: End of loading the GUI...
17.07.2019 17:16:09.951 *INFO* [FelixStartLevel] org.weasis.base.ui.gui.WeasisWinListener: Activate the main window PropertyChangeListener
17.07.2019 17:16:09.960 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: SR => org.weasis.dicom.sr.SRElementFactory
17.07.2019 17:16:10.101 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: AU => org.weasis.dicom.au.AuElementFactory
17.07.2019 17:16:10.106 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: ECG => org.weasis.dicom.wave.WaveElementFactory
17.07.2019 17:16:10.107 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: HD => org.weasis.dicom.wave.WaveElementFactory
17.07.2019 17:16:10.123 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
17.07.2019 17:16:10.123 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Cannot not start framework: java.lang.IllegalArgumentException: invalid version "": invalid format

**Comment by schirmermischa** [comment]
I forgot to say that i'm running on kubuntu 18.04.

**Comment by nroduit** [comment]
I just try on a live cd and I don't see any issue.

Did you change something? because you have an empty version value!

**Comment by schirmermischa** [comment]
I haven't changed anything. I pulled the v3.5.1 deb package from the repository and run the executable "as is".

**Comment by schirmermischa** [comment]
Before trying the .deb package, I compiled weasis from source, but the viewer-linux.sh script ran into problems not finding its own configuration and .jar files. I have adjusted $curPath accordingly in that script, but then other files were not found, so I went for the binary instead.

**Comment by nroduit** [comment]
Could you run /opt/WeasisWeasis in CLI and post the configuration part especially "last running version" and "current version"

**Comment by nroduit** [comment]
There was something wrong with the previous version. I made a fix in the future release to let run even the old version is not valid.

Removing the folder {user}/.weasis should also solve the problem.
