### ISSUE TITLE
Issues on images with BitsAllocated (0028,0100) set to 16 and BitsStored (0028,0101) set to 8

### ISSUE THREAD

**Issue by jmcoelloidonia** [nroduit/Weasis#94]
**Describe the bug**
We've found a DICOM modality that somehow creates images with BitsAllocated (0028,0100) set to 16 but BitsStored (0028,0101) set to 8 and this doesn't seem to be rendering properly on weasis.

**To Reproduce**
1. Load a dcm with (0028,0100) set to 16 and BitsStored (0028,0101) set to 8

**Expected behavior**
It should render correctly, as shown in attachment.

**Desktop (please complete the following information):**
 - OS: Both Linux and Windows, 64-bits
 - Java Runtime: OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.19.04.2-b03)
 - Weasis Version: 3.5.2-SNAPSHOT (portable)

**Screenshots**
![470ac4e2-a261-11e9-9099-7aee65d9ab48_0_HD](https://user-images.githubusercontent.com/46027684/61452542-47e84300-a95c-11e9-91bf-8c1b340aa42f.jpg)
![470ac4e2-a261-11e9-9099-7aee65d9ab48](https://user-images.githubusercontent.com/46027684/61452547-4a4a9d00-a95c-11e9-9986-3ef343aa28fa.png)

**Comment by nroduit** [comment]
I never have a file with this configuration that seems a little absurd to me because we double the size with useless information!

Could you send me a sample?

**Comment by jmcoelloidonia** [comment]
Yes, no problem.

[470ac4e2-a261-11e9-9099-7aee65d9ab48.dcm.zip](https://github.com/nroduit/Weasis/files/3410619/470ac4e2-a261-11e9-9099-7aee65d9ab48.dcm.zip)

**Comment by nroduit** [comment]
This special case was not taken into account because the reader step was the bitstored rounded to the upper byte.
Fixed for 3.5.3.
