### ISSUE TITLE
How to Save measurements and annotations in XML file

### ISSUE THREAD

**Issue by mywsat** [nroduit/Weasis#95]
How to Save measurements and annotations in XML file
i have not idea to do this

**Comment by nroduit** [comment]
Currently, it used when exporting images with annotations into non dicom format (jpg, png, tiff).

The API is in this [class](https://github.com/nroduit/Weasis/blob/master/weasis-core/weasis-core-ui/src/main/java/org/weasis/core/ui/serialize/XmlSerializer.java).
