### ISSUE TITLE
Debug With Intellij 

### ISSUE THREAD

**Issue by zhan2016** [nroduit/Weasis#96]
**Describe the bug**
I'm using intellij to debug weasis. After UI start normal,  the Image didn't load normally. What's more, All the buttons and menus aren't clickable.

**To Reproduce**
1. maven install weasis-framework
2. edit configurations->add Application template->main class: org.weasis.launcher.WeasisLauncher, arguments:$dicom:get -l "E:\\image\\Liang Jin Min"
3. debug configure

**Expected behavior**
debug normally.

**Desktop (please complete the following information):**
 - OS: [Windows10 X64]
 - Java Rutime: [jdk 1.8]
 - Weasis Version [3.5.3]
-maven version [3.6.1]

**Additional context**
Add any other context about the problem here [e.g. network issue: give information about anti-virus or network security software, firewall, proxy...]. 

**Screenshots**
**debug configure**
![image](https://user-images.githubusercontent.com/20983133/62932101-15622680-bdf2-11e9-85cf-ea0489fd689d.png)

**start log seem fine**
![image](https://user-images.githubusercontent.com/20983133/62932016-f1064a00-bdf1-11e9-8961-7c44cb2afd92.png)

**maxium and cancel maxium, UI become black**
![image](https://user-images.githubusercontent.com/20983133/62931876-adabdb80-bdf1-11e9-83b1-116dccb2035f.png)
**not clickable**
![image](https://user-images.githubusercontent.com/20983133/62931935-d03df480-bdf1-11e9-87c6-64fbdb070d67.png)

**Traces**
If applicable, add log files from Weasis, Java Runtime or PACS.

**Comment by nroduit** [comment]
Please check the minimal configuration in VM options for debug: https://nroduit.github.io/en/getting-started/guidelines/#debug-or-run-from-eclipse
